import Foundation

// Message replies (WIRE_SPEC section 13). A reply is an ordinary chat text whose body is one JSON object that names the earlier
// message it answers:
//
//     {"qa_reply":1,"to":"<server message id>","k":"text","q":"<excerpt>","b":"<reply text>"}
//
// The reference to the quoted message travels INSIDE the end-to-end encrypted body: the server sees an ordinary message. Nothing
// here touches encryption, the ratchet, the outbox or the bytes on the network; the object is the plaintext of a normal text send.
//
// This file is the pure logic (recognition, strict parser, canonical builder, EXCERPT); `MessageReplyLocal.swift` resolves the quote
// against the rows of a conversation. The known-answer vectors (`reply-kat.json`, generated by the server repository's
// `tools/katgen/reply`) are run in full by `MessageReplyKatTests`.

/// `k`: the kind of the quoted message. `avatar` and `thumb` are not chat messages and are never quoted.
public enum MessageReplyKind: String, CaseIterable, Sendable {
    case text, file, image, video, voice
}

/// A valid reply, as decoded: `quote` is `q` exactly as received (never display it: use `displayedQuote`).
public struct MessageReply: Equatable, Sendable {
    /// The server message id of the quoted message (36 characters, lowercase hex with hyphens), as the sender wrote it.
    public let to: String
    public let kind: MessageReplyKind
    /// `q` as received. The receiver shows `displayedQuote`, never this.
    public let quote: String
    /// `b`: the text of the reply, the text the message shows.
    public let body: String

    public init(to: String, kind: MessageReplyKind, quote: String, body: String) {
        self.to = to
        self.kind = kind
        self.quote = quote
        self.body = body
    }

    /// What the quote block shows when `to` is not found among the local rows (section 13.4): `EXCERPT(q)`, nothing for a voice note.
    public var displayedQuote: String {
        kind == .voice ? "" : MessageReplyCodec.excerpt(quote)
    }
}

/// Why a recognised body was rejected. Telemetry only: a rejected body is shown as ordinary text, never lost and never an error.
public enum MessageReplyRejection: String, Equatable, Sendable {
    case badReply = "bad_reply"
    case unsupportedVersion = "unsupported_version"
}

/// What a chat body is when message replies are concerned (section 13.3).
public enum MessageReplyRecognition: Equatable, Sendable {
    /// Not a reply (the bytes do not begin with `{"qa_reply":`): handled as before.
    case notReply
    /// A valid reply.
    case reply(MessageReply)
    /// Recognised and rejected: the whole body is displayed as ordinary text.
    case rejected(MessageReplyRejection)
}

/// Why the builder refuses to send. The reason strings are those of the vector file.
public enum MessageReplyRefusal: String, Error, Equatable, Sendable {
    case to = "to"
    case kind = "k"
    case bodyEmpty = "b.empty"
    case bodyPrefix = "b.prefix"
    case size = "size"
}

public enum MessageReplyCodec {

    // MARK: Constants (section 13.2)

    public static let version: Int64 = 1
    /// `{"qa_reply":` compared as BYTES, never with `hasPrefix` (Swift compares grapheme clusters: a colon followed by a combining
    /// mark would be another character).
    public static let prefix: [UInt8] = Array(#"{"qa_reply":"#.utf8)
    /// Exclusive: the serialised reply is at most 8191 bytes.
    public static let maxBytes: Int = 8192
    public static let maxDepth: Int = 4
    public static let qMaxScalars: Int = 160
    public static let idLength: Int = 36

    /// The four prefixes user text may not begin with (section 12.7.1 entry points, extended by section 13.5).
    static var reservedPrefixes: [[UInt8]] {
        [FileV2Message.descriptorPrefix, FileV2Message.sourcePrefix, FileV2Message.cancelPrefix, prefix]
    }

    // MARK: Prefix tests

    public static func hasReplyPrefix(_ text: String) -> Bool {
        text.utf8.starts(with: prefix)
    }

    public static func hasReplyPrefix(_ body: Data) -> Bool {
        [UInt8](body).starts(with: prefix)
    }

    /// `true` iff the UTF-8 bytes of `text` begin with `{"qa_file":`, `{"qa_file_src":`, `{"qa_file_cancel":` or `{"qa_reply":`.
    /// User text that begins with one of them is refused as an ordinary message and as the `b` of a reply (section 13.5).
    public static func hasReservedPrefix(_ text: String) -> Bool {
        for candidate in reservedPrefixes where text.utf8.starts(with: candidate) {
            return true
        }
        return false
    }

    // MARK: Recognition and validation (section 13.3)

    /// Recognises and validates a body given as text (its UTF-8 bytes). Prefer the bytes as decrypted when they are at hand.
    public static func recognize(_ text: String) -> MessageReplyRecognition {
        guard text.utf8.starts(with: prefix) else { return .notReply }
        return recognize(utf8: Data(text.utf8))
    }

    /// Recognises and validates the body of a chat message exactly as decrypted: a byte-prefix test, the version, then the JSON
    /// profile of section 12.7.2 and the five members. Any failure after recognition is a rejection, never an error for the user.
    public static func recognize(utf8 body: Data) -> MessageReplyRecognition {
        let bytes = [UInt8](body)
        guard bytes.starts(with: prefix) else { return .notReply }
        // The version: the bytes after the prefix up to the first `,`, `}` or JSON whitespace (or the end), read before anything else.
        let versionStart = prefix.count
        var versionEnd = bytes.count
        var index = versionStart
        while index < bytes.count {
            let byte = bytes[index]
            if byte == 0x2C || byte == 0x7D || byte == 0x20 || byte == 0x09 || byte == 0x0A || byte == 0x0D {
                versionEnd = index
                break
            }
            index += 1
        }
        guard let number = FileV2JSONInteger.parse(Array(bytes[versionStart..<versionEnd])) else {
            return .rejected(.badReply)
        }
        guard number == version else { return .rejected(.unsupportedVersion) }
        switch FileV2JSONParser.parse(bytes) {
        case .failure:
            return .rejected(.badReply)
        case .success(let object):
            guard let decoded = decodeReply(from: object) else { return .rejected(.badReply) }
            return .reply(decoded)
        }
    }

    /// The five members of section 13.2, all required and typed. Unknown members were checked by the profile and are ignored.
    private static func decodeReply(from object: FileV2JSONObject) -> MessageReply? {
        guard case .number(let versionToken)? = object.value("qa_reply"),
              FileV2JSONInteger.parse(versionToken) == version else { return nil }
        guard case .string(let toBytes)? = object.value("to"), isServerMessageId(toBytes) else { return nil }
        guard case .string(let kindBytes)? = object.value("k"), let kind = kindOf(bytes: kindBytes) else { return nil }
        guard case .string(let quoteBytes)? = object.value("q") else { return nil }
        guard case .string(let bodyBytes)? = object.value("b") else { return nil }
        return MessageReply(to: String(decoding: toBytes, as: UTF8.self), kind: kind,
                            quote: String(decoding: quoteBytes, as: UTF8.self),
                            body: String(decoding: bodyBytes, as: UTF8.self))
    }

    /// The kind named by `bytes`, compared as bytes (`Text` is not `text`); `nil` for anything else, `avatar` and `thumb` included.
    static func kindOf(bytes: [UInt8]) -> MessageReplyKind? {
        for candidate in MessageReplyKind.allCases where Array(candidate.rawValue.utf8) == bytes {
            return candidate
        }
        return nil
    }

    /// `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`: 36 bytes, lowercase hex, hyphens at 8, 13, 18 and 23, no version
    /// check, as the server's `uuid.NewString()` writes it.
    static func isServerMessageId(_ bytes: [UInt8]) -> Bool {
        guard bytes.count == idLength else { return false }
        for (index, byte) in bytes.enumerated() {
            if index == 8 || index == 13 || index == 18 || index == 23 {
                if byte != 0x2D { return false }
                continue
            }
            let isDigit: Bool = byte >= 0x30 && byte <= 0x39
            let isLowerHex: Bool = byte >= 0x61 && byte <= 0x66
            if !isDigit && !isLowerHex { return false }
        }
        return true
    }

    /// Whether `id` is a server message id a reply may name.
    public static func isServerMessageId(_ id: String) -> Bool {
        isServerMessageId(Array(id.utf8))
    }

    /// The text a reply message SHOWS, wherever the body must not appear (bubble, preview, notification, search, copy): `b` for a valid
    /// reply, the whole body for anything else (a rejected reply is displayed as ordinary text, section 13.3).
    public static func shownText(ofBody body: String) -> String {
        if case .reply(let reply) = recognize(body) { return reply.body }
        return body
    }

    // MARK: EXCERPT (section 13.4)

    /// Step 1: removed. Inclusive ranges of scalar values.
    static let removedRanges: [ClosedRange<UInt32>] = [
        0x00AD...0x00AD, 0x061C...0x061C, 0x180E...0x180E, 0x200B...0x200B, 0x200E...0x200F, 0x202A...0x202E,
        0x2060...0x2064, 0x2066...0x2069, 0x206A...0x206F, 0xFEFF...0xFEFF, 0xFFF9...0xFFFB
    ]
    /// Step 2: replaced with U+0020.
    static let spacedRanges: [ClosedRange<UInt32>] = [0x0000...0x001F, 0x007F...0x009F, 0x2028...0x2029]

    private static func contains(_ ranges: [ClosedRange<UInt32>], _ value: UInt32) -> Bool {
        for range in ranges where range.contains(value) {
            return true
        }
        return false
    }

    /// `EXCERPT(x)`: one line of plain text of at most 160 scalar values. It works on Unicode scalar values (never `String.count`, which
    /// counts grapheme clusters): bidirectional and invisible characters are removed, controls and separators become a space, runs of
    /// spaces collapse and the ends are trimmed, then the first 160 scalars are kept. ZWJ and ZWNJ are kept; nothing is normalised.
    /// Idempotent. The builder writes `q = excerpt(source)`; the receiver displays `excerpt(q)`.
    public static func excerpt(_ text: String) -> String {
        var kept: [Unicode.Scalar] = []
        kept.reserveCapacity(min(text.utf8.count, qMaxScalars + 2))
        let space: Unicode.Scalar = " "
        for scalar in text.unicodeScalars {
            let value: UInt32 = scalar.value
            if contains(removedRanges, value) { continue }
            var current: Unicode.Scalar = scalar
            if contains(spacedRanges, value) { current = space }
            if current == space && (kept.isEmpty || kept[kept.count - 1] == space) { continue }
            kept.append(current)
            // Enough to know the first 160: what follows cannot change them.
            if kept.count > qMaxScalars { break }
        }
        if kept.count > qMaxScalars { kept.removeSubrange(qMaxScalars..<kept.count) }
        if let last = kept.last, last == space { kept.removeLast() }
        var view = String.UnicodeScalarView()
        view.append(contentsOf: kept)
        return String(view)
    }

    // MARK: Builder (section 13.5)

    /// The canonical text of a reply, or the reason it refuses. The user interface keeps the draft and says why.
    ///
    /// - to: the server message id of the quoted message, exactly as the server returned it.
    /// - kind: `text`, `file`, `image`, `video` or `voice`.
    /// - quoteSource: the text `q` is made from (the text of the quoted message, the `b` of a quoted reply, the `nm` of a quoted
    ///   file); `nil` when there is none.
    /// - quotedIsEphemeral: the quoted message has a lifetime (a timer or view-once): `q` is empty.
    /// - body: the reply text as the user wrote it; never cut, trimmed, normalised or sanitised.
    ///
    /// Compact JSON, the members in the fixed order `qa_reply`, `to`, `k`, `q`, `b`, all five always written; escaping as the descriptor
    /// builder; `q` is empty for a voice note and for an ephemeral quoted message, `EXCERPT(quoteSource)` otherwise. It refuses when
    /// `b` is empty, `b` begins with one of the four reserved prefixes, `to` or `kind` is not valid, or the text would reach 8192 bytes.
    /// It never shortens `b` and never drops or shortens `q` to make the text fit.
    public static func build(to: String, kind: String, quoteSource: String?, quotedIsEphemeral: Bool,
                             body: String) -> Result<String, MessageReplyRefusal> {
        guard isServerMessageId(Array(to.utf8)) else { return .failure(.to) }
        guard let parsedKind = kindOf(bytes: Array(kind.utf8)) else { return .failure(.kind) }
        if body.isEmpty { return .failure(.bodyEmpty) }
        if hasReservedPrefix(body) { return .failure(.bodyPrefix) }
        let noQuote: Bool = parsedKind == .voice || quotedIsEphemeral
        let quote: String = noQuote ? "" : excerpt(quoteSource ?? "")
        var out: [UInt8] = Array(#"{"qa_reply":1,"to":"#.utf8)
        FileV2DescriptorBuilder.string(&out, to)
        out.append(contentsOf: Array(#","k":"#.utf8))
        FileV2DescriptorBuilder.string(&out, parsedKind.rawValue)
        out.append(contentsOf: Array(#","q":"#.utf8))
        FileV2DescriptorBuilder.string(&out, quote)
        out.append(contentsOf: Array(#","b":"#.utf8))
        FileV2DescriptorBuilder.string(&out, body)
        out.append(UInt8(ascii: "}"))
        guard out.count < maxBytes else { return .failure(.size) }
        return .success(String(decoding: out, as: UTF8.self))
    }

    /// The canonical text of the valid reply `body` with an empty `q`, or `nil` when `body` is not a valid reply or its `q` is already
    /// empty. Used when the quoted message is deleted: the copy of its text that the reply carries must not outlive it (section 13.6: a row
    /// that is gone shows nothing of itself). `to`, `k` and `b` are kept exactly as they are, so it does not apply the refusals of the
    /// builder (an empty `b`, or one that begins with a reserved prefix, was accepted on reception and is rewritten as it is).
    public static func clearingQuote(ofBody body: String) -> String? {
        guard case .reply(let reply) = recognize(body), !reply.quote.isEmpty else { return nil }
        var out: [UInt8] = Array(#"{"qa_reply":1,"to":"#.utf8)
        FileV2DescriptorBuilder.string(&out, reply.to)
        out.append(contentsOf: Array(#","k":"#.utf8))
        FileV2DescriptorBuilder.string(&out, reply.kind.rawValue)
        out.append(contentsOf: Array(#","q":"#.utf8))
        FileV2DescriptorBuilder.string(&out, "")
        out.append(contentsOf: Array(#","b":"#.utf8))
        FileV2DescriptorBuilder.string(&out, reply.body)
        out.append(UInt8(ascii: "}"))
        guard out.count < maxBytes else { return nil }
        return String(decoding: out, as: UTF8.self)
    }
}
