import Foundation

/// W-CRASHCRUMBS (this task) — a tiny, crash-safe trail of recent log lines
/// plus a one-line call-context summary, both readable from a POSIX signal
/// handler without ever blocking.
///
/// iOS-shaped counterpart of Android's `CrashBreadcrumbs` mmap ring
/// (spec section C1): Android needs a shared-memory ring because a NATIVE
/// tombstone is generated by a DIFFERENT process (`tombstoned`) that can
/// read this one's memory but not call back into it. On iOS there is no
/// such handoff — `CrashReporter`'s own signal/`NSUncaughtExceptionHandler`
/// runs SYNCHRONOUSLY, in-process, before the process actually dies (see
/// that file's header) — so a plain in-memory ring read at THAT exact
/// moment is simpler and carries no shared-memory/layout-versioning
/// surface at all. The one thing this file adds beyond a plain array is
/// the safety property a crash handler actually needs: a read that can
/// never deadlock.
///
/// **Deadlock avoidance:** `add(_:_:_:)` runs on whatever thread is
/// logging, at any time, including the instant before a crash.
/// `snapshotForCrash()` runs INSIDE the crash handler, possibly on the
/// very thread that was in the middle of `add` when it crashed. `NSLock`
/// is not reentrant, so a plain `lock()` there could self-deadlock and
/// hang the process instead of letting it terminate — worse than no
/// breadcrumbs at all. `snapshotForCrash()` therefore uses `lock.try()`
/// and returns `[]` on contention rather than ever blocking.
///
/// **Two separate stores, two separate lifetimes:**
///  - The line ring (`add`/`snapshotForCrash`) is in-memory only. It helps
///    `CrashReporter`'s OWN synchronous handlers, in THIS process, and is
///    gone the instant the process is (whether or not a handler ran).
///  - The call-context summary (`setCallContext`/`lastCallContext`) is a
///    single short `UserDefaults` string, refreshed only at call-phase
///    boundaries (NOT per breadcrumb, so it stays cheap). It survives to
///    the NEXT launch, which is what lets `QAudionApp.init()` tell "the
///    previous process died while a native-SRTP call was up" apart from
///    every other reason a process can end — see
///    `CallCapabilities.registerNativeSrtpCrashAndMaybeAutoReset()`.
///
/// **Redaction:** callers pass already-safe text — every line reaching
/// `add(_:_:_:)` in production has ALREADY been through
/// `LogRedactor.scrubKeyMaterial` (the single choke point, see
/// `RuntimeLogSink.record`), and the crash report text this feeds into is
/// itself shipped through the same `print()` -> stdout-tee -> redact
/// pipe as everything else (`CrashReporter.flushPendingReport()`) — so
/// redaction is unconditional and applied twice, not something this file
/// has to re-implement. `setCallContext` additionally truncates any call
/// id to 8 characters itself, matching this codebase's identity-logging
/// convention (`CallService.short8`) — never a full id, key material, an
/// IP, an SDP fingerprint or ICE credentials.
public enum CrashBreadcrumbs {

    private static let lock = NSLock()
    private static var lines: [String] = []

    /// Ring capacity and per-line byte cap — same numbers as Android's
    /// `CrashBreadcrumbs` ring (spec section C1) purely so a maintainer
    /// reading both platforms' crash reports sees comparably-sized trails.
    static let capacity = 50
    static let maxLineBytes = 180

    /// Append one line. Called from exactly one place in production —
    /// `RuntimeLogSink.record(level:tag:message:)`, itself the single
    /// choke point every `RTLog.*` call AND every tee'd `print(...)` line
    /// (Engine code included) already passes through — so this file adds
    /// no new call sites to the (uncompilable-here) call/media hot paths.
    /// Cheap: one lock, one array append/trim, no I/O, no formatting
    /// beyond a couple of string concatenations.
    public static func add(_ level: String, _ tag: String, _ message: String) {
        var line = level + " " + tag + ": " + message
        if line.utf8.count > maxLineBytes {
            line = String(line.prefix(maxLineBytes))
        }
        lock.lock()
        lines.append(line)
        if lines.count > capacity {
            lines.removeFirst(lines.count - capacity)
        }
        lock.unlock()
    }

    /// Crash-safe snapshot, oldest first. See the type doc for why this
    /// uses `try()` instead of `lock()`. Returns `[]` — never blocks, never
    /// throws — on the rare contended case; a crash report with no
    /// breadcrumbs is a fine degrade, a hung crash handler is not.
    public static func snapshotForCrash() -> [String] {
        guard lock.try() else { return [] }
        defer { lock.unlock() }
        return lines
    }

    /// Test-only: empties the ring so tests don't see another test's lines.
    static func resetForTesting() {
        lock.lock()
        lines.removeAll()
        lock.unlock()
    }

    // MARK: - Persisted call-context (survives to the next launch)

    private static let callContextKey = "qaudion.crash.call_context"

    /// Overwrite the persisted call-context line. Called at each
    /// native-SRTP snapshot decision (`AppState.logNativeSrtpSnapshot`) and
    /// cleared by ``clearCallContext()`` at a clean `CallService.endCall()`
    /// — so if the NEXT launch still finds one, the process ended (crash or
    /// OS kill) WHILE that call was up. `callId` is truncated to 8
    /// characters here — never store a full id.
    public static func setCallContext(inCall: Bool, native: Bool, role: String?, callId: String?, phase: String) {
        var s = "in_call=" + (inCall ? "1" : "0")
        s += " native=" + (native ? "1" : "0")
        if let role = role, !role.isEmpty {
            s += " role=" + role
        }
        if let callId = callId, !callId.isEmpty {
            s += " call8=" + String(callId.prefix(8))
        }
        s += " phase=" + phase
        UserDefaults.standard.set(s, forKey: callContextKey)
    }

    /// Called once the call has ended cleanly — the ordinary case removes
    /// the "we might have died mid-call" signal so an UNRELATED later
    /// crash (on the home screen, in Settings, ...) is never misread as a
    /// native-SRTP call crash.
    public static func clearCallContext() {
        UserDefaults.standard.removeObject(forKey: callContextKey)
    }

    /// The last written (and not yet cleared) call-context line, or `nil`
    /// between calls / after a clean end. Read once, at launch, by
    /// `QAudionApp.init()` — plain `UserDefaults` read, safe from ordinary
    /// (non-signal-handler) code on any thread.
    public static func lastCallContext() -> String? {
        UserDefaults.standard.string(forKey: callContextKey)
    }
}
