import XCTest
@testable import QAudionEngine

/// Per-call DTLS context (WIRE_SPEC §3.8): the peer fingerprint pin and the buffering of work that
/// must not run before it (applying a remote SDP). The certificate itself is generated by the
/// WebRTC binary and is covered by the on-device checks; this suite uses fingerprint-only contexts.
final class CallDtlsContextTests: XCTestCase {

    private typealias F = V5TestFixtures

    private func makeContext(_ callId: String = F.callId) -> CallDtlsContext {
        #if canImport(WebRTC)
        return CallDtlsContext(callId: callId, certificate: nil, fingerprint: F.fingerprint("self"))
        #else
        return CallDtlsContext(callId: callId, fingerprint: F.fingerprint("self"))
        #endif
    }

    func testFirstPinThenSameThenConflict() {
        let ctx = makeContext()
        XCTAssertNil(ctx.peerFingerprint)
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        XCTAssertEqual(ctx.peerFingerprint, F.fingerprint("peer"))
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .unchanged)
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("intruder")), .conflict)
        // A conflict never overwrites the pin.
        XCTAssertEqual(ctx.peerFingerprint, F.fingerprint("peer"))
    }

    func testMalformedFingerprintIsNeverPinned() {
        let ctx = makeContext()
        XCTAssertEqual(ctx.pinPeer(Data(count: 5)), .conflict)
        XCTAssertEqual(ctx.pinPeer(Data([0x02]) + Data(repeating: 1, count: 32)), .conflict)
        XCTAssertNil(ctx.peerFingerprint)
    }

    /// The remote SDP waits for the pin: nothing runs before it, everything runs once after it, in
    /// registration order (the SRD / SLD buffering of the PeerConnection funnel).
    func testWaitersRunOnlyAfterThePinInOrder() {
        let ctx = makeContext()
        var order: [String] = []
        var seen: [Data] = []
        ctx.whenPeerPinned { fp in order.append("a"); seen.append(fp) }
        ctx.whenPeerPinned { fp in order.append("b"); seen.append(fp) }
        XCTAssertTrue(order.isEmpty, "no remote SDP may be applied before the fingerprint is pinned")
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        XCTAssertEqual(order, ["a", "b"])
        XCTAssertEqual(seen, [F.fingerprint("peer"), F.fingerprint("peer")])
        // Waiters are one-shot: a repeated pin does not run them again.
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .unchanged)
        XCTAssertEqual(order, ["a", "b"])
    }

    func testWaiterRegisteredAfterThePinRunsImmediately() {
        let ctx = makeContext()
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        var ran = false
        ctx.whenPeerPinned { _ in ran = true }
        XCTAssertTrue(ran)
    }

    /// A conflicting pin never releases the buffered SDP work.
    func testConflictDoesNotReleaseWaiters() {
        let ctx = makeContext()
        var ran = 0
        ctx.whenPeerPinned { _ in ran += 1 }
        XCTAssertEqual(ctx.pinPeer(Data(count: 3)), .conflict)
        XCTAssertEqual(ran, 0)
    }

    func testPinIsThreadSafeAndFiresWaitersOnce() {
        let ctx = makeContext()
        let lock = NSLock()
        var count = 0
        for _ in 0..<20 {
            ctx.whenPeerPinned { _ in lock.lock(); count += 1; lock.unlock() }
        }
        DispatchQueue.concurrentPerform(iterations: 16) { _ in
            _ = ctx.pinPeer(F.fingerprint("peer"))
        }
        lock.lock(); defer { lock.unlock() }
        XCTAssertEqual(count, 20)
    }

    /// The store keeps the call id exactly as first spelled (frame keys derive from the transcript
    /// string, which may be upper-case in a KAT), while the lookup ignores case. Needs a real
    /// certificate, so it only runs where the WebRTC binary is linked.
    func testStoreKeepsTheExactCallIdAndLooksUpCaseInsensitively() throws {
        let store = CallDtlsContextStore()
        guard let ctx = store.context(forCallId: "01HXTestCallID") else {
            throw XCTSkip("no certificate generator on this host")
        }
        XCTAssertEqual(ctx.callId, "01HXTestCallID")
        XCTAssertTrue(store.context(forCallId: "01hxtestcallid") === ctx)
        XCTAssertTrue(store.existing(forCallId: "01HXTESTCALLID") === ctx)
        XCTAssertTrue(DtlsFingerprint.isWellFormedBinary(ctx.fingerprint))
        // A second call gets another certificate (calls stay unlinkable).
        let other = try XCTUnwrap(store.context(forCallId: "another-call"))
        XCTAssertNotEqual(other.fingerprint, ctx.fingerprint)
    }

    // MARK: - Hash store (SAS binding)

    func testTranscriptHashStoreKeyedByLowercasedCallId() {
        let store = HandshakeTranscriptHashStore()
        let h = Data(repeating: 0x5A, count: 32)
        store.set(h, forCallId: "ABC-Def")
        XCTAssertEqual(store.hash(forCallId: "abc-def"), h)
        XCTAssertNil(store.hash(forCallId: "other"))
        // Wrong lengths are refused.
        store.set(Data(count: 31), forCallId: "bad")
        XCTAssertNil(store.hash(forCallId: "bad"))
        // A later round replaces the hash.
        let h2 = Data(repeating: 0x6B, count: 32)
        store.set(h2, forCallId: "abc-def")
        XCTAssertEqual(store.hash(forCallId: "ABC-DEF"), h2)
    }

    func testTranscriptHashStoreRetainsOnlyTheLastCalls() {
        let store = HandshakeTranscriptHashStore()
        for i in 0..<6 {
            store.set(Data(repeating: UInt8(i), count: 32), forCallId: "call-\(i)")
        }
        XCTAssertNil(store.hash(forCallId: "call-0"))
        XCTAssertNil(store.hash(forCallId: "call-1"))
        XCTAssertNotNil(store.hash(forCallId: "call-5"))
    }
}
