import XCTest
@testable import QAudionEngine

/// Per-call DTLS context (WIRE_SPEC §3.8): the peer fingerprint pin and the buffering of work that
/// must not run before it (applying a remote SDP). The certificate itself is generated by the
/// WebRTC binary and is covered by the on-device checks; this suite uses fingerprint-only contexts.
final class CallDtlsContextTests: XCTestCase {

    private typealias F = V6TestFixtures

    private func makeContext(_ callId: String = F.callId) -> CallDtlsContext {
        #if canImport(WebRTC)
        return CallDtlsContext(callId: callId, certificate: nil, fingerprint: F.fingerprint("self"))
        #else
        return CallDtlsContext(callId: callId, fingerprint: F.fingerprint("self"))
        #endif
    }

    func testFirstPinThenSameThenConflict() {
        let ctx = makeContext()
        XCTAssertNil(ctx.peerFingerprint)
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        XCTAssertEqual(ctx.peerFingerprint, F.fingerprint("peer"))
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .unchanged)
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("intruder")), .conflict)
        // A conflict never overwrites the pin.
        XCTAssertEqual(ctx.peerFingerprint, F.fingerprint("peer"))
    }

    func testMalformedFingerprintIsNeverPinned() {
        let ctx = makeContext()
        XCTAssertEqual(ctx.pinPeer(Data(count: 5)), .conflict)
        XCTAssertEqual(ctx.pinPeer(Data([0x02]) + Data(repeating: 1, count: 32)), .conflict)
        XCTAssertNil(ctx.peerFingerprint)
    }

    /// The remote SDP waits for the pin: nothing runs before it, everything runs once after it, in
    /// registration order (the SRD / SLD buffering of the PeerConnection funnel).
    func testWaitersRunOnlyAfterThePinInOrder() {
        let ctx = makeContext()
        var order: [String] = []
        var seen: [Data] = []
        ctx.whenPeerPinned { fp in order.append("a"); seen.append(fp) }
        ctx.whenPeerPinned { fp in order.append("b"); seen.append(fp) }
        XCTAssertTrue(order.isEmpty, "no remote SDP may be applied before the fingerprint is pinned")
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        XCTAssertEqual(order, ["a", "b"])
        XCTAssertEqual(seen, [F.fingerprint("peer"), F.fingerprint("peer")])
        // Waiters are one-shot: a repeated pin does not run them again.
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .unchanged)
        XCTAssertEqual(order, ["a", "b"])
    }

    func testWaiterRegisteredAfterThePinRunsImmediately() {
        let ctx = makeContext()
        XCTAssertEqual(ctx.pinPeer(F.fingerprint("peer")), .pinned)
        var ran = false
        ctx.whenPeerPinned { _ in ran = true }
        XCTAssertTrue(ran)
    }

    /// A conflicting pin never releases the buffered SDP work.
    func testConflictDoesNotReleaseWaiters() {
        let ctx = makeContext()
        var ran = 0
        ctx.whenPeerPinned { _ in ran += 1 }
        XCTAssertEqual(ctx.pinPeer(Data(count: 3)), .conflict)
        XCTAssertEqual(ran, 0)
    }

    func testPinIsThreadSafeAndFiresWaitersOnce() {
        let ctx = makeContext()
        let lock = NSLock()
        var count = 0
        for _ in 0..<20 {
            ctx.whenPeerPinned { _ in lock.lock(); count += 1; lock.unlock() }
        }
        DispatchQueue.concurrentPerform(iterations: 16) { _ in
            _ = ctx.pinPeer(F.fingerprint("peer"))
        }
        lock.lock(); defer { lock.unlock() }
        XCTAssertEqual(count, 20)
    }

    /// The store keeps the call id exactly as first spelled (frame keys derive from the transcript
    /// string, which may be upper-case in a KAT), while the lookup ignores case. Needs a real
    /// certificate, so it only runs where the WebRTC binary is linked.
    func testStoreKeepsTheExactCallIdAndLooksUpCaseInsensitively() throws {
        let store = CallDtlsContextStore()
        guard let ctx = store.context(forCallId: "01HXTestCallID") else {
            throw XCTSkip("no certificate generator on this host")
        }
        XCTAssertEqual(ctx.callId, "01HXTestCallID")
        XCTAssertTrue(store.context(forCallId: "01hxtestcallid") === ctx)
        XCTAssertTrue(store.existing(forCallId: "01HXTESTCALLID") === ctx)
        XCTAssertTrue(DtlsFingerprint.isWellFormedBinary(ctx.fingerprint))
        // A second call gets another certificate (calls stay unlinkable).
        let other = try XCTUnwrap(store.context(forCallId: "another-call"))
        XCTAssertNotEqual(other.fingerprint, ctx.fingerprint)
    }

    // MARK: - Store lifetime (R-CERT)

    /// A store whose certificates are fingerprint-only fakes, and a counter of how many
    /// certificates were generated per call id.
    private final class Counting: @unchecked Sendable {
        private let lock = NSLock()
        private var counts: [String: Int] = [:]
        func bump(_ id: String) -> Int {
            lock.lock(); defer { lock.unlock() }
            counts[id.lowercased(), default: 0] += 1
            return counts[id.lowercased()]!
        }
        func count(_ id: String) -> Int {
            lock.lock(); defer { lock.unlock() }
            return counts[id.lowercased(), default: 0]
        }
    }

    private func makeStore(_ counting: Counting) -> CallDtlsContextStore {
        CallDtlsContextStore(generator: { callId in
            let n = counting.bump(callId)
            #if canImport(WebRTC)
            return CallDtlsContext(callId: callId, certificate: nil, fingerprint: F.fingerprint("self-\(callId)-\(n)"))
            #else
            return CallDtlsContext(callId: callId, fingerprint: F.fingerprint("self-\(callId)-\(n)"))
            #endif
        })
    }

    /// The live call's context must survive any number of other calls' OFFERs (the registry used
    /// to keep the last 4 by insertion order, so a 5th OFFER evicted the live call and the next
    /// re-key signed a new certificate).
    func testLiveCallContextSurvivesMoreThanFourOtherOffers() throws {
        let counting = Counting()
        let store = makeStore(counting)
        let fp = try XCTUnwrap(store.fingerprint(forCallId: "live-call"))
        let ctx = try XCTUnwrap(store.existing(forCallId: "live-call"))
        for i in 0..<12 {
            XCTAssertNotNil(store.context(forCallId: "other-\(i)"))
            // Other calls' OFFERs may also be answered with a fingerprint read (a ringing call).
            if i % 3 == 0 { _ = store.fingerprint(forCallId: "other-\(i)") }
        }
        XCTAssertTrue(store.existing(forCallId: "live-call") === ctx, "the live call's context was evicted")
        XCTAssertEqual(store.fingerprint(forCallId: "LIVE-CALL"), fp, "a re-key must sign the same certificate")
        XCTAssertEqual(counting.count("live-call"), 1, "a second certificate was generated for the live call")
    }

    /// A PeerConnection-bound (held) context is protected too, even before anything is signed.
    func testHeldContextSurvivesOtherOffers() throws {
        let counting = Counting()
        let store = makeStore(counting)
        let ctx = try XCTUnwrap(store.context(forCallId: "ringing"))
        store.hold(callId: "Ringing")
        for i in 0..<6 { _ = store.context(forCallId: "noise-\(i)") }
        XCTAssertTrue(store.existing(forCallId: "ringing") === ctx)
    }

    /// A context created with `hold: true` is live from its very first instant: the other calls'
    /// OFFERs that arrive right after cannot evict it (no lookup-then-hold window), and a
    /// fingerprint read afterwards still returns the certificate the PeerConnection was given.
    func testContextCreatedHeldIsNeverEvictedAndKeepsItsCertificate() throws {
        let counting = Counting()
        let store = makeStore(counting)
        let ctx = try XCTUnwrap(store.context(forCallId: "Bound", hold: true))
        for i in 0..<(CallDtlsContextStore.retained * 3) { _ = store.context(forCallId: "noise-\(i)") }
        XCTAssertTrue(store.existing(forCallId: "bound") === ctx)
        XCTAssertEqual(store.fingerprint(forCallId: "bound"), ctx.fingerprint)
        XCTAssertEqual(counting.count("bound"), 1)
    }

    /// A call whose certificate is first read for signing is signed and live in the same step: the
    /// fingerprint returned is that of the context the store keeps, even under a burst of OFFERs.
    func testFingerprintReadIsAtomicWithTheInsert() throws {
        let counting = Counting()
        let store = makeStore(counting)
        let fp = try XCTUnwrap(store.fingerprint(forCallId: "first-sign"))
        for i in 0..<(CallDtlsContextStore.retained * 3) { _ = store.context(forCallId: "burst-\(i)") }
        XCTAssertEqual(store.existing(forCallId: "first-sign")?.fingerprint, fp)
        XCTAssertEqual(store.fingerprint(forCallId: "first-sign"), fp)
        XCTAssertEqual(counting.count("first-sign"), 1)
    }

    /// Contexts that are neither held nor signed (an OFFER merely ringing) are still bounded.
    func testUnheldContextsAreStillEvictedInInsertionOrder() {
        let store = makeStore(Counting())
        for i in 0..<(CallDtlsContextStore.retained + 3) { _ = store.context(forCallId: "ring-\(i)") }
        XCTAssertNil(store.existing(forCallId: "ring-0"))
        XCTAssertNotNil(store.existing(forCallId: "ring-\(CallDtlsContextStore.retained + 2)"))
    }

    /// Once a call id has signed, it never gets a second certificate: after the call ended (or the
    /// context was dropped) the id is retired and the store refuses to generate again.
    func testSignedCallIdIsNeverRegenerated() throws {
        let counting = Counting()
        let store = makeStore(counting)
        _ = try XCTUnwrap(store.fingerprint(forCallId: "signed-call"))
        store.release(callId: "signed-call")
        XCTAssertNil(store.existing(forCallId: "signed-call"))
        XCTAssertNil(store.context(forCallId: "signed-call"))
        XCTAssertNil(store.fingerprint(forCallId: "SIGNED-CALL"))
        XCTAssertEqual(counting.count("signed-call"), 1)
    }

    /// An id that never signed is not retired by a release (a declined ring-time context).
    func testReleaseOfAnUnsignedCallDoesNotRetireIt() throws {
        let store = makeStore(Counting())
        _ = try XCTUnwrap(store.context(forCallId: "declined"))
        store.release(callId: "declined")
        XCTAssertNotNil(store.context(forCallId: "declined"))
    }

    /// The live cap drops held-but-unsigned contexts before any signed (live call) context.
    func testLiveCapNeverDropsASignedCallBeforeAnUnsignedHold() throws {
        let counting = Counting()
        let store = makeStore(counting)
        _ = try XCTUnwrap(store.fingerprint(forCallId: "the-call"))
        for i in 0..<(CallDtlsContextStore.liveCap * 2) {
            _ = store.context(forCallId: "held-\(i)")
            store.hold(callId: "held-\(i)")
        }
        XCTAssertNotNil(store.existing(forCallId: "the-call"))
        XCTAssertEqual(counting.count("the-call"), 1)
    }

    func testStoreIsThreadSafe() {
        let store = makeStore(Counting())
        DispatchQueue.concurrentPerform(iterations: 64) { i in
            _ = store.fingerprint(forCallId: "c-\(i % 5)")
            store.hold(callId: "c-\(i % 7)")
            if i % 11 == 0 { store.release(callId: "c-\(i % 5)") }
        }
    }

    // MARK: - Hash store (SAS binding)

    func testTranscriptHashStoreKeyedByLowercasedCallId() {
        let store = HandshakeTranscriptHashStore()
        let h = Data(repeating: 0x5A, count: 32)
        store.set(h, forCallId: "ABC-Def")
        XCTAssertEqual(store.hash(forCallId: "abc-def"), h)
        XCTAssertNil(store.hash(forCallId: "other"))
        // Wrong lengths are refused.
        store.set(Data(count: 31), forCallId: "bad")
        XCTAssertNil(store.hash(forCallId: "bad"))
        // A later round replaces the hash.
        let h2 = Data(repeating: 0x6B, count: 32)
        store.set(h2, forCallId: "abc-def")
        XCTAssertEqual(store.hash(forCallId: "ABC-DEF"), h2)
    }

    func testTranscriptHashStoreRetainsOnlyTheLastCalls() {
        let store = HandshakeTranscriptHashStore()
        for i in 0..<6 {
            store.set(Data(repeating: UInt8(i), count: 32), forCallId: "call-\(i)")
        }
        XCTAssertNil(store.hash(forCallId: "call-0"))
        XCTAssertNil(store.hash(forCallId: "call-1"))
        XCTAssertNotNil(store.hash(forCallId: "call-5"))
    }
}
