/* qaudion-crypto-core — v4 PQ ratchet C ABI (P1.6).
 * GENERATED by cbindgen from src/ffi.rs — DO NOT EDIT BY HAND.
 * See README.md "FFI / per-platform bindings" for JNI / Swift / N-API integration steps. */

#ifndef QAUDION_CRYPTO_CORE_H
#define QAUDION_CRYPTO_CORE_H

/* This file is auto-generated. Regenerate with `cargo build`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * GCM authentication tag length in bytes.
 */
#define TAG_LEN 16

/**
 * GCM nonce length in bytes (96-bit, the recommended/required size for AES-GCM).
 */
#define NONCE_LEN 12

/**
 * ML-KEM-768 public-key length in bytes (FIPS-203).
 */
#define MLKEM768_PK_LEN 1184

/**
 * ML-KEM-768 secret-key length in bytes (FIPS-203).
 */
#define MLKEM768_SK_LEN 2400

/**
 * ML-KEM-768 ciphertext length in bytes (FIPS-203).
 */
#define MLKEM768_CT_LEN 1088

/**
 * Shared-secret / X25519 element length in bytes.
 */
#define SS_LEN 32

/**
 * ML-KEM `generate_key_pair` seed length (`d ‖ z`, 32 + 32).
 */
#define MLKEM768_KEYGEN_SEED_LEN 64

/**
 * ML-KEM `encapsulate` randomness length (`m`).
 */
#define MLKEM768_ENCAPS_SEED_LEN 32

/**
 * Max message keys we will skip (store) in a single chain before refusing — bounds memory
 * and limits the blast radius of a malicious "jump the counter to 2^32" frame.
 */
#define MAX_SKIP 1024

/**
 * Direction byte fed into `ratchet_step`'s info string (the frozen cross-platform contract).
 * `0x00` = the epoch initiator's send direction, `0x01` = the responder's. Each side uses the
 * peer's `dir` to derive the *matching* chain (their send == our recv).
 */
#define DIR_A 0

#define DIR_B 1

/**
 * GF(2^8) primitive polynomial (x^8 + x^4 + x^3 + x^2 + 1).
 */
#define RS_POLY 285

/**
 * GF(2^8) generator / primitive element.
 */
#define RS_ALPHA 2

/**
 * Number of systematic data shards required to reconstruct (`k`).
 */
#define RS_K 12

/**
 * Total number of shards emitted (`n`); `n - k` = parity shards.
 */
#define RS_N 18

/**
 * Bytes of source data carried per shard.
 */
#define SHARD_DATA 103

/**
 * The object is right-zero-padded to this length before encoding (`k * SHARD_DATA`).
 */
#define PADDED_LEN (RS_K * SHARD_DATA)

/**
 * v4 frame magic (dual-stack with 0xE3 legacy on the receive side).
 */
#define MAGIC_V4 229

/**
 * v4 version byte.
 */
#define VERSION_V4 4

#define FRAME_TYPE_DATA 0

#define FRAME_TYPE_RATCHET_INIT 1

/**
 * One Reed-Solomon shard of a chunked ML-KEM/X-Wing object (P1.5b).
 */
#define FRAME_TYPE_KEM_CHUNK 2

/**
 * flags bit0: the ML-KEM ciphertext is Reed-Solomon chunked across frames.
 * On a Data/RatchetInit frame this bit is invalid (those carry inline ct); a `KEM_CHUNK` frame
 * always sets it. See [`parse_shard`] / [`reassemble`].
 */
#define FLAG_MLKEM_CT_CHUNKED 1

/**
 * Size of a `KEM_CHUNK` shard-frame header (magic..object_len inclusive).
 */
#define SHARD_HEADER_LEN 30

/**
 * Length of the `call_id` field carried in a shard frame.
 */
#define CALL_ID_LEN 16

/**
 * Total serialized length of one shard frame: header + `SHARD_DATA` payload.
 */
#define SHARD_FRAME_LEN (SHARD_HEADER_LEN + SHARD_DATA)

/**
 * FFI status codes. `QA_OK == 0`; all errors are non-zero. Stable — never renumber.
 */
enum QaStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    /**
     * Success.
     */
    QA_STATUS_OK = 0,
    /**
     * A required pointer argument was NULL.
     */
    QA_STATUS_NULL_ARG = -1,
    /**
     * The provided output buffer was too small; `*out_len` was set to the required size.
     */
    QA_STATUS_BUFFER_TOO_SMALL = -2,
    /**
     * AEAD authentication failed (wrong key / tampered / forged) — fail-closed, no detail.
     */
    QA_STATUS_AUTH_FAILED = -3,
    /**
     * The frame is a replay (its (epoch, counter) was already consumed).
     */
    QA_STATUS_REPLAY = -4,
    /**
     * Decrypt would require skipping more than the per-epoch bound — refused (DoS guard).
     */
    QA_STATUS_TOO_MANY_SKIPPED = -5,
    /**
     * The frame references an epoch the session has not ratcheted into yet.
     */
    QA_STATUS_UNKNOWN_EPOCH = -6,
    /**
     * A serialized buffer (state or wire frame) was malformed / truncated.
     */
    QA_STATUS_PARSE_ERROR = -7,
};
#ifndef __cplusplus
typedef int32_t QaStatus;
#endif // __cplusplus

/**
 * Opaque session handle. The C side only ever holds a `*mut QaSession`.
 */
typedef struct QaSession QaSession;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize a session from the handshake shared secret and the first epoch's X-Wing secret.
 *
 * `root_0`, `first_ss_xwing`, `transcript_hash` are each exactly 32 bytes (the caller passes
 * `*const [u8;32]`). `is_a != 0` selects the "A" direction (its send chain == B's recv chain).
 * `root_0` should already be the post-handshake `ROOT_0` (see `qa_root_0` below to derive it).
 * On success writes the new handle to `*out_session` and returns [`QaStatus::Ok`].
 *
 * # Safety
 * All pointers must be valid for the stated sizes; `out_session` must be a valid `*mut *mut`.
 */
QaStatus qa_session_init(const uint8_t *root_0,
                         const uint8_t *first_ss_xwing,
                         const uint8_t *transcript_hash,
                         int32_t is_a,
                         QaSession **out_session);

/**
 * Derive `ROOT_0 = HKDF-SHA384(salt=∅, ikm=SS_handshake, info="qa/v4/root-init", L=32)` from a
 * 32-byte handshake shared secret. Convenience so callers can feed `qa_session_init` directly.
 *
 * # Safety
 * `ss_handshake` must point to 32 readable bytes; `out_root0` to 32 writable bytes.
 */
QaStatus qa_root_0(const uint8_t *ss_handshake, uint8_t *out_root0);

/**
 * Encrypt `plaintext` on the session's send chain and serialize the result as a v4 **Data**
 * wire frame into `(out, *out_len)` (query-then-fill). Advances the send chain in place — per
 * the write-ahead contract the caller MUST persist the session (via [`qa_session_serialize`])
 * BEFORE transmitting the returned frame bytes.
 *
 * # Safety
 * `session` must be a live handle; `plaintext` valid for `plaintext_len`; `out_len` valid.
 */
QaStatus qa_ratchet_encrypt(QaSession *session,
                            const uint8_t *plaintext,
                            uintptr_t plaintext_len,
                            uint8_t *out,
                            uintptr_t *out_len);

/**
 * Parse a v4 **Data** wire frame and decrypt it on the session's receive chain, writing the
 * recovered plaintext into `(out, *out_len)` (query-then-fill). Handles in-order, out-of-order
 * (skipped-key cache), and replay-reject. Fail-closed: any auth/replay/parse failure returns the
 * corresponding error and mutates no security state.
 *
 * NOTE: this is the Data-frame path. RatchetInit / KEM_CHUNK epoch transitions are driven by the
 * higher layer (it derives the new epoch's X-Wing secret from the wire KEM material and calls
 * `qa_dh_ratchet`); exposing that is the next FFI increment.
 *
 * # Safety
 * `session` live; `frame` valid for `frame_len`; `out_len` valid.
 */
QaStatus qa_ratchet_decrypt(QaSession *session,
                            const uint8_t *frame,
                            uintptr_t frame_len,
                            uint8_t *out,
                            uintptr_t *out_len);

/**
 * Advance the session into the next epoch using a fresh 32-byte X-Wing secret and a 32-byte
 * transcript hash (both peers call this with identical inputs at the epoch boundary). The
 * higher layer obtains `ss_xwing` by reassembling + decapsulating the wire KEM material.
 *
 * # Safety
 * `session` live; `ss_xwing`/`transcript_hash` each 32 readable bytes.
 */
QaStatus qa_dh_ratchet(QaSession *session, const uint8_t *ss_xwing, const uint8_t *transcript_hash);

/**
 * Serialize the full session state into the durable vault format (query-then-fill). Used for the
 * write-ahead persist-before-transmit invariant and crash-resume.
 *
 * # Safety
 * `session` live; `out_len` valid.
 */
QaStatus qa_session_serialize(const QaSession *session, uint8_t *out, uintptr_t *out_len);

/**
 * Parse a [`qa_session_serialize`] buffer back into a NEW session handle (e.g. on app restart).
 * Fail-closed: a malformed buffer returns [`QaStatus::ParseError`] and writes no handle.
 *
 * # Safety
 * `data` valid for `data_len`; `out_session` a valid `*mut *mut`.
 */
QaStatus qa_session_deserialize(const uint8_t *data, uintptr_t data_len, QaSession **out_session);

/**
 * Release a session handle. Safe to call with NULL (no-op). After this the handle is dangling and
 * MUST NOT be used again. Each handle must be freed exactly once.
 *
 * # Safety
 * `session` must be a handle returned by `qa_session_init`/`qa_session_deserialize` and not yet
 * freed, or NULL.
 */
void qa_session_free(QaSession *session);

/**
 * Return the crate's ABI/semver version as a 32-bit packed integer `(major<<16)|(minor<<8)|patch`
 * so a host can assert it linked the expected core. 0.1.0 -> 0x0000_0100.
 */
uint32_t qa_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* QAUDION_CRYPTO_CORE_H */
