import XCTest
import CryptoKit
@testable import QAudionEngine

// swiftlint:disable identifier_name

/// Runs EVERY vector of `file-v2-kat.json` (WIRE_SPEC section 12.13) against the Swift file v2 library: the
/// derivations, Padme, the complete files (header, per-chunk nonce, AAD, tag, ciphertext hash, blob hash), the
/// maximum chunk index, every negative blob and negative chunk with its expected error code, and every
/// descriptor. The vector file is generated by the server repository's `tools/katgen/filev2`, an independent
/// Go implementation; the three client libraries are proven compatible by this one file. Its SHA-256 is
/// pinned below, so the copy in this repository can never drift from the server's.
///
/// Nothing in this class skips: a missing or changed vector file fails.
final class FileV2KatTests: XCTestCase {

    private typealias Support = FileV2TestSupport

    // MARK: The file itself

    func testKatFileIsAByteIdenticalCopyOfTheServerFile() throws {
        let bytes = try Support.katBytes()
        XCTAssertEqual(bytes.count, Support.pinnedKatLength, "length of file-v2-kat.json changed")
        XCTAssertEqual(Support.sha256Hex(bytes), Support.pinnedKatSHA256,
                       "file-v2-kat.json is not the pinned byte-for-byte copy of the server file")
        XCTAssertFalse(bytes.contains(0x0D), "a CR in the vector file: line endings were rewritten (.gitattributes -text)")
    }

    /// The counts are asserted so a vector can never be dropped or filtered out without a failure here.
    func testKatCoversEverythingTheTestsExercise() throws {
        let kat = try Support.loadKat()
        XCTAssertEqual(kat.format, "qaudion-file-v2-kat")
        XCTAssertEqual(kat.version, 1)
        XCTAssertEqual(kat.derivations.count, 8)
        XCTAssertEqual(kat.padme.count, 17)
        XCTAssertEqual(kat.files.map(\.name),
                       ["f_1", "f_1023", "f_1048575", "f_1048576", "f_1048577", "f_3145733", "f_1023_b", "f_3145733_b"])
        XCTAssertEqual(kat.max_index.count, 2)
        XCTAssertEqual(kat.negative_blobs.count, 18)
        XCTAssertEqual(kat.negative_chunks.count, 2)
        XCTAssertEqual(kat.descriptors.count, 15)
        XCTAssertEqual(kat.descriptors.filter { $0.expect == "ok" }.count, 3)
        XCTAssertEqual(kat.error_codes, ["bad_descriptor", "bad_header", "commit_mismatch", "header_mismatch",
                                         "chunk_auth", "bad_padding", "size_mismatch", "cancelled"])
        XCTAssertEqual(kat.receive_order.count, 8)

        // Every error code of section 12.9 that a receiver can produce from bytes has at least one vector
        // (`cancelled` is the sender's own message, not a receive-side outcome).
        let expected = Set(kat.negative_blobs.map(\.expect) + kat.negative_chunks.map(\.expect)
                           + kat.descriptors.map(\.expect))
        for code in kat.error_codes where code != "cancelled" {
            XCTAssertTrue(expected.contains(code), "no negative vector for \(code)")
        }
        XCTAssertTrue(expected.contains("discard"))
        XCTAssertTrue(expected.contains("ok"))
        // Nothing unknown in `expect`.
        for code in expected {
            XCTAssertTrue(kat.error_codes.contains(code) || code == "ok" || code == "discard", "unknown expect \(code)")
        }
    }

    // MARK: Constants, derivations, Padme

    func testConstantsMatchTheKatAndTheSpec() throws {
        let kat = try Support.loadKat()
        XCTAssertEqual(kat.constants["CHUNK"], .number(UInt64(FileV2.chunkSize)))
        XCTAssertEqual(kat.constants["TAG"], .number(UInt64(FileV2.tagSize)))
        XCTAssertEqual(kat.constants["STRIDE"], .number(UInt64(FileV2.stride)))
        XCTAssertEqual(kat.constants["HEADER_LEN"], .number(UInt64(FileV2.headerLength)))
        XCTAssertEqual(kat.constants["MAX_SIZE"], .number(FileV2.maxSize))
        XCTAssertEqual(kat.constants["MAX_STREAM"], .number(FileV2.maxStream))
        XCTAssertEqual(kat.constants["MAX_CHUNKS"], .number(UInt64(FileV2.maxChunks)))
        XCTAssertEqual(kat.constants["MAX_BLOB"], .number(FileV2.maxBlob))
        XCTAssertEqual(kat.constants["MAGIC"], .text(Support.hexString(Data(FileV2.magic))))
        XCTAssertEqual(kat.constants["AAD_LABEL"], .text(String(decoding: FileV2Crypto.aadLabel, as: UTF8.self)))
        XCTAssertEqual(kat.constants["HKDF_INFO_ENC"], .text(String(decoding: FileV2Crypto.infoEncryption, as: UTF8.self)))
        XCTAssertEqual(kat.constants["HKDF_INFO_NONCE"], .text(String(decoding: FileV2Crypto.infoNonce, as: UTF8.self)))
        XCTAssertEqual(kat.constants["HKDF_INFO_COMMIT"],
                       .text(String(decoding: FileV2Crypto.infoCommitment, as: UTF8.self)))
        XCTAssertEqual(FileV2.chunkSize, 1_048_576)
        XCTAssertEqual(FileV2.stride, 1_048_592)
        XCTAssertEqual(FileV2.maxSize, 5_368_709_120)
        XCTAssertEqual(FileV2.maxBlob, 5_368_791_104)
        XCTAssertEqual(kat.constants.count, 13, "a constant was added to the KAT: assert it too")
    }

    func testEveryDerivationVector() throws {
        let kat = try Support.loadKat()
        XCTAssertFalse(kat.derivations.isEmpty)
        for vector in kat.derivations {
            let keys = FileV2Crypto.derive(fileKey: Support.hex(vector.k), fileID: Support.hex(vector.file_id))
            XCTAssertEqual(Support.hexString(keys.prk), vector.prk, "\(vector.name) prk")
            XCTAssertEqual(Support.hexString(keys.encryptionKey.withUnsafeBytes { Data($0) }), vector.k_enc,
                           "\(vector.name) k_enc")
            XCTAssertEqual(Support.hexString(keys.noncePrefix), vector.nonce_prefix, "\(vector.name) nonce_prefix")
            XCTAssertEqual(Support.hexString(keys.commitment), vector.commitment, "\(vector.name) commitment")
        }
    }

    func testEveryPadmeVector() throws {
        let kat = try Support.loadKat()
        XCTAssertFalse(kat.padme.isEmpty)
        for vector in kat.padme {
            XCTAssertEqual(FileV2.padme(vector.len), vector.padded, "padme(\(vector.len))")
        }
        XCTAssertEqual(FileV2.padme(FileV2.maxSize), FileV2.maxStream)
    }

    // MARK: Complete files

    func testEveryPositiveFileVector() throws {
        let kat = try Support.loadKat()
        let directory = try Support.makeTempDirectory(for: self)
        XCTAssertFalse(kat.files.isEmpty)
        for vector in kat.files {
            let label = vector.name
            let fileKey = Support.hex(vector.k)
            let fileID = Support.hex(vector.file_id)
            let encryptor = try FileV2Encryptor(fileKey: fileKey, fileID: fileID, plaintextSize: vector.size)

            // Geometry and header.
            XCTAssertEqual(Support.hexString(encryptor.header.bytes), vector.header, "\(label) header")
            XCTAssertEqual(encryptor.streamLength, vector.stream_len, "\(label) stream_len")
            XCTAssertEqual(encryptor.totalChunks, vector.total_chunks, "\(label) total_chunks")
            XCTAssertEqual(encryptor.blobLength, vector.blob_len, "\(label) blob_len")
            XCTAssertEqual(vector.chunks.count, encryptor.totalChunks, "\(label) chunk list")

            // The KAT plaintext rule is the one this test writes.
            let plainURL = directory.appendingPathComponent("\(label).plain")
            try Support.writePlaintextFile(size: vector.size, to: plainURL)
            XCTAssertEqual(try Support.sha256Hex(ofFile: plainURL), vector.plaintext_sha256, "\(label) plaintext")

            // Encrypt file to file, then check the blob byte for byte against the vector.
            let blobURL = directory.appendingPathComponent("\(label).blob")
            try encryptor.encryptFile(from: plainURL, to: blobURL)
            let blob = try Data(contentsOf: blobURL)
            XCTAssertEqual(UInt64(blob.count), vector.blob_len, "\(label) blob length")
            XCTAssertEqual(Support.sha256Hex(blob), vector.blob_sha256, "\(label) blob sha256")
            if let inline = vector.blob_hex {
                XCTAssertEqual(blob, Support.hex(inline), "\(label) blob bytes")
            }
            XCTAssertEqual(Data(blob.prefix(FileV2.headerLength)), encryptor.header.bytes, "\(label) blob header")

            // Per chunk: nonce, AAD, tag, ciphertext hash, final flag.
            let keys = FileV2Crypto.derive(fileKey: fileKey, fileID: fileID)
            for chunk in vector.chunks {
                let index = chunk.index
                let chunkLabel = "\(label) chunk \(index)"
                let isLast = index == vector.total_chunks - 1
                XCTAssertEqual(chunk.final, isLast ? 1 : 0, "\(chunkLabel) final flag")
                XCTAssertEqual(UInt64(encryptor.chunkStreamLength(index)), chunk.plain_len, "\(chunkLabel) plain_len")
                XCTAssertEqual(Support.hexString(FileV2Crypto.chunkNonce(prefix: keys.noncePrefix,
                                                                         index: UInt32(index))),
                               chunk.nonce, "\(chunkLabel) nonce")
                XCTAssertEqual(Support.hexString(FileV2Crypto.chunkAAD(header: encryptor.header.bytes,
                                                                       index: UInt32(index), final: isLast)),
                               chunk.aad, "\(chunkLabel) aad")
                let offset = Int(encryptor.blobOffset(ofChunk: index))
                let sealed = blob.subdata(in: offset..<offset + encryptor.sealedChunkLength(index))
                XCTAssertEqual(Support.hexString(sealed.suffix(FileV2.tagSize)), chunk.tag, "\(chunkLabel) tag")
                XCTAssertEqual(Support.sha256Hex(sealed.prefix(sealed.count - FileV2.tagSize)), chunk.ct_sha256,
                               "\(chunkLabel) ciphertext sha256")

                // The per-chunk sealing used by retries gives the same bytes as the file path, deterministically.
                let content = Support.plaintextBlock(offset: UInt64(index) * UInt64(FileV2.chunkSize),
                                                     count: encryptor.chunkFileLength(index))
                XCTAssertEqual(try encryptor.sealChunk(index: index, fileBytes: content), sealed,
                               "\(chunkLabel) re-seal differs")
            }

            // Receive it back: the plaintext is the vector's plaintext, to the byte.
            let receiver = try FileV2Decryptor(fileID: fileID, fileKey: fileKey, header: Support.hex(vector.header),
                                               size: vector.size)
            let outputURL = directory.appendingPathComponent("\(label).out")
            try receiver.decryptFile(from: blobURL, to: outputURL)
            XCTAssertEqual(try Support.sha256Hex(ofFile: outputURL), vector.plaintext_sha256, "\(label) decrypted")
            XCTAssertEqual(try FileManager.default.attributesOfItem(atPath: outputURL.path)[.size] as? UInt64,
                           vector.size, "\(label) decrypted size")
        }
    }

    func testMaximumChunkIndexVectors() throws {
        let kat = try Support.loadKat()
        XCTAssertFalse(kat.max_index.isEmpty)
        for vector in kat.max_index {
            let fileKey = Support.hex(vector.k)
            let fileID = Support.hex(vector.file_id)
            XCTAssertEqual(vector.size, FileV2.maxSize)
            XCTAssertEqual(vector.stream_len, FileV2.maxStream)
            XCTAssertEqual(vector.total_chunks, FileV2.maxChunks)
            let keys = FileV2Crypto.derive(fileKey: fileKey, fileID: fileID)
            let header = FileV2Header(fileID: fileID, streamLength: FileV2.padme(vector.size),
                                      totalChunks: vector.total_chunks, commitment: keys.commitment)
            XCTAssertEqual(Support.hexString(header.bytes), vector.header, "\(vector.name) header")
            XCTAssertEqual(Support.hexString(FileV2Crypto.chunkNonce(prefix: keys.noncePrefix,
                                                                     index: UInt32(vector.index))),
                           vector.nonce, "\(vector.name) nonce")
            let isLast = vector.index == vector.total_chunks - 1
            XCTAssertEqual(vector.final, isLast ? 1 : 0)
            XCTAssertEqual(Support.hexString(FileV2Crypto.chunkAAD(header: header.bytes, index: UInt32(vector.index),
                                                                   final: isLast)),
                           vector.aad, "\(vector.name) aad")
            // The same geometry through the public sender, which never reads a byte of a 5 GiB file here.
            let encryptor = try FileV2Encryptor(fileKey: fileKey, fileID: fileID, plaintextSize: vector.size)
            XCTAssertEqual(encryptor.header.bytes, header.bytes)
            XCTAssertEqual(encryptor.blobLength, FileV2.maxBlob)
        }
    }

    // MARK: Negative vectors

    /// The positive vectors the recipes are built on, rebuilt with this library and checked against the KAT.
    private func recipeBases(_ kat: FileV2Kat, in directory: URL) throws -> [String: (vector: FileV2Kat.FileVector, blob: Data)] {
        var bases: [String: (vector: FileV2Kat.FileVector, blob: Data)] = [:]
        for name in Set(kat.negative_blobs.compactMap(\.base) + kat.negative_blobs.compactMap { $0.op?.from }) {
            guard let vector = kat.files.first(where: { $0.name == name }) else {
                XCTFail("recipe base \(name) is not a file vector")
                continue
            }
            let encryptor = try FileV2Encryptor(fileKey: Support.hex(vector.k), fileID: Support.hex(vector.file_id),
                                                plaintextSize: vector.size)
            let plainURL = directory.appendingPathComponent("base-\(name).plain")
            let blobURL = directory.appendingPathComponent("base-\(name).blob")
            try Support.writePlaintextFile(size: vector.size, to: plainURL)
            try encryptor.encryptFile(from: plainURL, to: blobURL)
            let blob = try Data(contentsOf: blobURL)
            XCTAssertEqual(Support.sha256Hex(blob), vector.blob_sha256, "recipe base \(name) does not match its vector")
            bases[name] = (vector, blob)
        }
        return bases
    }

    /// Applies the recipe of a multi-chunk negative vector to its base blob (chunk `i` sits at `64 + i x STRIDE`).
    private func applyRecipe(_ operation: FileV2Kat.Operation, baseName: String,
                             bases: [String: (vector: FileV2Kat.FileVector, blob: Data)]) throws -> Data? {
        guard let base = bases[baseName] else {
            XCTFail("no base \(baseName)")
            return nil
        }
        func split(_ entry: (vector: FileV2Kat.FileVector, blob: Data)) -> (header: Data, chunks: [Data]) {
            var chunks: [Data] = []
            var offset = FileV2.headerLength
            for chunk in entry.vector.chunks {
                let length = Int(chunk.plain_len) + FileV2.tagSize
                chunks.append(entry.blob.subdata(in: offset..<offset + length))
                offset += length
            }
            XCTAssertEqual(UInt64(offset), entry.vector.blob_len)
            return (Data(entry.blob.prefix(FileV2.headerLength)), chunks)
        }
        let parts = split(base)
        var chunks = parts.chunks
        switch operation.op {
        case "swap_chunks":
            guard let i = operation.i, let j = operation.j else { XCTFail("swap_chunks needs i and j"); return nil }
            chunks.swapAt(i, j)
        case "drop_last_chunk":
            chunks.removeLast()
        case "duplicate_chunk":   // chunk j becomes a copy of chunk i
            guard let i = operation.i, let j = operation.j else { XCTFail("duplicate_chunk needs i and j"); return nil }
            chunks[j] = chunks[i]
        case "splice_chunk":      // chunk i is replaced by chunk i of the other file
            guard let i = operation.i, let from = operation.from, let other = bases[from] else {
                XCTFail("splice_chunk needs i and a known from")
                return nil
            }
            chunks[i] = split(other).chunks[i]
        case "reencrypt_chunk_final":   // chunk i encrypted again with another final flag
            guard let i = operation.i, let flag = operation.final else {
                XCTFail("reencrypt_chunk_final needs i and final")
                return nil
            }
            let vector = base.vector
            let keys = FileV2Crypto.derive(fileKey: Support.hex(vector.k), fileID: Support.hex(vector.file_id))
            let length = Int(vector.chunks[i].plain_len)
            let start = UInt64(i) * UInt64(FileV2.chunkSize)
            var plain = Support.plaintextBlock(offset: start, count: length)
            // The stream is the file followed by zero padding.
            if start + UInt64(length) > vector.size {
                let real = start >= vector.size ? 0 : Int(vector.size - start)
                plain = plain.prefix(real) + Data(count: length - real)
            }
            chunks[i] = try FileV2Crypto.seal(
                plaintext: plain, key: keys.encryptionKey,
                nonce: FileV2Crypto.chunkNonce(prefix: keys.noncePrefix, index: UInt32(i)),
                aad: FileV2Crypto.chunkAAD(header: parts.header, index: UInt32(i), final: flag == 1))
        default:
            XCTFail("unknown recipe op \(operation.op)")
            return nil
        }
        return chunks.reduce(parts.header) { $0 + $1 }
    }

    func testEveryNegativeBlobVector() throws {
        let kat = try Support.loadKat()
        let directory = try Support.makeTempDirectory(for: self)
        let bases = try recipeBases(kat, in: directory)
        XCTAssertFalse(kat.negative_blobs.isEmpty)
        var exercised = 0
        var recipes = 0
        for vector in kat.negative_blobs {
            // The blob: embedded for the small ones, a recipe on a positive vector for the others.
            let blob: Data
            if let inline = vector.blob_hex {
                blob = Support.hex(inline)
            } else {
                guard let baseName = vector.base, let operation = vector.op,
                      let built = try applyRecipe(operation, baseName: baseName, bases: bases) else {
                    XCTFail("\(vector.name): neither a blob nor a usable recipe")
                    continue
                }
                blob = built
                recipes += 1
            }
            XCTAssertEqual(blob.count, vector.blob_len, "\(vector.name) blob length")
            XCTAssertEqual(Support.sha256Hex(blob), vector.blob_sha256, "\(vector.name) blob sha256")

            let blobURL = directory.appendingPathComponent("\(vector.name).blob")
            let outputURL = directory.appendingPathComponent("\(vector.name).out")
            try blob.write(to: blobURL)
            do {
                let receiver = try FileV2Decryptor(fileID: Support.hex(vector.descriptor.id),
                                                   fileKey: Support.hex(vector.descriptor.k),
                                                   header: Support.hex(vector.descriptor.h),
                                                   size: vector.descriptor.sz)
                try receiver.decryptFile(from: blobURL, to: outputURL)
                XCTFail("\(vector.name): the receiver ACCEPTED a blob that must fail with \(vector.expect)")
            } catch let error as FileV2Error {
                XCTAssertEqual(error.code, vector.expect, "\(vector.name): \(error)")
            }
            XCTAssertFalse(FileManager.default.fileExists(atPath: outputURL.path),
                           "\(vector.name): a failed transfer left plaintext on disk")
            exercised += 1
        }
        XCTAssertEqual(exercised, kat.negative_blobs.count)
        XCTAssertEqual(recipes, 6, "the six multi-chunk recipe vectors")
    }

    func testEveryNegativeChunkVector() throws {
        let kat = try Support.loadKat()
        XCTAssertFalse(kat.negative_chunks.isEmpty)
        for vector in kat.negative_chunks {
            let receiver = try FileV2Decryptor(fileID: Support.hex(vector.descriptor.id),
                                               fileKey: Support.hex(vector.descriptor.k),
                                               header: Support.hex(vector.descriptor.h),
                                               size: vector.descriptor.sz)
            let chunk = Support.hex(vector.chunk_hex)
            if vector.expect == "discard" {
                // An index past the end is dropped: no error, nothing allocated, nothing marked verified.
                XCTAssertNil(try receiver.openChunk(index: vector.index, sealed: chunk), vector.name)
                XCTAssertEqual(receiver.verifiedCount, 0)
            } else {
                XCTAssertThrowsError(try receiver.openChunk(index: vector.index, sealed: chunk), vector.name) { error in
                    XCTAssertEqual((error as? FileV2Error)?.code, vector.expect, vector.name)
                }
            }
        }
    }

    // MARK: Descriptors

    func testEveryDescriptorVector() throws {
        let kat = try Support.loadKat()
        XCTAssertFalse(kat.descriptors.isEmpty)
        for vector in kat.descriptors {
            if vector.expect == "ok" {
                XCTAssertNoThrow(try FileV2Descriptor.parse(vector.serialized), vector.name)
            } else {
                XCTAssertThrowsError(try FileV2Descriptor.parse(vector.serialized), vector.name) { error in
                    XCTAssertEqual((error as? FileV2Error)?.code, vector.expect, vector.name)
                }
            }
        }
    }

    /// The three valid descriptors, field by field, and their headers against the file vectors they were built from.
    func testValidDescriptorsCarryTheVectorsTheyDescribe() throws {
        let kat = try Support.loadKat()
        func descriptor(_ name: String) throws -> FileV2Descriptor {
            let vector = try XCTUnwrap(kat.descriptors.first(where: { $0.name == name }), "no descriptor vector \(name)")
            return try FileV2Descriptor.parse(vector.serialized)
        }
        func file(_ name: String) throws -> FileV2Kat.FileVector {
            try XCTUnwrap(kat.files.first(where: { $0.name == name }), "no file vector \(name)")
        }

        // A file with a thumbnail, 1:1.
        let withThumbnail = try descriptor("valid_file_with_thumbnail")
        let f1023 = try file("f_1023")
        XCTAssertEqual(Support.hexString(withThumbnail.fileID), f1023.file_id)
        XCTAssertEqual(Support.hexString(withThumbnail.fileKey), f1023.k)
        XCTAssertEqual(Support.hexString(withThumbnail.header.bytes), f1023.header)
        XCTAssertEqual(withThumbnail.size, 1023)
        XCTAssertEqual(withThumbnail.kind, .file)
        XCTAssertEqual(withThumbnail.name, "relazione.pdf")
        XCTAssertEqual(withThumbnail.mimeType, "application/pdf")
        XCTAssertEqual(withThumbnail.source.via, .srv)
        XCTAssertEqual(withThumbnail.source.obj?.count, 32)
        XCTAssertEqual(withThumbnail.source.token?.exp, 1_760_000_000_000)
        XCTAssertEqual(withThumbnail.source.token?.max, 100)
        XCTAssertEqual(withThumbnail.preview, Data("kat-preview".utf8))
        XCTAssertEqual(withThumbnail.ex, 0)
        XCTAssertEqual(withThumbnail.xp, 1)
        let thumbnail = try XCTUnwrap(withThumbnail.thumbnail)
        let f1048575 = try file("f_1048575")
        XCTAssertEqual(thumbnail.kind, .thumb)
        XCTAssertEqual(Support.hexString(thumbnail.fileID), f1048575.file_id)
        XCTAssertEqual(thumbnail.size, 1_048_575)
        XCTAssertNil(thumbnail.thumbnail)
        // The descriptor opens a receiver for its own file.
        let receiver = try FileV2Decryptor(descriptor: withThumbnail)
        XCTAssertEqual(receiver.totalChunks, f1023.total_chunks)

        // A voice note on the direct path.
        let voice = try descriptor("valid_voice_note_direct")
        XCTAssertEqual(Support.hexString(voice.fileID), try file("f_1").file_id)
        XCTAssertEqual(voice.kind, .voice)
        XCTAssertEqual(voice.source.via, .direct)
        XCTAssertNil(voice.source.obj)
        XCTAssertEqual(voice.mimeType, "audio/ogg")
        XCTAssertEqual(voice.media?.dur, 5234)
        XCTAssertEqual(voice.media?.wave, [0, 3, 9, 14, 9, 3, 0])
        XCTAssertNil(voice.thumbnail)

        // An image in a group.
        let image = try descriptor("valid_group_image")
        XCTAssertEqual(Support.hexString(image.fileID), try file("f_1048577").file_id)
        XCTAssertEqual(image.kind, .image)
        XCTAssertEqual(image.media?.w, 1920)
        XCTAssertEqual(image.media?.h, 1080)
        XCTAssertEqual(image.ex, 604_800)
        XCTAssertEqual(image.name, "foto.jpg")

        // No descriptor ever prints its key.
        for parsed in [withThumbnail, voice, image] {
            XCTAssertFalse(parsed.description.contains(Support.hexString(parsed.fileKey)))
            XCTAssertFalse("\(parsed)".contains(Support.hexString(parsed.fileKey)))
        }
    }
}
