import XCTest
import CryptoKit
@testable import QAudionEngine

// The Decodable structs below mirror the keys of the shared KAT file verbatim (snake_case, no CodingKeys):
// renaming would silently break decoding against the cross-platform fixture.
// swiftlint:disable identifier_name

/// The values of `constants` in the KAT: integers and strings.
enum FileV2KatConstant: Decodable, Equatable {
    case number(UInt64)
    case text(String)

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let number = try? container.decode(UInt64.self) {
            self = .number(number)
        } else {
            self = .text(try container.decode(String.self))
        }
    }
}

/// `test/kat/file_v2/file-v2-kat.json`, generated by the server repository's `tools/katgen/filev2`.
struct FileV2Kat: Decodable {
    struct Derivation: Decodable {
        let name: String, k: String, file_id: String, prk: String, k_enc: String, nonce_prefix: String
        let commitment: String
    }
    struct PadmeVector: Decodable {
        let len: UInt64, padded: UInt64
    }
    struct ChunkVector: Decodable {
        let index: Int, final: Int, plain_len: UInt64
        let nonce: String, aad: String, tag: String, ct_sha256: String
    }
    struct FileVector: Decodable {
        let name: String, k: String, file_id: String
        let size: UInt64
        let plaintext_rule: String, plaintext_sha256: String
        let stream_len: UInt64
        let total_chunks: Int
        let header: String
        let chunks: [ChunkVector]
        let blob_len: UInt64
        let blob_sha256: String
        let blob_hex: String?
    }
    struct MaxIndexVector: Decodable {
        let name: String, k: String, file_id: String
        let size: UInt64, stream_len: UInt64
        let total_chunks: Int
        let header: String
        let index: Int, final: Int
        let nonce: String, aad: String
    }
    struct DescriptorFields: Decodable {
        let id: String, k: String, h: String
        let sz: UInt64
    }
    struct Operation: Decodable {
        let op: String
        let i: Int?, j: Int?, final: Int?
        let from: String?
        let comment: String?
    }
    struct NegativeBlob: Decodable {
        let name: String, expect: String, why: String
        let descriptor: DescriptorFields
        let base: String?
        let op: Operation?
        let blob_len: Int
        let blob_sha256: String
        let blob_hex: String?
    }
    struct NegativeChunk: Decodable {
        let name: String, expect: String, why: String
        let descriptor: DescriptorFields
        let index: Int
        let chunk_hex: String
    }
    struct DescriptorVector: Decodable {
        let name: String
        let context: String?
        let expect: String
        let serialized: String
    }

    let format: String
    let version: Int
    let note: String
    let constants: [String: FileV2KatConstant]
    let derivations: [Derivation]
    let padme: [PadmeVector]
    let files: [FileVector]
    let max_index: [MaxIndexVector]
    let negative_blobs: [NegativeBlob]
    let negative_chunks: [NegativeChunk]
    let descriptors: [DescriptorVector]
    let error_codes: [String]
    let receive_order: [String]
}

/// Helpers shared by the file v2 test classes. No test skips silently: a missing resource fails.
enum FileV2TestSupport {

    /// SHA-256 of the KAT file, pinned: the file in this repository must stay a byte-for-byte copy of the one
    /// in the server repository (`test/kat/file_v2/file-v2-kat.json`).
    static let pinnedKatSHA256 = "dfd9774dd37feef2c71f9399b0c708c43fdacd0dab410cc3a347777f31f611ad"
    static let pinnedKatLength = 78_448

    // MARK: Hex and hashing

    static func hex(_ text: String) -> Data {
        var out = Data()
        out.reserveCapacity(text.utf8.count / 2)
        var high: UInt8?
        for character in text.utf8 {
            let value: UInt8
            switch character {
            case 48...57: value = character - 48
            case 97...102: value = character - 87
            case 65...70: value = character - 55
            default: fatalError("not a hex digit in the test vector")
            }
            if let top = high {
                out.append(top << 4 | value)
                high = nil
            } else {
                high = value
            }
        }
        if high != nil { fatalError("odd-length hex in the test vector") }
        return out
    }

    static func hexString(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    static func sha256Hex(_ data: Data) -> String {
        hexString(Data(SHA256.hash(data: data)))
    }

    /// SHA-256 of a file, one MiB at a time.
    static func sha256Hex(ofFile url: URL) throws -> String {
        let handle = try FileHandle(forReadingFrom: url)
        defer { try? handle.close() }
        var hasher = SHA256()
        while let block = try handle.read(upToCount: 1 << 20), !block.isEmpty {
            hasher.update(data: block)
        }
        return hexString(Data(hasher.finalize()))
    }

    // MARK: The KAT file

    static func katBytes() throws -> Data {
        let candidates: [URL?] = [
            Bundle.module.url(forResource: "file-v2-kat", withExtension: "json"),
            Bundle.module.url(forResource: "file-v2-kat", withExtension: "json", subdirectory: "kat"),
            Bundle.module.url(forResource: "file-v2-kat", withExtension: "json", subdirectory: "Resources/kat")
        ]
        guard let url = candidates.compactMap({ $0 }).first else {
            throw FileV2TestError.missingKat
        }
        return try Data(contentsOf: url)
    }

    static func loadKat() throws -> FileV2Kat {
        try JSONDecoder().decode(FileV2Kat.self, from: try katBytes())
    }

    /// A missing KAT resource FAILS the test that needs it: nothing here skips silently.
    enum FileV2TestError: Error { case missingKat }

    // MARK: Deterministic plaintext (byte j = j mod 251) and temporary files

    /// `count` bytes of the KAT plaintext starting at stream offset `offset`.
    static func plaintextBlock(offset: UInt64, count: Int) -> Data {
        var bytes = [UInt8](repeating: 0, count: count)
        var phase = Int(offset % 251)
        for index in 0..<count {
            bytes[index] = UInt8(phase)
            phase += 1
            if phase == 251 { phase = 0 }
        }
        return Data(bytes)
    }

    /// Writes the KAT plaintext of `size` bytes to `url`, one MiB at a time.
    static func writePlaintextFile(size: UInt64, to url: URL) throws {
        XCTAssertTrue(FileManager.default.createFile(atPath: url.path, contents: nil))
        let handle = try FileHandle(forWritingTo: url)
        defer { try? handle.close() }
        var offset: UInt64 = 0
        while offset < size {
            let count = Int(min(UInt64(1 << 20), size - offset))
            try handle.write(contentsOf: plaintextBlock(offset: offset, count: count))
            offset += UInt64(count)
        }
    }

    /// A fresh directory, removed when the test ends.
    static func makeTempDirectory(for testCase: XCTestCase) throws -> URL {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("filev2-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        testCase.addTeardownBlock { try? FileManager.default.removeItem(at: directory) }
        return directory
    }

    // MARK: Memory

    /// The resident memory of this process in bytes, `nil` where it cannot be read.
    static func residentMemoryBytes() -> UInt64? {
        #if canImport(Darwin)
        var info = mach_task_basic_info()
        var count = mach_msg_type_number_t(MemoryLayout<mach_task_basic_info>.size / MemoryLayout<natural_t>.size)
        let result = withUnsafeMutablePointer(to: &info) { pointer in
            pointer.withMemoryRebound(to: integer_t.self, capacity: Int(count)) {
                task_info(mach_task_self_, task_flavor_t(MACH_TASK_BASIC_INFO), $0, &count)
            }
        }
        return result == KERN_SUCCESS ? UInt64(info.resident_size) : nil
        #else
        guard let statm = try? String(contentsOfFile: "/proc/self/statm", encoding: .utf8) else { return nil }
        let fields = statm.split(separator: " ")
        guard fields.count > 1, let pages = UInt64(fields[1]) else { return nil }
        return pages * UInt64(sysconf(Int32(_SC_PAGESIZE)))
        #endif
    }
}
