import XCTest
import CryptoKit
@testable import QAudionEngine

// The KAT JSON mirrors the desktop generator's key names verbatim.
// swiftlint:disable force_cast

/// Transcript v5 + DTLS fingerprint binding (WIRE_SPEC 3.7 / 3.8) against the shared KAT
/// (`Resources/handshake-sig-v5-kat.json`, generated by the desktop with `node:crypto` and pure
/// Ed25519, synthetic keys and certificates only).
///
/// CryptoKit signs non-deterministically, so the signatures are not compared byte for byte: the
/// golden `sigV5` of the KAT is VERIFIED under the golden identity key, and a fresh signature made
/// here is verified too. Everything else (transcript bytes, hashes, session key, SAS words,
/// KCMAC, frame keys, canonical forms, SDP verdicts) is compared byte for byte.
final class HandshakeTranscriptV5Tests: XCTestCase {

    /// sha256 of the KAT file; the test refuses any other bytes.
    private static let pinnedSha256 = "dc0d569f4107f19adc339fb13641c474d26a94b042734c3e41fe05ebd2bd78df"

    // MARK: - Loading

    private func katData() throws -> Data {
        guard let url = Bundle.module.url(forResource: "handshake-sig-v5-kat", withExtension: "json") else {
            XCTFail("handshake-sig-v5-kat.json not found in Bundle.module")
            throw NSError(domain: "kat", code: 1)
        }
        return try Data(contentsOf: url)
    }

    private func kat() throws -> [String: Any] {
        let obj = try JSONSerialization.jsonObject(with: try katData())
        return obj as! [String: Any]
    }

    private func hex(_ text: String) -> Data {
        var out = Data()
        var index = text.startIndex
        while index < text.endIndex {
            let next = text.index(index, offsetBy: 2)
            out.append(UInt8(text[index..<next], radix: 16) ?? 0)
            index = next
        }
        return out
    }

    private func toHex(_ data: Data) -> String {
        return data.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Vector decoding

    private struct Built {
        let id: String
        let offer: Data
        let accept: Data
        let offerBinding: Data
        let acceptHash: Data
        let offererKey: Data
        let acceptorKey: Data
        let offererSeed: Data
        let acceptorSeed: Data
        let offererFpText: String
        let acceptorFpText: String
    }

    private func caps(_ d: [String: Any]) -> HandshakeTranscript.Caps9 {
        func b(_ k: String) -> Bool { (d[k] as? Bool) ?? false }
        return HandshakeTranscript.Caps9(
            ratchetV3: b("ratchetV3"), sframeV1: b("sframeV1"), vkeyV1: b("vkeyV1"),
            sessionKdfV3: b("sessionKdfV3"), ratchetV4: b("ratchetV4"), srtpDirKeyV1: b("srtpDirKeyV1"),
            pskMixV1: b("pskMixV1"), hsTranscriptBindV1: b("hsTranscriptBindV1"), ratchetV5: b("ratchetV5"))
    }

    private func optionalBytes(_ hexText: String) -> Data? {
        return hexText.isEmpty ? nil : hex(hexText)
    }

    /// Build OFFER_v5 / ACCEPT_v5 of a transcript vector, optionally with substituted DTLS
    /// fingerprints (negative cases).
    private func build(
        _ vector: [String: Any], offererFp: Data? = nil, acceptorFp: Data? = nil
    ) throws -> Built {
        let inputs = vector["inputs"] as! [String: Any]
        let o = inputs["offerer"] as! [String: Any]
        let a = inputs["acceptor"] as! [String: Any]
        let callId = inputs["callId"] as! String
        let oFp = offererFp ?? hex(o["dtlsFingerprintBinHex"] as! String)
        let aFp = acceptorFp ?? hex(a["dtlsFingerprintBinHex"] as! String)

        let offer = try XCTUnwrap(HandshakeTranscript.offer(
            callId: callId,
            signerIdentityKey: hex(o["identityKeyHex"] as! String),
            epochId: hex(o["epochIdHex"] as! String),
            pqcPublicKey: hex(o["pqcPublicKeyHex"] as! String),
            x25519PublicKey: hex(o["x25519PublicKeyHex"] as! String),
            strongBoxPublicKey: optionalBytes(o["strongBoxPublicKeyHex"] as! String),
            dualCurvePublicKey: optionalBytes(o["dualCurvePublicKeyHex"] as! String),
            caps: caps(o["capabilities"] as! [String: Any]),
            ratchetV: UInt8((o["ratchetV"] as! NSNumber).intValue),
            suiteId: UInt8((o["suiteId"] as! NSNumber).intValue),
            pskFingerprints: o["pskFingerprints"] as? [String],
            pskRoles: (o["pskRoles"] as? [NSNumber])?.map { $0.intValue },
            rekeyNonce: hex(o["rekeyNonceHex"] as! String),
            rekeyRound: UInt32((o["round"] as! NSNumber).intValue),
            dtlsFingerprint: oFp))
        let binding = HandshakeTranscript.offerBinding(offer)
        let accept = try XCTUnwrap(HandshakeTranscript.accept(
            callId: callId,
            signerIdentityKey: hex(a["identityKeyHex"] as! String),
            epochId: hex(a["epochIdHex"] as! String),
            ctPqc: hex(a["ctPqcHex"] as! String),
            ctX25519: hex(a["ctX25519Hex"] as! String),
            ctStrongBox: optionalBytes(a["ctStrongBoxHex"] as! String),
            ctDualCurve: optionalBytes(a["ctDualCurveHex"] as! String),
            caps: caps(a["capabilities"] as! [String: Any]),
            ratchetV: UInt8((a["ratchetV"] as! NSNumber).intValue),
            suiteId: UInt8((a["suiteId"] as! NSNumber).intValue),
            selectedPskFingerprint: a["selectedPskFingerprint"] as? String,
            offerBinding: binding,
            responderPskFingerprints: a["responderPskFingerprints"] as? [String],
            responderPskRoles: (a["responderPskRoles"] as? [NSNumber])?.map { $0.intValue },
            rekeyNonce: hex(a["rekeyNonceHex"] as! String),
            rekeyRound: UInt32((a["round"] as! NSNumber).intValue),
            dtlsFingerprint: aFp))
        return Built(
            id: vector["id"] as! String, offer: offer, accept: accept, offerBinding: binding,
            acceptHash: HandshakeTranscript.offerBinding(accept),
            offererKey: hex(o["identityKeyHex"] as! String), acceptorKey: hex(a["identityKeyHex"] as! String),
            offererSeed: hex(o["seedHex"] as! String), acceptorSeed: hex(a["seedHex"] as! String),
            offererFpText: o["dtlsFingerprint"] as! String, acceptorFpText: a["dtlsFingerprint"] as! String)
    }

    private func transcriptVectors() throws -> [[String: Any]] {
        return (try kat()["transcripts"] as! [String: Any])["vectors"] as! [[String: Any]]
    }

    // MARK: - File pin

    func testFileIsThePinnedOne() throws {
        let digest = SHA256.hash(data: try katData()).map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(digest, Self.pinnedSha256, "handshake-sig-v5-kat.json changed: re-pin only after the desktop republished it")
        XCTAssertEqual((try kat())["version"] as? Int, 5)
    }

    // MARK: - Certificates, canonical forms, SDP

    func testCertificateVectors() throws {
        for c in try kat()["certVectors"] as! [[String: Any]] {
            let name = c["name"] as! String
            let want = hex(c["fingerprintBinHex"] as! String)
            XCTAssertEqual(DtlsFingerprint.fromPem(c["pem"] as! String), want, "[\(name)] PEM")
            XCTAssertEqual(DtlsFingerprint.fromDer(hex(c["derHex"] as! String)), want, "[\(name)] DER")
            XCTAssertEqual(DtlsFingerprint.canonicalText(want), c["fingerprintCanonical"] as? String, "[\(name)] text")
        }
    }

    func testCanonicalVectors() throws {
        let cases = try kat()["canonical"] as! [[String: Any]]
        XCTAssertGreaterThan(cases.count, 10)
        for c in cases {
            let text = c["text"] as! String
            let label = (c["id"] as? String) ?? String(text.prefix(24))
            let parsed = DtlsFingerprint.parseCanonical(text)
            if (c["verdict"] as! String) == "ok" {
                XCTAssertEqual(parsed, hex(c["binHex"] as! String), "[\(label)]")
                XCTAssertEqual(DtlsFingerprint.canonicalText(try XCTUnwrap(parsed)), text, "[\(label)] round trip")
            } else {
                XCTAssertNil(parsed, "[\(label)] must be rejected")
            }
        }
    }

    func testSdpVectors() throws {
        let cases = try kat()["sdp"] as! [[String: Any]]
        XCTAssertGreaterThan(cases.count, 10)
        for c in cases {
            let id = c["id"] as! String
            let expected = try XCTUnwrap(DtlsFingerprint.parseCanonical(c["expectedFp"] as! String))
            let ok = DtlsFingerprint.checkSdp(c["text"] as! String, expected: expected)
            XCTAssertEqual(ok, (c["verdict"] as! String) == "ok", "[\(id)]")
        }
    }

    // MARK: - Transcripts and signatures

    func testTranscriptBytesHashesAndSignatures() throws {
        for vector in try transcriptVectors() {
            let expected = vector["expected"] as! [String: Any]
            let b = try build(vector)
            let id = b.id
            XCTAssertEqual(toHex(b.offer), expected["offerV5Hex"] as? String, "[\(id)] OFFER_v5 bytes")
            XCTAssertEqual(b.offer.count, (expected["offerV5Len"] as! NSNumber).intValue, "[\(id)] OFFER_v5 length")
            XCTAssertEqual(toHex(b.offerBinding), expected["offerBindingHex"] as? String, "[\(id)] offerBinding")
            XCTAssertEqual(toHex(b.offerBinding), expected["offerV5Sha256Hex"] as? String)
            XCTAssertEqual(toHex(b.accept), expected["acceptV5Hex"] as? String, "[\(id)] ACCEPT_v5 bytes")
            XCTAssertEqual(b.accept.count, (expected["acceptV5Len"] as! NSNumber).intValue, "[\(id)] ACCEPT_v5 length")
            XCTAssertEqual(toHex(b.acceptHash), expected["acceptV5Sha256Hex"] as? String, "[\(id)] ACCEPT_v5 hash")

            // DTLSFP is the LAST field of both transcripts, 33 bytes.
            let o = (vector["inputs"] as! [String: Any])["offerer"] as! [String: Any]
            let a = (vector["inputs"] as! [String: Any])["acceptor"] as! [String: Any]
            XCTAssertEqual(b.offer.suffix(33), hex(o["dtlsFingerprintBinHex"] as! String))
            XCTAssertEqual(b.accept.suffix(33), hex(a["dtlsFingerprintBinHex"] as! String))

            // Golden signatures verify (CryptoKit's own are not byte-compared).
            XCTAssertTrue(HandshakeTranscript.verify(
                transcript: b.offer, signature: hex(expected["sigV5OfferHex"] as! String),
                signerIdentityKey: b.offererKey), "[\(id)] golden OFFER signature")
            XCTAssertTrue(HandshakeTranscript.verify(
                transcript: b.accept, signature: hex(expected["sigV5AcceptHex"] as! String),
                signerIdentityKey: b.acceptorKey), "[\(id)] golden ACCEPT signature")
            // The golden signature does not verify another transcript or another key.
            XCTAssertFalse(HandshakeTranscript.verify(
                transcript: b.accept, signature: hex(expected["sigV5OfferHex"] as! String),
                signerIdentityKey: b.offererKey))
            XCTAssertFalse(HandshakeTranscript.verify(
                transcript: b.offer, signature: hex(expected["sigV5OfferHex"] as! String),
                signerIdentityKey: b.acceptorKey))

            // A fresh signature from the golden seed verifies, and matches the golden key.
            let sig = try HandshakeTranscript.sign(transcript: b.offer, signingPrivateKeyRaw: b.offererSeed)
            XCTAssertTrue(HandshakeTranscript.verify(transcript: b.offer, signature: sig, signerIdentityKey: b.offererKey))
            let priv = try Curve25519.Signing.PrivateKey(rawRepresentation: b.acceptorSeed)
            XCTAssertEqual(priv.publicKey.rawRepresentation, b.acceptorKey, "[\(id)] seed derives the golden identity key")
        }
    }

    /// Flipping any single byte of either transcript breaks the golden signature.
    func testGoldenSignatureRejectsEveryByteFlipSample() throws {
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let expected = vector["expected"] as! [String: Any]
        let b = try build(vector)
        let sig = hex(expected["sigV5OfferHex"] as! String)
        for index in stride(from: 0, to: b.offer.count, by: 37) {
            var t = b.offer
            t[index] ^= 0x01
            XCTAssertFalse(HandshakeTranscript.verify(transcript: t, signature: sig, signerIdentityKey: b.offererKey), "byte \(index)")
        }
        var last = b.offer
        last[last.count - 1] ^= 0x01   // inside DTLSFP
        XCTAssertFalse(HandshakeTranscript.verify(transcript: last, signature: sig, signerIdentityKey: b.offererKey))
    }

    /// The whole decision path with the golden material: signature + fingerprint text + key.
    func testPolicyAuthenticatesGoldenBundleAndRejectsTampering() throws {
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let expected = vector["expected"] as! [String: Any]
        let b = try build(vector)
        let sigB64 = hex(expected["sigV5OfferHex"] as! String).base64EncodedString()
        let keyB64 = b.offererKey.base64EncodedString()
        let verdict = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: keyB64, sigV5B64: sigB64, dtlsFingerprintText: b.offererFpText,
            transcript: b.offer, pinnedKey: nil, serverFetchedKey: b.offererKey, advertisedV4: true,
            advertisedSrtpDirKeyV1: true, advertisedRatchetV5: true)
        XCTAssertEqual(
            verdict,
            .authenticated(tofuPinKey: b.offererKey, v4Capable: true, srtpDirKeyV1Capable: true, ratchetV5Capable: true))

        // The same signature over a transcript carrying another fingerprint: invalid.
        let swapped = try build(vector, offererFp: hex(
            ((vector["inputs"] as! [String: Any])["acceptor"] as! [String: Any])["dtlsFingerprintBinHex"] as! String))
        let tampered = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: keyB64, sigV5B64: sigB64, dtlsFingerprintText: b.offererFpText,
            transcript: swapped.offer, pinnedKey: nil, serverFetchedKey: b.offererKey, advertisedV4: true)
        XCTAssertEqual(tampered, .abort(code: "sig_invalid"))
    }

    // MARK: - KDF, SAS, KCMAC

    private func advert(_ d: [String: Any]) -> [KeyConfirmation.PskAdvertEntry] {
        return KeyConfirmation.pskAdvertEntries(
            fingerprintsHex: d["fps"] as? [String],
            roles: (d["roles"] as? [NSNumber])?.map { $0.intValue })
    }

    func testKdfSasAndKeyConfirmationVectors() throws {
        let vectors = try transcriptVectors()
        for k in (try kat()["kdf"] as! [String: Any])["vectors"] as! [[String: Any]] {
            let id = k["id"] as! String
            let tvId = k["transcriptVector"] as! String
            let tv = try XCTUnwrap(vectors.first { ($0["id"] as! String) == tvId })
            let b = try build(tv)
            let inputs = k["inputs"] as! [String: Any]
            let expected = k["expected"] as! [String: Any]
            XCTAssertEqual(toHex(b.acceptHash), inputs["acceptV5Sha256Hex"] as? String, "[\(id)] accept hash input")
            XCTAssertEqual(toHex(b.offerBinding), inputs["offerV5Sha256Hex"] as? String, "[\(id)] offer hash input")

            // Session key: unconditional transcript-bound KDF.
            let pskHex = inputs["pskHex"] as! String
            let key = QAudionCallIntegration.deriveTranscriptBoundSessionKey(
                pqcSharedSecret: hex(inputs["pqcSharedSecretHex"] as! String),
                x25519Shared: hex(inputs["x25519SharedSecretHex"] as! String),
                psk: pskHex.isEmpty ? nil : hex(pskHex),
                transcriptHash: b.acceptHash)
            XCTAssertEqual(toHex(key), expected["sessionKeyHex"] as? String, "[\(id)] session key")

            // SAS: six words over the same hash.
            let sas = try ComputeSasUseCase.invoke(sessionKey: key, transcriptHash: b.acceptHash)
            XCTAssertEqual(sas.words, expected["sasWords"] as? [String], "[\(id)] SAS words")

            // KCMAC with offer/accept bindings = SHA-256(OFFER_v5) / SHA-256(ACCEPT_v5).
            let mixed = (inputs["kcMixedFingerprints"] as! [String]).map { hex($0) }
            let kcT = try XCTUnwrap(KeyConfirmation.transcript(
                offerBinding: b.offerBinding, acceptBinding: b.acceptHash,
                initAdvert: advert(inputs["kcInitAdvert"] as! [String: Any]),
                respAdvert: advert(inputs["kcRespAdvert"] as! [String: Any]),
                mixFingerprints: mixed, mixId: Data(), ikInit: b.offererKey, ikResp: b.acceptorKey))
            XCTAssertEqual(toHex(kcT), expected["kcTranscriptHex"] as? String, "[\(id)] kc transcript")
            let kKc = KeyConfirmation.deriveKcKey(sessionKey: key)
            XCTAssertEqual(toHex(kKc), expected["kKcHex"] as? String, "[\(id)] K_kc")
            let macInit = KeyConfirmation.macInit(kcKey: kKc, transcript: kcT)
            let macResp = KeyConfirmation.macResp(kcKey: kKc, transcript: kcT)
            XCTAssertEqual(toHex(macInit), expected["kcMacInitHex"] as? String, "[\(id)] kc_mac_init")
            XCTAssertEqual(toHex(macResp), expected["kcMacRespHex"] as? String, "[\(id)] kc_mac_resp")
            XCTAssertTrue(KeyConfirmation.verify(received: macInit, kcKey: kKc, asInitiator: true, transcript: kcT))
            XCTAssertFalse(KeyConfirmation.verify(received: macInit, kcKey: kKc, asInitiator: false, transcript: kcT))
        }
    }

    // MARK: - Negative: a substituted DTLS fingerprint diverges the two legs

    func testSubstitutedFingerprintDivergesKeySasAndKcmac() throws {
        let negative = try kat()["negative"] as! [String: Any]
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let inputs = vector["inputs"] as! [String: Any]
        let offererFp = hex((inputs["offerer"] as! [String: Any])["dtlsFingerprintBinHex"] as! String)
        let acceptorFp = hex((inputs["acceptor"] as! [String: Any])["dtlsFingerprintBinHex"] as! String)
        let pqcSS = hex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20")
        let x25519SS = hex("606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f")

        func leg(_ b: Built) throws -> (hash: String, key: String, words: [String], kcMac: Data) {
            let key = QAudionCallIntegration.deriveTranscriptBoundSessionKey(
                pqcSharedSecret: pqcSS, x25519Shared: x25519SS, psk: nil, transcriptHash: b.acceptHash)
            let words = try ComputeSasUseCase.invoke(sessionKey: key, transcriptHash: b.acceptHash).words
            let kcT = try XCTUnwrap(KeyConfirmation.transcript(
                offerBinding: b.offerBinding, acceptBinding: b.acceptHash, initAdvert: [], respAdvert: [],
                mixFingerprints: [], mixId: Data(), ikInit: b.offererKey, ikResp: b.acceptorKey))
            let mac = KeyConfirmation.macInit(kcKey: KeyConfirmation.deriveKcKey(sessionKey: key), transcript: kcT)
            return (toHex(b.acceptHash), toHex(key), words, mac)
        }

        let honestB = try build(vector)
        let honest = try leg(honestB)
        let honestKat = negative["honest"] as! [String: Any]
        XCTAssertEqual(honest.hash, honestKat["acceptV5Sha256Hex"] as? String)
        XCTAssertEqual(honest.key, honestKat["sessionKeyHex"] as? String)
        XCTAssertEqual(honest.words, honestKat["sasWords"] as? [String])

        for c in negative["cases"] as! [[String: Any]] {
            let id = c["id"] as! String
            // The offerer's leg sees another fingerprint in the ACCEPT / the acceptor's leg sees
            // another one in the OFFER (the generator swaps the two real fingerprints).
            let mutatedBuild: Built
            switch id {
            case "acceptor-fingerprint-substituted-in-accept":
                mutatedBuild = try build(vector, acceptorFp: offererFp)
            case "offerer-fingerprint-substituted-in-offer":
                mutatedBuild = try build(vector, offererFp: acceptorFp)
            default:
                XCTFail("unknown negative case \(id)"); continue
            }
            let mutated = try leg(mutatedBuild)
            let want = c["mutated"] as! [String: Any]
            XCTAssertEqual(mutated.hash, want["acceptV5Sha256Hex"] as? String, "[\(id)] ACCEPT hash")
            XCTAssertEqual(mutated.key, want["sessionKeyHex"] as? String, "[\(id)] session key")
            XCTAssertEqual(mutated.words, want["sasWords"] as? [String], "[\(id)] SAS")
            // The two legs disagree on everything the user and the receiver depend on.
            XCTAssertNotEqual(mutated.hash, honest.hash)
            XCTAssertNotEqual(mutated.key, honest.key)
            XCTAssertNotEqual(mutated.words, honest.words)
            XCTAssertNotEqual(mutated.kcMac, honest.kcMac, "[\(id)] the KCMAC of the mutated leg must not verify")
        }
    }

    // MARK: - Directional frame keys

    func testFrameKeyVectors() throws {
        let vectors = (try kat()["frameKeys"] as! [String: Any])["vectors"] as! [[String: Any]]
        XCTAssertGreaterThanOrEqual(vectors.count, 3)
        for v in vectors {
            let id = v["id"] as! String
            let keys = try XCTUnwrap(OneToOneFrameKeys.derive(
                sessionKey: hex(v["sessionKeyHex"] as! String), callId: v["callId"] as! String), id)
            XCTAssertEqual(toHex(keys.offererToAcceptor), v["o2aHex"] as? String, "[\(id)] o2a")
            XCTAssertEqual(toHex(keys.acceptorToOfferer), v["a2oHex"] as? String, "[\(id)] a2o")
        }
    }
}
// swiftlint:enable force_cast
