import XCTest
import CryptoKit
@testable import QAudionEngine

// The KAT JSON mirrors the desktop generator's key names verbatim.
// swiftlint:disable force_cast

/// Transcript v6 (caller SAS commitment + REVEAL) + DTLS fingerprint binding (WIRE_SPEC 3.7 / 3.7.4 /
/// 3.8) against the shared KAT (`Resources/handshake-sig-v6-kat.json`, generated by the desktop with
/// `node:crypto` and pure Ed25519, synthetic keys and certificates only, independently recomputed by the
/// server's Go verifier and the Python design-check reference).
///
/// CryptoKit signs non-deterministically, so the signatures are not compared byte for byte: the
/// golden `sigV6` of the KAT is VERIFIED under the golden identity key, and a fresh signature made
/// here is verified too. Everything else (transcript bytes, hashes, commitments, session key, SAS words,
/// KCMAC, frame keys, REVEAL verdicts, bundle verdicts, canonical forms, SDP verdicts) is compared byte
/// for byte. The `sequences` section is consumed by `SasCommitSequenceTests`.
final class HandshakeTranscriptV6Tests: XCTestCase {

    /// sha256 of the KAT file; the test refuses any other bytes.
    private static let pinnedSha256 = "6151ad3b1d51afd22674ceefa3376654428c918fae89c8e15f28b300da91fb15"

    // MARK: - Loading

    private func katData() throws -> Data {
        guard let url = Bundle.module.url(forResource: "handshake-sig-v6-kat", withExtension: "json") else {
            XCTFail("handshake-sig-v6-kat.json not found in Bundle.module")
            throw NSError(domain: "kat", code: 1)
        }
        return try Data(contentsOf: url)
    }

    private func kat() throws -> [String: Any] {
        let obj = try JSONSerialization.jsonObject(with: try katData())
        return obj as! [String: Any]
    }

    private func hex(_ text: String) -> Data {
        var out = Data()
        var index = text.startIndex
        while index < text.endIndex {
            let next = text.index(index, offsetBy: 2)
            out.append(UInt8(text[index..<next], radix: 16) ?? 0)
            index = next
        }
        return out
    }

    private func toHex(_ data: Data) -> String {
        return data.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Vector decoding

    private struct Built {
        let id: String
        let offer: Data
        let accept: Data
        let offerBinding: Data
        let acceptHash: Data
        let offererKey: Data
        let acceptorKey: Data
        let offererSeed: Data
        let acceptorSeed: Data
        let offererFpText: String
        let acceptorFpText: String
    }

    private func caps(_ d: [String: Any]) -> HandshakeTranscript.Caps9 {
        func b(_ k: String) -> Bool { (d[k] as? Bool) ?? false }
        return HandshakeTranscript.Caps9(
            ratchetV3: b("ratchetV3"), sframeV1: b("sframeV1"), vkeyV1: b("vkeyV1"),
            sessionKdfV3: b("sessionKdfV3"), ratchetV4: b("ratchetV4"), srtpDirKeyV1: b("srtpDirKeyV1"),
            pskMixV1: b("pskMixV1"), hsTranscriptBindV1: b("hsTranscriptBindV1"), ratchetV5: b("ratchetV5"))
    }

    private func optionalBytes(_ hexText: String) -> Data? {
        return hexText.isEmpty ? nil : hex(hexText)
    }

    /// Build OFFER_v6 / ACCEPT_v6 of a transcript vector, optionally with substituted DTLS
    /// fingerprints or a substituted commitment (negative cases).
    private func build(
        _ vector: [String: Any], offererFp: Data? = nil, acceptorFp: Data? = nil, sasCommit: Data? = nil
    ) throws -> Built {
        let inputs = vector["inputs"] as! [String: Any]
        let o = inputs["offerer"] as! [String: Any]
        let a = inputs["acceptor"] as! [String: Any]
        let callId = inputs["callId"] as! String
        let oFp = offererFp ?? hex(o["dtlsFingerprintBinHex"] as! String)
        let aFp = acceptorFp ?? hex(a["dtlsFingerprintBinHex"] as! String)
        let commit = sasCommit ?? optionalBytes(o["sasCommitHex"] as! String)

        let offer = try XCTUnwrap(HandshakeTranscript.offer(
            callId: callId,
            signerIdentityKey: hex(o["identityKeyHex"] as! String),
            epochId: hex(o["epochIdHex"] as! String),
            pqcPublicKey: hex(o["pqcPublicKeyHex"] as! String),
            x25519PublicKey: hex(o["x25519PublicKeyHex"] as! String),
            strongBoxPublicKey: optionalBytes(o["strongBoxPublicKeyHex"] as! String),
            dualCurvePublicKey: optionalBytes(o["dualCurvePublicKeyHex"] as! String),
            caps: caps(o["capabilities"] as! [String: Any]),
            ratchetV: UInt8((o["ratchetV"] as! NSNumber).intValue),
            suiteId: UInt8((o["suiteId"] as! NSNumber).intValue),
            pskFingerprints: o["pskFingerprints"] as? [String],
            pskRoles: (o["pskRoles"] as? [NSNumber])?.map { $0.intValue },
            rekeyNonce: hex(o["rekeyNonceHex"] as! String),
            rekeyRound: UInt32((o["round"] as! NSNumber).intValue),
            dtlsFingerprint: oFp,
            sasCommit: commit))
        let binding = HandshakeTranscript.offerBinding(offer)
        let accept = try XCTUnwrap(HandshakeTranscript.accept(
            callId: callId,
            signerIdentityKey: hex(a["identityKeyHex"] as! String),
            epochId: hex(a["epochIdHex"] as! String),
            ctPqc: hex(a["ctPqcHex"] as! String),
            ctX25519: hex(a["ctX25519Hex"] as! String),
            ctStrongBox: optionalBytes(a["ctStrongBoxHex"] as! String),
            ctDualCurve: optionalBytes(a["ctDualCurveHex"] as! String),
            caps: caps(a["capabilities"] as! [String: Any]),
            ratchetV: UInt8((a["ratchetV"] as! NSNumber).intValue),
            suiteId: UInt8((a["suiteId"] as! NSNumber).intValue),
            selectedPskFingerprint: a["selectedPskFingerprint"] as? String,
            offerBinding: binding,
            responderPskFingerprints: a["responderPskFingerprints"] as? [String],
            responderPskRoles: (a["responderPskRoles"] as? [NSNumber])?.map { $0.intValue },
            rekeyNonce: hex(a["rekeyNonceHex"] as! String),
            rekeyRound: UInt32((a["round"] as! NSNumber).intValue),
            dtlsFingerprint: aFp))
        return Built(
            id: vector["id"] as! String, offer: offer, accept: accept, offerBinding: binding,
            acceptHash: HandshakeTranscript.offerBinding(accept),
            offererKey: hex(o["identityKeyHex"] as! String), acceptorKey: hex(a["identityKeyHex"] as! String),
            offererSeed: hex(o["seedHex"] as! String), acceptorSeed: hex(a["seedHex"] as! String),
            offererFpText: o["dtlsFingerprint"] as! String, acceptorFpText: a["dtlsFingerprint"] as! String)
    }

    private func transcriptVectors() throws -> [[String: Any]] {
        return (try kat()["transcripts"] as! [String: Any])["vectors"] as! [[String: Any]]
    }

    private func section(_ name: String) throws -> [[String: Any]] {
        return (try kat()[name] as! [String: Any])["vectors"] as! [[String: Any]]
    }

    // MARK: - File pin

    func testFileIsThePinnedOne() throws {
        let digest = SHA256.hash(data: try katData()).map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(digest, Self.pinnedSha256, "handshake-sig-v6-kat.json changed: re-pin only after the desktop republished it")
        XCTAssertEqual((try kat())["version"] as? Int, 6)
    }

    // MARK: - Certificates, canonical forms, SDP

    func testCertificateVectors() throws {
        for c in try kat()["certVectors"] as! [[String: Any]] {
            let name = c["name"] as! String
            let want = hex(c["fingerprintBinHex"] as! String)
            XCTAssertEqual(DtlsFingerprint.fromPem(c["pem"] as! String), want, "[\(name)] PEM")
            XCTAssertEqual(DtlsFingerprint.fromDer(hex(c["derHex"] as! String)), want, "[\(name)] DER")
            XCTAssertEqual(DtlsFingerprint.canonicalText(want), c["fingerprintCanonical"] as? String, "[\(name)] text")
        }
    }

    func testCanonicalVectors() throws {
        let cases = try kat()["canonical"] as! [[String: Any]]
        XCTAssertGreaterThan(cases.count, 10)
        for c in cases {
            let text = c["text"] as! String
            let label = (c["id"] as? String) ?? String(text.prefix(24))
            let parsed = DtlsFingerprint.parseCanonical(text)
            if (c["verdict"] as! String) == "ok" {
                XCTAssertEqual(parsed, hex(c["binHex"] as! String), "[\(label)]")
                XCTAssertEqual(DtlsFingerprint.canonicalText(try XCTUnwrap(parsed)), text, "[\(label)] round trip")
            } else {
                XCTAssertNil(parsed, "[\(label)] must be rejected")
            }
        }
    }

    func testSdpVectors() throws {
        let cases = try kat()["sdp"] as! [[String: Any]]
        XCTAssertGreaterThan(cases.count, 10)
        for c in cases {
            let id = c["id"] as! String
            let expected = try XCTUnwrap(DtlsFingerprint.parseCanonical(c["expectedFp"] as! String))
            let ok = DtlsFingerprint.checkSdp(c["text"] as! String, expected: expected)
            XCTAssertEqual(ok, (c["verdict"] as! String) == "ok", "[\(id)]")
        }
    }

    // MARK: - Commitment (WIRE_SPEC 3.7.4)

    func testCommitVectors() throws {
        let vectors = try section("commit")
        XCTAssertEqual(vectors.map { $0["id"] as! String }, ["design-check", "commit-basic", "commit-other-call-id"])
        var seen = Set<String>()
        for v in vectors {
            let id = v["id"] as! String
            let expected = v["expected"] as! [String: Any]
            let commit = try XCTUnwrap(SasCommit.commit(callId: v["callId"] as! String, nonce: hex(v["sasNonceHex"] as! String)), id)
            XCTAssertEqual(toHex(commit), expected["sasCommitHex"] as? String, "[\(id)] commitment")
            XCTAssertEqual(commit.base64EncodedString(), expected["sasCommitB64"] as? String, "[\(id)] base64")
            seen.insert(toHex(commit))
        }
        XCTAssertEqual(seen.count, 3, "the callId is part of the commitment")
    }

    func testTheOfferersCommitmentOfEveryRoundOneVectorIsTheCommitOfItsNonce() throws {
        for vector in try transcriptVectors() {
            let o = (vector["inputs"] as! [String: Any])["offerer"] as! [String: Any]
            let callId = (vector["inputs"] as! [String: Any])["callId"] as! String
            let nonceHex = o["sasNonceHex"] as! String
            if (o["round"] as! NSNumber).intValue == 1 {
                let commit = try XCTUnwrap(SasCommit.commit(callId: callId, nonce: hex(nonceHex)))
                XCTAssertEqual(toHex(commit), o["sasCommitHex"] as? String)
            } else {
                XCTAssertEqual(nonceHex, "", "a rekey round has no nonce")
                XCTAssertEqual(o["sasCommitHex"] as? String, "", "a rekey round has no commitment")
            }
        }
    }

    // MARK: - Transcripts and signatures

    func testTranscriptBytesHashesAndSignatures() throws {
        for vector in try transcriptVectors() {
            let expected = vector["expected"] as! [String: Any]
            let b = try build(vector)
            let id = b.id
            XCTAssertEqual(toHex(b.offer), expected["offerV6Hex"] as? String, "[\(id)] OFFER_v6 bytes")
            XCTAssertEqual(b.offer.count, (expected["offerV6Len"] as! NSNumber).intValue, "[\(id)] OFFER_v6 length")
            XCTAssertEqual(toHex(b.offerBinding), expected["offerBindingHex"] as? String, "[\(id)] offerBinding")
            XCTAssertEqual(toHex(b.offerBinding), expected["offerV6Sha256Hex"] as? String)
            XCTAssertEqual(toHex(b.accept), expected["acceptV6Hex"] as? String, "[\(id)] ACCEPT_v6 bytes")
            XCTAssertEqual(b.accept.count, (expected["acceptV6Len"] as! NSNumber).intValue, "[\(id)] ACCEPT_v6 length")
            XCTAssertEqual(toHex(b.acceptHash), expected["acceptV6Sha256Hex"] as? String, "[\(id)] ACCEPT_v6 hash")

            // DTLSFP closes the ACCEPT; the OFFER ends with DTLSFP || LP(sasCommit | empty).
            let o = (vector["inputs"] as! [String: Any])["offerer"] as! [String: Any]
            let a = (vector["inputs"] as! [String: Any])["acceptor"] as! [String: Any]
            let commitHex = o["sasCommitHex"] as! String
            let tail = commitHex.isEmpty ? Data([0x00, 0x00]) : Data([0x00, 0x20]) + hex(commitHex)
            XCTAssertEqual(b.offer.suffix(tail.count), tail, "[\(id)] LP(sasCommit | empty) is the last OFFER field")
            XCTAssertEqual(
                b.offer.suffix(tail.count + 33).prefix(33), hex(o["dtlsFingerprintBinHex"] as! String),
                "[\(id)] DTLSFP precedes the commitment")
            XCTAssertEqual(b.accept.suffix(33), hex(a["dtlsFingerprintBinHex"] as! String))

            // Golden signatures verify (CryptoKit's own are not byte-compared).
            XCTAssertTrue(HandshakeTranscript.verify(
                transcript: b.offer, signature: hex(expected["sigV6OfferHex"] as! String),
                signerIdentityKey: b.offererKey), "[\(id)] golden OFFER signature")
            XCTAssertTrue(HandshakeTranscript.verify(
                transcript: b.accept, signature: hex(expected["sigV6AcceptHex"] as! String),
                signerIdentityKey: b.acceptorKey), "[\(id)] golden ACCEPT signature")
            // The golden signature does not verify another transcript or another key.
            XCTAssertFalse(HandshakeTranscript.verify(
                transcript: b.accept, signature: hex(expected["sigV6OfferHex"] as! String),
                signerIdentityKey: b.offererKey))
            XCTAssertFalse(HandshakeTranscript.verify(
                transcript: b.offer, signature: hex(expected["sigV6OfferHex"] as! String),
                signerIdentityKey: b.acceptorKey))

            // A fresh signature from the golden seed verifies, and matches the golden key.
            let sig = try HandshakeTranscript.sign(transcript: b.offer, signingPrivateKeyRaw: b.offererSeed)
            XCTAssertTrue(HandshakeTranscript.verify(transcript: b.offer, signature: sig, signerIdentityKey: b.offererKey))
            let priv = try Curve25519.Signing.PrivateKey(rawRepresentation: b.acceptorSeed)
            XCTAssertEqual(priv.publicKey.rawRepresentation, b.acceptorKey, "[\(id)] seed derives the golden identity key")
        }
    }

    /// WIRE_SPEC 3.7: `LP(sasCommit | empty)` is 32 bytes in round 1 and empty from round 2; a builder
    /// refuses every other combination (R-COMMIT-FIELD). Fails without the builder's round rule.
    func testTheOfferBuilderRefusesEveryOtherCommitmentCombination() throws {
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let o = (vector["inputs"] as! [String: Any])["offerer"] as! [String: Any]
        func offer(round: UInt32, commit: Data?) -> Data? {
            HandshakeTranscript.offer(
                callId: "c", signerIdentityKey: hex(o["identityKeyHex"] as! String),
                epochId: hex(o["epochIdHex"] as! String),
                pqcPublicKey: Data(repeating: 1, count: 1568), x25519PublicKey: Data(repeating: 2, count: 32),
                strongBoxPublicKey: nil, dualCurvePublicKey: nil, caps: caps(o["capabilities"] as! [String: Any]),
                ratchetV: 4, suiteId: 1, pskFingerprints: nil, pskRoles: nil,
                rekeyNonce: hex(o["rekeyNonceHex"] as! String), rekeyRound: round,
                dtlsFingerprint: hex(o["dtlsFingerprintBinHex"] as! String), sasCommit: commit)
        }
        let c32 = Data(repeating: 0xC1, count: 32)
        XCTAssertNotNil(offer(round: 1, commit: c32))
        XCTAssertNotNil(offer(round: 2, commit: nil))
        XCTAssertNotNil(offer(round: 2, commit: Data()))
        XCTAssertNil(offer(round: 1, commit: nil), "empty with round 1")
        XCTAssertNil(offer(round: 1, commit: Data()), "empty with round 1")
        XCTAssertNil(offer(round: 2, commit: c32), "32 bytes with round >= 2")
        XCTAssertNil(offer(round: UInt32.max, commit: c32))
        XCTAssertNil(offer(round: 1, commit: Data(repeating: 1, count: 31)), "any other length")
        XCTAssertNil(offer(round: 1, commit: Data(repeating: 1, count: 33)), "any other length")
    }

    /// Flipping any single byte of either transcript breaks the golden signature.
    func testGoldenSignatureRejectsEveryByteFlipSample() throws {
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let expected = vector["expected"] as! [String: Any]
        let b = try build(vector)
        let sig = hex(expected["sigV6OfferHex"] as! String)
        for index in stride(from: 0, to: b.offer.count, by: 37) {
            var t = b.offer
            t[index] ^= 0x01
            XCTAssertFalse(HandshakeTranscript.verify(transcript: t, signature: sig, signerIdentityKey: b.offererKey), "byte \(index)")
        }
        var last = b.offer
        last[last.count - 1] ^= 0x01   // inside the commitment
        XCTAssertFalse(HandshakeTranscript.verify(transcript: last, signature: sig, signerIdentityKey: b.offererKey))
    }

    /// The whole decision path with the golden material: signature + fingerprint text + key.
    func testPolicyAuthenticatesGoldenBundleAndRejectsTampering() throws {
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let expected = vector["expected"] as! [String: Any]
        let b = try build(vector)
        let sigB64 = hex(expected["sigV6OfferHex"] as! String).base64EncodedString()
        let keyB64 = b.offererKey.base64EncodedString()
        let verdict = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: keyB64, sigV6B64: sigB64, dtlsFingerprintText: b.offererFpText,
            transcript: b.offer, pinnedKey: nil, serverFetchedKey: b.offererKey, advertisedV4: true,
            advertisedSrtpDirKeyV1: true, advertisedRatchetV5: true)
        XCTAssertEqual(
            verdict,
            .authenticated(tofuPinKey: b.offererKey, v4Capable: true, srtpDirKeyV1Capable: true, ratchetV5Capable: true))

        // The same signature over a transcript carrying another fingerprint: invalid.
        let swapped = try build(vector, offererFp: hex(
            ((vector["inputs"] as! [String: Any])["acceptor"] as! [String: Any])["dtlsFingerprintBinHex"] as! String))
        let tampered = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: keyB64, sigV6B64: sigB64, dtlsFingerprintText: b.offererFpText,
            transcript: swapped.offer, pinnedKey: nil, serverFetchedKey: b.offererKey, advertisedV4: true)
        XCTAssertEqual(tampered, .abort(code: "sig_invalid"))

        // The same signature over a transcript carrying another commitment: invalid too.
        let otherCommit = try XCTUnwrap(SasCommit.commit(callId: "other", nonce: Data(repeating: 9, count: 32)))
        let recommitted = try build(vector, sasCommit: otherCommit)
        let commitTampered = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: keyB64, sigV6B64: sigB64, dtlsFingerprintText: b.offererFpText,
            transcript: recommitted.offer, pinnedKey: nil, serverFetchedKey: b.offererKey, advertisedV4: true)
        XCTAssertEqual(commitTampered, .abort(code: "sig_invalid"), "the commitment is signed")
    }

    // MARK: - KDF, KCMAC

    private func advert(_ d: [String: Any]) -> [KeyConfirmation.PskAdvertEntry] {
        return KeyConfirmation.pskAdvertEntries(
            fingerprintsHex: d["fps"] as? [String],
            roles: (d["roles"] as? [NSNumber])?.map { $0.intValue })
    }

    func testKdfAndKeyConfirmationVectors() throws {
        let vectors = try transcriptVectors()
        for k in try section("kdf") {
            let id = k["id"] as! String
            let tvId = k["transcriptVector"] as! String
            let tv = try XCTUnwrap(vectors.first { ($0["id"] as! String) == tvId })
            let b = try build(tv)
            let inputs = k["inputs"] as! [String: Any]
            let expected = k["expected"] as! [String: Any]
            XCTAssertEqual(toHex(b.acceptHash), inputs["acceptV6Sha256Hex"] as? String, "[\(id)] accept hash input")
            XCTAssertEqual(toHex(b.offerBinding), inputs["offerV6Sha256Hex"] as? String, "[\(id)] offer hash input")

            // Session key: unconditional transcript-bound KDF (the nonce never enters it).
            let pskHex = inputs["pskHex"] as! String
            let key = QAudionCallIntegration.deriveTranscriptBoundSessionKey(
                pqcSharedSecret: hex(inputs["pqcSharedSecretHex"] as! String),
                x25519Shared: hex(inputs["x25519SharedSecretHex"] as! String),
                psk: pskHex.isEmpty ? nil : hex(pskHex),
                transcriptHash: b.acceptHash)
            XCTAssertEqual(toHex(key), expected["sessionKeyHex"] as? String, "[\(id)] session key")

            // KCMAC with offer/accept bindings = SHA-256(OFFER_v6) / SHA-256(ACCEPT_v6).
            let mixed = (inputs["kcMixedFingerprints"] as! [String]).map { hex($0) }
            let kcT = try XCTUnwrap(KeyConfirmation.transcript(
                offerBinding: b.offerBinding, acceptBinding: b.acceptHash,
                initAdvert: advert(inputs["kcInitAdvert"] as! [String: Any]),
                respAdvert: advert(inputs["kcRespAdvert"] as! [String: Any]),
                mixFingerprints: mixed, mixId: Data(), ikInit: b.offererKey, ikResp: b.acceptorKey))
            XCTAssertEqual(toHex(kcT), expected["kcTranscriptHex"] as? String, "[\(id)] kc transcript")
            let kKc = KeyConfirmation.deriveKcKey(sessionKey: key)
            XCTAssertEqual(toHex(kKc), expected["kKcHex"] as? String, "[\(id)] K_kc")
            let macInit = KeyConfirmation.macInit(kcKey: kKc, transcript: kcT)
            let macResp = KeyConfirmation.macResp(kcKey: kKc, transcript: kcT)
            XCTAssertEqual(toHex(macInit), expected["kcMacInitHex"] as? String, "[\(id)] kc_mac_init")
            XCTAssertEqual(toHex(macResp), expected["kcMacRespHex"] as? String, "[\(id)] kc_mac_resp")
            XCTAssertTrue(KeyConfirmation.verify(received: macInit, kcKey: kKc, asInitiator: true, transcript: kcT))
            XCTAssertFalse(KeyConfirmation.verify(received: macInit, kcKey: kKc, asInitiator: false, transcript: kcT))
        }
    }

    // MARK: - SAS (WIRE_SPEC 4)

    func testSasVectors() throws {
        let vectors = try section("sas")
        XCTAssertEqual(vectors.map { $0["id"] as! String }, ["design-check", "sas-basic", "sas-nonce-bit-flip"])
        var wordSets = [[String]]()
        for v in vectors {
            let id = v["id"] as! String
            let inputs = v["inputs"] as! [String: Any]
            let expected = v["expected"] as! [String: Any]
            let sas = try ComputeSasUseCase.invoke(
                sessionKey: hex(inputs["sessionKeyHex"] as! String),
                transcriptHash: hex(inputs["acceptV6Sha256Hex"] as! String),
                sasNonce: hex(inputs["sasNonceHex"] as! String))
            XCTAssertEqual(sas.words, expected["sasWords"] as? [String], "[\(id)] SAS words")
            // the indices: re-derive the KDF output and compare byte for byte
            var info = HkdfLabels.sasV6
            info.append(hex(inputs["acceptV6Sha256Hex"] as! String))
            info.append(hex(inputs["sasNonceHex"] as! String))
            let out = HKDF<SHA256>.deriveKey(
                inputKeyMaterial: SymmetricKey(data: hex(inputs["sessionKeyHex"] as! String)),
                salt: SasConstants.saltBytes, info: info, outputByteCount: 18).withUnsafeBytes { Data($0) }
            XCTAssertEqual(toHex(out), expected["sasKdfHex"] as? String, "[\(id)] SAS-KDF")
            var indices = [Int]()
            for i in 0..<6 { indices.append(((Int(out[3 * i]) << 16) | (Int(out[3 * i + 1]) << 8) | Int(out[3 * i + 2])) % 256) }
            XCTAssertEqual(indices, (expected["sasIndices"] as! [NSNumber]).map { $0.intValue }, "[\(id)] indices")
            wordSets.append(sas.words)
        }
        XCTAssertNotEqual(wordSets[1], wordSets[2], "one flipped nonce bit changes the words")
    }

    /// The sas vector of a transcript is the SAS of its OWN kdf key, ACCEPT hash and nonce: the whole
    /// chain (transcript to session key to words) agrees.
    func testTheSasBasicVectorFollowsFromTheTranscriptAndTheKdfVector() throws {
        let tv = try XCTUnwrap(try transcriptVectors().first { ($0["id"] as! String) == "v6-basic-no-psk" })
        let b = try build(tv)
        let kdf = try XCTUnwrap(try section("kdf").first { ($0["id"] as! String) == "kdf-no-psk" })
        let sas = try XCTUnwrap(try section("sas").first { ($0["id"] as! String) == "sas-basic" })
        let o = (tv["inputs"] as! [String: Any])["offerer"] as! [String: Any]
        let key = hex((kdf["expected"] as! [String: Any])["sessionKeyHex"] as! String)
        let words = try ComputeSasUseCase.invoke(
            sessionKey: key, transcriptHash: b.acceptHash, sasNonce: hex(o["sasNonceHex"] as! String)).words
        XCTAssertEqual(words, (sas["expected"] as! [String: Any])["sasWords"] as? [String])
    }

    // MARK: - REVEAL verdicts

    /// Every REVEAL vector, evaluated by the callee state machine exactly as the integration does.
    func testRevealVectors() throws {
        let vectors = try section("reveal")
        XCTAssertGreaterThanOrEqual(vectors.count, 13)
        for v in vectors {
            let id = v["id"] as! String
            let data = v["data"] as! String
            var callee = SasCommitCallee(callId: v["callId"] as! String, storedCommit: hex(v["storedCommitHex"] as! String))
            callee.setAcceptHash(hex(v["ownAcceptHashHex"] as! String))
            XCTAssertTrue(callee.acceptSent(nowMs: 0))
            // The dispatcher routes by the tag first: anything else is not a REVEAL at all.
            guard case .sasReveal(_, _)? = CallPiggyBack.parse(data) else {
                XCTAssertEqual(v["expect"] as? String, "drop", "[\(id)] not routed as a REVEAL")
                continue
            }
            let outcome = callee.receiveReveal(data: data, nowMs: 100)
            switch v["expect"] as! String {
            case "ok": XCTAssertEqual(outcome, .sasReady, "[\(id)]")
            case "sas_commit_mismatch": XCTAssertEqual(outcome, .end(reason: "sas_commit_mismatch"), "[\(id)]")
            case "sibling": XCTAssertEqual(outcome, .leaveLocally, "[\(id)]")
            case "drop": XCTAssertEqual(outcome, .dropped, "[\(id)]")
            default: XCTFail("[\(id)] unknown expectation")
            }
        }
    }

    /// The REVEAL a caller builds is the vector's `data` byte for byte.
    func testTheCallersRevealIsTheVectorBytes() throws {
        let ok = try XCTUnwrap(try section("reveal").first { ($0["id"] as! String) == "ok-basic" })
        let tv = try XCTUnwrap(try transcriptVectors().first { ($0["id"] as! String) == "v6-basic-no-psk" })
        let b = try build(tv)
        let o = (tv["inputs"] as! [String: Any])["offerer"] as! [String: Any]
        let wire = SasReveal.serialize(
            callId: (tv["inputs"] as! [String: Any])["callId"] as! String,
            acceptBinding: b.acceptHash, nonce: hex(o["sasNonceHex"] as! String))
        XCTAssertEqual(wire, ok["data"] as? String)
        XCTAssertEqual(wire?.count, 27 + 1 + 10 + 88, "callId + `|` + tag + 88 characters")
    }

    // MARK: - Bundle verdicts (WIRE_SPEC 3.1)

    /// What the callee / caller does with a bundle before any signature is evaluated: decode it like the
    /// opaque dispatcher, then apply the structural rules. `handshake_malformed` or `ok`.
    private func structuralVerdict(_ json: String, callId: String, firstOfferOfCall: Bool) -> String {
        guard let parsed = AndroidHandshakeEnvelope.parse(callId + "|" + json) else {
            return AndroidHandshakeEnvelope.malformedBundleCallId(callId + "|" + json) != nil
                ? "handshake_malformed" : "dropped"
        }
        let b = parsed.bundle
        if HandshakeSigningPolicy.sasCommitMalformedCode(
            isOffer: b.kind == .offer, round: b.rekeyRound, sasCommitB64: b.sasCommit) != nil {
            return "handshake_malformed"
        }
        if b.kind == .offer, HandshakeSigningPolicy.firstRoundMalformedCode(
            isFirstOfferOfCall: firstOfferOfCall, round: b.rekeyRound) != nil {
            return "handshake_malformed"
        }
        // the signing fields: a bundle without sigV6 (only a retired sigV5) is malformed
        let verdict = HandshakeSigningPolicy.evaluate(
            signerIdentityKeyB64: b.signerIdentityKey, sigV6B64: b.sigV6, dtlsFingerprintText: b.dtlsFingerprint,
            transcript: nil, pinnedKey: nil, serverFetchedKey: nil, advertisedV4: true)
        if case .malformed(let code) = verdict, code == "sig_missing" || code == "dtlsfp_missing" || code == "dtlsfp_malformed" {
            return "handshake_malformed"
        }
        return "ok"
    }

    func testBundleVectors() throws {
        let vectors = try section("bundle")
        XCTAssertGreaterThanOrEqual(vectors.count, 12)
        var callIds = [String: String]()
        for tv in try transcriptVectors() {
            callIds[tv["id"] as! String] = (tv["inputs"] as! [String: Any])["callId"] as? String
        }
        for v in vectors {
            let id = v["id"] as! String
            let callId = try XCTUnwrap(callIds[v["transcriptVector"] as! String], "[\(id)] transcript vector")
            // A round-1 OFFER is the call's first OFFER; a later round is judged after round 1 was seen.
            let isFirst = !id.contains("r2")
            XCTAssertEqual(
                structuralVerdict(v["json"] as! String, callId: callId, firstOfferOfCall: isFirst),
                v["expect"] as? String, "[\(id)]")
        }
    }

    // MARK: - Negative: a substituted fingerprint or commitment diverges the two legs

    func testSubstitutedFingerprintOrCommitmentDivergesKeySasAndKcmac() throws {
        let negative = try kat()["negative"] as! [String: Any]
        let vector = try XCTUnwrap(try transcriptVectors().first)
        let inputs = vector["inputs"] as! [String: Any]
        let offerer = inputs["offerer"] as! [String: Any]
        let offererFp = hex(offerer["dtlsFingerprintBinHex"] as! String)
        let acceptorFp = hex((inputs["acceptor"] as! [String: Any])["dtlsFingerprintBinHex"] as! String)
        let nonce = hex(offerer["sasNonceHex"] as! String)
        let pqcSS = hex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20")
        let x25519SS = hex("606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f")

        func leg(_ b: Built) throws -> (offerHash: String, hash: String, key: String, words: [String], kcMac: Data) {
            let key = QAudionCallIntegration.deriveTranscriptBoundSessionKey(
                pqcSharedSecret: pqcSS, x25519Shared: x25519SS, psk: nil, transcriptHash: b.acceptHash)
            let words = try ComputeSasUseCase.invoke(sessionKey: key, transcriptHash: b.acceptHash, sasNonce: nonce).words
            let kcT = try XCTUnwrap(KeyConfirmation.transcript(
                offerBinding: b.offerBinding, acceptBinding: b.acceptHash, initAdvert: [], respAdvert: [],
                mixFingerprints: [], mixId: Data(), ikInit: b.offererKey, ikResp: b.acceptorKey))
            let mac = KeyConfirmation.macInit(kcKey: KeyConfirmation.deriveKcKey(sessionKey: key), transcript: kcT)
            return (toHex(b.offerBinding), toHex(b.acceptHash), toHex(key), words, mac)
        }

        let honest = try leg(try build(vector))
        let honestKat = negative["honest"] as! [String: Any]
        XCTAssertEqual(honest.offerHash, honestKat["offerV6Sha256Hex"] as? String)
        XCTAssertEqual(honest.hash, honestKat["acceptV6Sha256Hex"] as? String)
        XCTAssertEqual(honest.key, honestKat["sessionKeyHex"] as? String)
        XCTAssertEqual(honest.words, honestKat["sasWords"] as? [String])

        let otherCommit = try XCTUnwrap(SasCommit.commit(
            callId: inputs["callId"] as! String, nonce: Data((0..<32).map { UInt8((0x55 + $0) & 0xFF) })))
        var seenIds = [String]()
        for c in negative["cases"] as! [[String: Any]] {
            let id = c["id"] as! String
            seenIds.append(id)
            let mutatedBuild: Built
            switch id {
            case "acceptor-fingerprint-substituted-in-accept":
                mutatedBuild = try build(vector, acceptorFp: offererFp)
            case "offerer-fingerprint-substituted-in-offer":
                mutatedBuild = try build(vector, offererFp: acceptorFp)
            case "commit-substituted-in-offer":
                mutatedBuild = try build(vector, sasCommit: otherCommit)
            default:
                XCTFail("unknown negative case \(id)"); continue
            }
            let mutated = try leg(mutatedBuild)
            let want = c["mutated"] as! [String: Any]
            XCTAssertEqual(mutated.hash, want["acceptV6Sha256Hex"] as? String, "[\(id)] ACCEPT hash")
            XCTAssertEqual(mutated.key, want["sessionKeyHex"] as? String, "[\(id)] session key")
            XCTAssertEqual(mutated.words, want["sasWords"] as? [String], "[\(id)] SAS")
            // The two legs disagree on everything the user and the receiver depend on.
            XCTAssertNotEqual(mutated.hash, honest.hash)
            XCTAssertNotEqual(mutated.key, honest.key)
            XCTAssertNotEqual(mutated.words, honest.words)
            XCTAssertNotEqual(mutated.kcMac, honest.kcMac, "[\(id)] the KCMAC of the mutated leg must not verify")
            if id == "commit-substituted-in-offer" {
                XCTAssertNotEqual(mutated.offerHash, honest.offerHash, "the commitment is inside OFFER_v6")
                XCTAssertEqual(mutated.offerHash, want["offerV6Sha256Hex"] as? String)
            }
        }
        XCTAssertEqual(seenIds.count, 3)
    }

    // MARK: - Directional frame keys

    func testFrameKeyVectors() throws {
        let vectors = try section("frameKeys")
        XCTAssertGreaterThanOrEqual(vectors.count, 3)
        for v in vectors {
            let id = v["id"] as! String
            let keys = try XCTUnwrap(OneToOneFrameKeys.derive(
                sessionKey: hex(v["sessionKeyHex"] as! String), callId: v["callId"] as! String), id)
            XCTAssertEqual(toHex(keys.offererToAcceptor), v["o2aHex"] as? String, "[\(id)] o2a")
            XCTAssertEqual(toHex(keys.acceptorToOfferer), v["a2oHex"] as? String, "[\(id)] a2o")
        }
    }
}
// swiftlint:enable force_cast
