import XCTest
import CryptoKit
@testable import QAudionEngine

/// Cross-platform CORRECTED hybrid PQC session-key KAT verifier (iOS).
///
/// Loads `tools/kat/hybrid-combine/hybrid-combine-kat.json` (schema :2,
/// mirrored byte-equal in all BCRYPTO repos, generated by the stdlib-only
/// Python reference and independently re-derived by Node crypto) and
/// asserts that the iOS PRODUCTION path
/// `QAudionCallIntegration.deriveHybridSessionKey` reproduces every
/// pinned (pqcSs, x25519Ss, ciphertext, psk) → sessionKey vector
/// byte-for-byte.
///
/// Schema :1 (no ML-KEM ciphertext binding) is INSECURE and superseded:
/// a MITM could substitute a re-encapsulating ciphertext. Schema :2
/// folds HMAC-SHA256("q-audion-ct-bind-v1", ciphertext) into the HKDF
/// `info` and uses the PSK as the HKDF Extract salt. Byte-identical to
/// firmware `qa_session_handshake_complete` (hybrid path), Android
/// `HybridPqcKeyExchange.deriveSessionKey`, Desktop `deriveHybridSessionKey`.
///
/// Sister tests:
///   apps/qaudion-android-new/.../HybridCombineKatTest.kt
///   apps/qaudion-desktop/test/HybridCombine.kat.spec.ts
///   apps/qaudion-firmware/portable/tests/test_session.c
final class HybridCombineKatTests: XCTestCase {

    private struct KatConstruction: Decodable {
        let kdf: String
        let ct_bind: String
        let ikm: String
        let salt: String
        let info: String
        let output_len_bytes: Int
    }

    private struct KatVector: Decodable {
        let name: String
        let pqc_shared_hex: String
        let x25519_shared_hex: String
        let ciphertext_hex: String
        let psk_hex: String?
        let session_key_hex: String
    }

    private struct KatFile: Decodable {
        let schema: String
        let construction: KatConstruction
        let vectors: [KatVector]
    }

    func testEveryCorrectedHybridVectorMatches() throws {
        guard let kat = loadKatOrNil() else { return }

        XCTAssertEqual(kat.schema, "qaudion-hybrid-combine-kat:2")
        XCTAssertEqual(kat.construction.output_len_bytes, 32)
        XCTAssertGreaterThan(kat.vectors.count, 0)
        // Pin the canonical labels are the ones iOS production uses.
        XCTAssertTrue(kat.construction.salt.contains(
            String(decoding: HkdfLabels.hybridPqcSaltV1, as: UTF8.self)))
        XCTAssertTrue(kat.construction.info.contains(
            String(decoding: HkdfLabels.hybridPqcSessionKey, as: UTF8.self)))
        XCTAssertTrue(kat.construction.ct_bind.contains(
            String(decoding: HkdfLabels.hybridCtBindV1, as: UTF8.self)))

        for v in kat.vectors {
            let derived = QAudionCallIntegration.deriveHybridSessionKey(
                pqcSs: Data(hex: v.pqc_shared_hex),
                x25519Ss: Data(hex: v.x25519_shared_hex),
                pqcCiphertext: Data(hex: v.ciphertext_hex),
                psk: v.psk_hex.map { Data(hex: $0) }
            )
            XCTAssertEqual(
                derived.hexEncodedString(), v.session_key_hex,
                "[\(v.name)] iOS deriveHybridSessionKey drift — IKM=pqcSs(32)||x25519Ss(32), "
                + "salt=\(v.psk_hex != nil ? "psk" : "hybrid-pqc-v1"), "
                + "info='q-audion-session-key'||HMAC('q-audion-ct-bind-v1',ct), L=32"
            )
        }
    }

    private func loadKatOrNil() -> KatFile? {
        let fm = FileManager.default
        var dir = URL(fileURLWithPath: fm.currentDirectoryPath)
        for _ in 0..<6 {
            let candidate = dir.appendingPathComponent("tools/kat/hybrid-combine/hybrid-combine-kat.json")
            if fm.fileExists(atPath: candidate.path) {
                if let data = try? Data(contentsOf: candidate),
                   let kat = try? JSONDecoder().decode(KatFile.self, from: data) {
                    return kat
                }
            }
            dir = dir.deletingLastPathComponent()
        }
        return nil
    }
}

private extension Data {
    init(hex: String) {
        precondition(hex.count % 2 == 0, "hex must be even-length: \(hex)")
        var data = Data(capacity: hex.count / 2)
        var idx = hex.startIndex
        while idx < hex.endIndex {
            let next = hex.index(idx, offsetBy: 2)
            data.append(UInt8(hex[idx..<next], radix: 16) ?? 0)
            idx = next
        }
        self = data
    }

    func hexEncodedString() -> String {
        map { String(format: "%02x", $0) }.joined()
    }
}
