// AUTO-GENERATED by scripts/gen_changelog.py -- DO NOT EDIT BY HAND.
// Regenerated on every release (see ios-release.ps1). Source of truth:
// real `git log` between adjacent version tags in THIS repo. See the
// header of gen_changelog.py for the exact derivation rule.
import Foundation

extension ReleaseNote {
    /// Auto-generated changelog entries, newest-first, derived from real
    /// git tag/commit history. Complements (does not replace) the
    /// hand-curated `releaseNotes` in WhatsNewData.swift.
    public static let generatedReleaseNotes: [ReleaseNote] = [
        .init(id: "v1.0.824",
              date: "2026-07-20",
              title: "v1.0.824",
              bullets: [
                "fix(call): callee-path telemetry wiring + speaker-route re-assertion (W-TELEMPARITY, W-CALLSPKR)",
              ]),
        .init(id: "v1.0.823",
              date: "2026-07-20",
              title: "v1.0.823",
              bullets: [
                "chore: regenerate changelog for v1.0.823",
                "fix(groupcall): self video in unified grid, self-vs-remote e2ee guard (W-GRPSELFGRID, W-GRPE2EESELF)",
              ]),
        .init(id: "v1.0.822",
              date: "2026-07-20",
              title: "v1.0.822",
              bullets: [
                "chore: regenerate changelog for v1.0.822",
                "feat(groupcall): signal AES-256 raw-key version-skew instead of silent decrypt failure (W-GRPVERSIONSKEW)",
              ]),
        .init(id: "v1.0.821",
              date: "2026-07-20",
              title: "v1.0.821",
              bullets: [
                "chore: regenerate changelog for v1.0.821",
                "fix(groupcall,ui): reconcile SFU roster with WS roster, close CallKit-title UUID gap (W-GRPSFUGHOST, W-GRPTITLE-UUIDGAP)",
              ]),
        .init(id: "v1.0.820",
              date: "2026-07-20",
              title: "v1.0.820",
              bullets: [
                "chore: regenerate changelog for v1.0.820",
                "feat(groupcall,ui): ctrl-recipe parity, rejoin on reconnect, extension-first names (W-GRPCTRL-PARITY, W-GRPREJOIN, W-EXTCHAIN)",
              ]),
        .init(id: "v1.0.819",
              date: "2026-07-20",
              title: "v1.0.819",
              bullets: [
                "chore: regenerate changelog for v1.0.819",
                "fix(ui): resolve PERSISTED UUID-shaped conversation titles at render (W-UUIDSWEEP-2)",
              ]),
        .init(id: "v1.0.818",
              date: "2026-07-20",
              title: "v1.0.818",
              bullets: [
                "chore: regenerate changelog for v1.0.818",
                "fix(ui): never show raw UUIDs anywhere — central DisplayName resolver + sweep (W-UUIDSWEEP)",
              ]),
        .init(id: "v1.0.817",
              date: "2026-07-20",
              title: "v1.0.817",
              bullets: [
                "chore: regenerate changelog for v1.0.817",
                "fix(groupcall): iPhone control-bar overflow, earpiece-routed audio, simulcast stats, hang-up ends call for all",
              ]),
        .init(id: "v1.0.816",
              date: "2026-07-20",
              title: "v1.0.816",
              bullets: [
                "chore: regenerate changelog for v1.0.816",
                "fix(build): align LiveKitBroadcast pin with the 2.13.1-aes256-raw fork tag",
              ]),
        .init(id: "v1.0.815",
              date: "2026-07-20",
              title: "v1.0.815",
              bullets: [
                "chore: regenerate changelog for v1.0.815",
                "feat(groupcall): true AES-256-GCM frame crypto — raw 32-byte SK_0 via fork overload (flag-day)",
                "chore: regenerate changelog for v1.0.814",
              ]),
        .init(id: "v1.0.814",
              date: "2026-07-19",
              title: "v1.0.814",
              bullets: [
                "fix(groupcall): late joiner stuck with zero participants after socket rebuild",
              ]),
        .init(id: "v1.0.813",
              date: "2026-07-19",
              title: "v1.0.813",
              bullets: [
                "chore: regenerate changelog for v1.0.813",
                "fix(groupcall): ship ctrl envelopes as raw JSON opaque payload",
              ]),
        .init(id: "v1.0.812",
              date: "2026-07-19",
              title: "v1.0.812",
              bullets: [
                "chore: regenerate changelog for v1.0.812",
                "fix(groupchat): stale group metadata never re-seals after member rekey",
              ]),
        .init(id: "v1.0.811",
              date: "2026-07-19",
              title: "v1.0.811",
              bullets: [
                "chore: regenerate changelog for v1.0.811",
                "fix(groupcall): VP-IO engine race crash, key-pin video-zero, track/tile race, stuck join",
              ]),
        .init(id: "v1.0.810",
              date: "2026-07-19",
              title: "v1.0.810",
              bullets: [
                "chore: regenerate changelog for v1.0.810",
                "fix(call): catch the ObjC NSException from setVoiceProcessingEnabled",
              ]),
        .init(id: "v1.0.809",
              date: "2026-07-19",
              title: "v1.0.809",
              bullets: [
                "chore: regenerate changelog for v1.0.809",
                "fix(call): stop group-call VP-IO SIGABRT at the AudioCapture funnel",
              ]),
        .init(id: "v1.0.808",
              date: "2026-07-19",
              title: "v1.0.808",
              bullets: [
                "chore: regenerate changelog for v1.0.808",
                "fix(groupcall): disable audio RED under E2EE — group-call voice was silent",
              ]),
        .init(id: "v1.0.807",
              date: "2026-07-18",
              title: "v1.0.807",
              bullets: [
                "chore: regenerate changelog for v1.0.807",
                "fix(calls): defense-in-depth guard — never start 1:1 audio engine during a group call",
              ]),
        .init(id: "v1.0.806",
              date: "2026-07-17",
              title: "v1.0.806",
              bullets: [
                "chore: regenerate changelog for v1.0.806",
                "fix(groupcall): add real resolution/fps/codec to group-call video telemetry",
              ]),
        .init(id: "v1.0.805",
              date: "2026-07-17",
              title: "v1.0.805",
              bullets: [
                "chore: regenerate changelog for v1.0.805",
                "fix(groupcall): port sender_key_nack + fix group-call telemetry key names",
              ]),
    ]
}
