// AUTO-GENERATED by scripts/gen_changelog.py -- DO NOT EDIT BY HAND.
// Regenerated on every release (see ios-release.ps1). Source of truth:
// real `git log` between adjacent version tags in THIS repo. See the
// header of gen_changelog.py for the exact derivation rule.
import Foundation

extension ReleaseNote {
    /// Auto-generated changelog entries, newest-first, derived from real
    /// git tag/commit history. Complements (does not replace) the
    /// hand-curated `releaseNotes` in WhatsNewData.swift.
    public static let generatedReleaseNotes: [ReleaseNote] = [
        .init(id: "v1.0.881",
              date: "2026-07-28",
              title: "v1.0.881",
              bullets: [
                "fix(ci): silence two build warnings (Sendable restate, dead try?)",
                "chore(engine): fix SwiftLint identifier_name/colon findings in Audio/",
                "chore(engine): document + suppress known-safe force-unwraps in OpusCodec",
              ]),
        .init(id: "v1.0.880",
              date: "2026-07-28",
              title: "v1.0.880",
              bullets: [
                "chore: regenerate changelog for v1.0.880",
                "fix(calling): don't kill camera/track on glare rollback before accepting peer's video upgrade",
                "chore(engine): bump GRDB 6.29.3 -> 7.11.0 now that CI runs Xcode 26.6",
                "fix(ci): update ios-simulator-tests destination for Xcode 26 device list",
                "chore(ci): upgrade every Xcode pin to 26.x, not just the release pipeline",
                "fix(livekit): qualify ConnectionState so RoomDelegate telemetry actually fires",
              ]),
        .init(id: "v1.0.879",
              date: "2026-07-28",
              title: "v1.0.879",
              bullets: [
                "chore: regenerate changelog for v1.0.879",
                "fix(build): drop read-only direction clamp on existing RTCRtpTransceiver",
              ]),
        .init(id: "v1.0.878",
              date: "2026-07-28",
              title: "v1.0.878",
              bullets: [
                "chore: regenerate changelog for v1.0.878",
                "fix(video): reuse the pre-allocated video transceiver in upgradeToVideo()",
                "chore(engine): stop suppressing all C warnings in CLiboqs",
                "chore(ci): remove masked-failure macOS test job from engine-tests.yml",
                "chore(ci): report-only lint/secret/RealityCore checks, drop orphaned zips",
              ]),
        .init(id: "v1.0.877",
              date: "2026-07-28",
              title: "v1.0.877",
              bullets: [
                "chore: regenerate changelog for v1.0.877",
                "fix(video): rebind sender/receiver cryptor after fresh-PC upgrade negotiation",
              ]),
        .init(id: "v1.0.876",
              date: "2026-07-28",
              title: "v1.0.876",
              bullets: [
                "chore: regenerate changelog for v1.0.876",
                "fix(build): drop MainActor-isolated sourceMode from nonisolated log line",
              ]),
        .init(id: "v1.0.875",
              date: "2026-07-28",
              title: "v1.0.875",
              bullets: [
                "chore: regenerate changelog for v1.0.875",
                "diag(video): throttled capture-pipeline + WebRTC-bridge frame logging",
              ]),
        .init(id: "v1.0.874",
              date: "2026-07-28",
              title: "v1.0.874",
              bullets: [
                "chore: regenerate changelog for v1.0.874",
                "fix(build): cast webRtcController before identity comparison",
              ]),
        .init(id: "v1.0.873",
              date: "2026-07-28",
              title: "v1.0.873",
              bullets: [
                "chore: regenerate changelog for v1.0.873",
                "fix(call): watchdog timeout for on-demand video-upgrade PeerConnection ICE",
              ]),
        .init(id: "v1.0.872",
              date: "2026-07-27",
              title: "v1.0.872",
              bullets: [
                "chore: regenerate changelog for v1.0.872",
                "feat(call): force CXCallUpdate.hasVideo=true for group calls too",
              ]),
        .init(id: "v1.0.871",
              date: "2026-07-27",
              title: "v1.0.871",
              bullets: [
                "chore: regenerate changelog for v1.0.871",
                "feat(call): force CXCallUpdate.hasVideo=true on all 1:1 incoming calls",
              ]),
        .init(id: "v1.0.870",
              date: "2026-07-27",
              title: "v1.0.870",
              bullets: [
                "chore: regenerate changelog for v1.0.870",
                "fix(call): 1:1 ring screen unreachable, GroupCallView always won (CRITICAL)",
              ]),
        .init(id: "v1.0.869",
              date: "2026-07-27",
              title: "v1.0.869",
              bullets: [
                "chore: regenerate changelog for v1.0.869",
                "fix(call): group-call accept silently no-ops after CallKit UI release (CRITICAL regression)",
              ]),
        .init(id: "v1.0.868",
              date: "2026-07-27",
              title: "v1.0.868",
              bullets: [
                "chore: regenerate changelog for v1.0.868",
                "fix(groupcall): disable adaptiveStream/dynacast — zero video for whole call (W-GRPADAPTIVEDEADLOCK)",
              ]),
        .init(id: "v1.0.867",
              date: "2026-07-27",
              title: "v1.0.867",
              bullets: [
                "chore: regenerate changelog for v1.0.867",
                "fix(call): release native CallKit banner over foreground group-call ring (W-GRPDOUBLEDIALER)",
              ]),
        .init(id: "v1.0.866",
              date: "2026-07-27",
              title: "v1.0.866",
              bullets: [
                "chore: regenerate changelog for v1.0.866",
                "feat(call): proximity screen/touch-off for 1:1 calls (W-EARTOUCH)",
              ]),
        .init(id: "v1.0.865",
              date: "2026-07-27",
              title: "v1.0.865",
              bullets: [
                "chore: regenerate changelog for v1.0.865",
                "diag(call): instrument the answer→foreground→app-lock chain (W-CALLFG-DIAG)",
              ]),
        .init(id: "v1.0.864",
              date: "2026-07-27",
              title: "v1.0.864",
              bullets: [
                "chore: regenerate changelog for v1.0.864",
                "feat(call): show the rich IncomingCallScreen for 1:1 calls too (W-1TO1RING)",
              ]),
        .init(id: "v1.0.863",
              date: "2026-07-27",
              title: "v1.0.863",
              bullets: [
                "chore: regenerate changelog for v1.0.863",
                "fix(bugreport): port iOS bug reports to the E2EE ticketing pipeline",
              ]),
        .init(id: "v1.0.862",
              date: "2026-07-27",
              title: "v1.0.862",
              bullets: [
                "chore: regenerate changelog for v1.0.862",
                "fix(group-call): await previous SFU room disconnect before rejoining",
              ]),
    ]
}
