// AUTO-GENERATED by scripts/gen_changelog.py -- DO NOT EDIT BY HAND.
// Regenerated on every release (see ios-release.ps1). Source of truth:
// real `git log` between adjacent version tags in THIS repo. See the
// header of gen_changelog.py for the exact derivation rule.
import Foundation

extension ReleaseNote {
    /// Auto-generated changelog entries, newest-first, derived from real
    /// git tag/commit history. Complements (does not replace) the
    /// hand-curated `releaseNotes` in WhatsNewData.swift.
    public static let generatedReleaseNotes: [ReleaseNote] = [
        .init(id: "v1.0.1056",
              date: "2026-08-30",
              title: "v1.0.1056",
              bullets: [
                "fix(call): W-DEADTXNET sentinel sample is Int64 — 1055 CI compile error",
              ]),
        .init(id: "v1.0.1055",
              date: "2026-08-30",
              title: "v1.0.1055",
              bullets: [
                "chore: regenerate changelog for v1.0.1055",
                "fix(call): manual-audio was armed without the CallKit activation relay — audio unit never started (W-ADMACTIVATE, W-DEADTXNET)",
              ]),
        .init(id: "v1.0.1054",
              date: "2026-08-30",
              title: "v1.0.1054",
              bullets: [
                "chore: regenerate changelog for v1.0.1054",
                "fix(call): responder asks the initiator to restart ICE instead of offering into a peer that discards it (W-RESPONDERREQFIRST)",
              ]),
        .init(id: "v1.0.1053",
              date: "2026-08-30",
              title: "v1.0.1053",
              bullets: [
                "chore: regenerate changelog for v1.0.1053",
                "fix(call): three-way silent-call teardown — pre-attached mic track, manual WebRTC audio unit, key-forward hardening (W-PREATTACHMIC, W-ADMMANUAL, W-CTRLBUILDDIAG)",
              ]),
        .init(id: "v1.0.1052",
              date: "2026-08-30",
              title: "v1.0.1052",
              bullets: [
                "chore: regenerate changelog for v1.0.1052",
                "diag(call): make activateNativeAudioSrtp's decisions remote-visible (W-AUDIOSENDDIAG)",
              ]),
        .init(id: "v1.0.1051",
              date: "2026-08-30",
              title: "v1.0.1051",
              bullets: [
                "chore: regenerate changelog for v1.0.1051",
                "fix(call): callee mic track landed on a transceiver libwebrtc never sends for (W-AUDIOSENDPICK)",
                "fix(net): dual-family STUN probe and an IPv6 call-media punch-hole (W-STUNDUALSTACK, W-VPNV6PUNCH)",
              ]),
        .init(id: "v1.0.1050",
              date: "2026-08-30",
              title: "v1.0.1050",
              bullets: [
                "chore: regenerate changelog for v1.0.1050",
                "diag(call): remote heartbeat for native audio RTP — the silent-call blind spot (W-SRTPRXDIAG)",
              ]),
        .init(id: "v1.0.1049",
              date: "2026-08-30",
              title: "v1.0.1049",
              bullets: [
                "chore: regenerate changelog for v1.0.1049",
                "fix(call): audio TX kept writing into an ICE-dead DataChannel for the whole outage (W-DCTXICEGATE +3)",
                "feat(call): detect mid-call speaker change from the call's own audio (SPKCHG)",
              ]),
        .init(id: "v1.0.1048",
              date: "2026-08-29",
              title: "v1.0.1048",
              bullets: [
                "chore: regenerate changelog for v1.0.1048",
                "fix(logs): turning the diagnostics toggle ON never started the log pump (W-CONSENTLATESTART)",
              ]),
        .init(id: "v1.0.1047",
              date: "2026-08-29",
              title: "v1.0.1047",
              bullets: [
                "chore: regenerate changelog for v1.0.1047",
                "fix(call): align the last legacy-path readouts to the native SRTP counters (W-SRTPCOUNTERS)",
                "fix(call): codec and throughput read dead counters on an SRTP call, and confidence was averaging silence (W-SRTPWIREMETRICS, W-VOICEMEANVOICED)",
                "refactor(engine): scoped locking in async contexts, clearing the Swift 6 hard errors (W-ASYNCLOCK)",
              ]),
        .init(id: "v1.0.1046",
              date: "2026-08-29",
              title: "v1.0.1046",
              bullets: [
                "chore: regenerate changelog for v1.0.1046",
                "fix(diagnostics): back off livelog upload on HTTP 429/5xx instead of hammering every 3s",
                "fix(call): iOS never answered a peer's ICE-restart request, so every iOS<->Android handoff died (W-RESTARTICEREQ)",
              ]),
        .init(id: "v1.0.1045",
              date: "2026-08-29",
              title: "v1.0.1045",
              bullets: [
                "chore: regenerate changelog for v1.0.1045",
                "feat(call): average the live voice metrics over one second so they can be read (W-VOICEUISMOOTH)",
                "a11y(security-icon): expand tap target on SecurityIconHeaderView, add VoiceOver traits",
                "fix(call): iOS killed every audio-srtp call at 90s with \"media-lost\" while audio worked (W-MEDIADEADSRTP)",
              ]),
        .init(id: "v1.0.1044",
              date: "2026-08-29",
              title: "v1.0.1044",
              bullets: [
                "chore: regenerate changelog for v1.0.1044",
                "fix(logs): iOS remote-log pipeline died on the first expired token and never recovered (W-TUSAUTHREFRESH)",
                "fix(call): iOS voice curve and liveness analysis saw zero audio for the whole call (W-AUDIORXTAPCARRYOVER)",
              ]),
        .init(id: "v1.0.1043",
              date: "2026-08-29",
              title: "v1.0.1043",
              bullets: [
                "chore: regenerate changelog for v1.0.1043",
                "fix(call): PQC session key could never reach the WebRTC controller on an iOS<->iOS call (W-SRTPKEYFWDRACE)",
              ]),
        .init(id: "v1.0.1042",
              date: "2026-08-28",
              title: "v1.0.1042",
              bullets: [
                "chore: regenerate changelog for v1.0.1042",
                "fix(call): audio-srtp receiver cryptor bound before negotiation completed, same class as the 2026-07-05 video decode fix (W-AUDIORXPOSTNEG)",
                "fix(call): audio-srtp sender used a stale pre-created transceiver after JSEP rewire (W-AUDIOSRTPSENDERCARRYOVER)",
                "🎨 Palette: Add accessibility attributes to CircularAction (#96)",
              ]),
        .init(id: "v1.0.1041",
              date: "2026-08-27",
              title: "v1.0.1041",
              bullets: [
                "chore: regenerate changelog for v1.0.1041",
                "fix(call): rewire group-call fallback audio to sender-key-derived W-GRPAUDIOKEY",
              ]),
        .init(id: "v1.0.1040",
              date: "2026-08-27",
              title: "v1.0.1040",
              bullets: [
                "chore: regenerate changelog for v1.0.1040",
                "feat(call): group-call SFU-outage fallback audio, receive-side (QUAD AUDIO_DATA)",
                "fix(test): update AudioProfileTests literals for the 40kbps standard-block rate",
                "fix(call): raise Opus preferred bitrate 32->40 kbps within existing block headroom",
                "fix(call): BWE-composed video ceiling + mid-call SFU disconnect fallback (P3 batch)",
              ]),
        .init(id: "v1.0.1039",
              date: "2026-08-27",
              title: "v1.0.1039",
              bullets: [
                "chore: regenerate changelog for v1.0.1039",
                "fix(call): video WS-relay gate must confirm real cryptor attach, not just ICE (W-VIDEOSENDHEALTH)",
                "fix(call): group video publish forces VP8 simulcast, unconditionally",
              ]),
        .init(id: "v1.0.1038",
              date: "2026-08-27",
              title: "v1.0.1038",
              bullets: [
                "chore: regenerate changelog for v1.0.1038",
                "fix(call): fail-closed native-audio-srtp sender attach + bounded retry (W-AUDIOSENDERGATE)",
              ]),
        .init(id: "v1.0.1037",
              date: "2026-08-27",
              title: "v1.0.1037",
              bullets: [
                "chore: regenerate changelog for v1.0.1037",
                "fix(call): restore nonisolated on ScreenShareController.onFrame after lock refactor",
                "fix(voice-analysis): gate VoiceAnalysisEngine on a 100ms time budget, not frame count",
              ]),
    ]
}
