import XCTest
import CryptoKit
@testable import QAudionEngine

// The Decodable structs below mirror the keys of the shared KAT file verbatim (snake_case, no CodingKeys):
// renaming would silently break decoding against the cross-platform fixture.
// swiftlint:disable identifier_name

/// A value of `constants` in the KAT: an integer, a string or a list of those (lists nest: the excerpt ranges are lists of pairs).
indirect enum ReplyKatValue: Decodable, Equatable {
    case int(Int64)
    case text(String)
    case list([ReplyKatValue])

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let number = try? container.decode(Int64.self) {
            self = .int(number)
        } else if let text = try? container.decode(String.self) {
            self = .text(text)
        } else {
            self = .list(try container.decode([ReplyKatValue].self))
        }
    }

    var texts: [String]? {
        guard case .list(let items) = self else { return nil }
        var out: [String] = []
        for item in items {
            guard case .text(let value) = item else { return nil }
            out.append(value)
        }
        return out
    }
}

/// `test/kat/reply_v1/reply-kat.json`, generated by the server repository's `tools/katgen/reply` (Go standard library only).
struct ReplyKat: Decodable {
    struct Normalized: Decodable {
        let to: String, k: String, q: String, b: String, q_display: String
    }
    /// A chat BODY judged by the receiver (`recognition`) or a reply text straight to the validator (`rules`, with a `topic`).
    /// `expect` is `text`, `reply` or `fallback`; a body is `serialized` (text) or `serialized_b64` (its bytes), exactly one.
    struct BodyVector: Decodable {
        let name: String, rule: String, context: String, expect: String, why: String
        let topic: String?
        let code: String?
        let serialized: String?
        let serialized_b64: String?
        let normalized: Normalized?
    }
    struct ExcerptVector: Decodable {
        let name: String, expected: String, why: String
        let expected_scalars: Int
        let input: String?
        let input_utf16: [UInt16]?
    }
    struct BuilderInput: Decodable {
        let to: String, k: String
        let q_source: String?
        let q_source_utf16: [UInt16]?
        let quoted_ephemeral: Bool?
        let b: String?
        let b_utf16: [UInt16]?
    }
    struct BuilderVector: Decodable {
        let name: String, why: String
        let input: BuilderInput
        let expected: String?
        let refuse: String?
    }
    struct Row: Decodable {
        let id: String, conversation: String, kind: String, text: String, author: String
        let view_once: Bool?
        let gone: Bool?
    }
    struct Expected: Decodable {
        let source: String
        let link: String?
        let author: String?
        let excerpt: String
    }
    struct ResolutionVector: Decodable {
        let name: String, why: String, serialized: String
        let rows: [Row]
        let expected: Expected
    }

    let format: String
    let version: Int
    let note: String
    let constants: [String: ReplyKatValue]
    let recognition: [BodyVector]
    let rules: [BodyVector]
    let excerpt_cases: [ExcerptVector]
    let builder_cases: [BuilderVector]
    let resolution_cases: [ResolutionVector]
    let fallback_codes: [String]
}

/// Runs EVERY vector of `reply-kat.json` (WIRE_SPEC section 13.8) against the Swift implementation of message replies:
/// recognition and versions, every member and type, the JSON profile (size at 8191, 8192 and 8193 bytes, duplicate names, depth,
/// surrogates, invalid UTF-8), EXCERPT, the canonical builder with its refusals, and the resolution of `to`. The counts are
/// pinned and nothing skips: a vector can never be dropped or filtered out without a failure here. The vector file is generated by an
/// independent Go implementation; its SHA-256 is pinned below, so the copy in this repository can never drift from the server's.
///
/// Texts are compared as bytes: Swift compares `String`s by canonical equivalence, which would make a precomposed and a decomposed
/// letter, or the Kelvin sign and `K`, "equal".
///
/// This code was written on a machine that cannot compile Swift: the macOS CI job is the only thing that has run it.
final class MessageReplyKatTests: XCTestCase {

    static let pinnedSHA256 = "59abb544efa5bedc20ddba6831a1af2ce48c91822643f9f370e289bbbe25606f"
    static let pinnedLength = 140_608

    // MARK: The file

    private func katBytes() throws -> Data {
        let candidates: [URL?] = [
            Bundle.module.url(forResource: "reply-kat", withExtension: "json"),
            Bundle.module.url(forResource: "reply-kat", withExtension: "json", subdirectory: "kat"),
            Bundle.module.url(forResource: "reply-kat", withExtension: "json", subdirectory: "Resources/kat")
        ]
        guard let url = candidates.compactMap({ $0 }).first else {
            throw NSError(domain: "MessageReplyKatTests", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "reply-kat.json is not in the test bundle"])
        }
        return try Data(contentsOf: url)
    }

    private func loadKat() throws -> ReplyKat {
        try JSONDecoder().decode(ReplyKat.self, from: try katBytes())
    }

    private func utf8(_ text: String) -> [UInt8] { Array(text.utf8) }

    private func utf8(_ text: String?) -> [UInt8]? { text.map { Array($0.utf8) } }

    private func sha256Hex(_ data: Data) -> String {
        Data(SHA256.hash(data: data)).map { String(format: "%02x", $0) }.joined()
    }

    /// The BYTES of a body vector: `serialized` as the UTF-8 of the text, or `serialized_b64` decoded; exactly one is present.
    private func bodyBytes(_ vector: ReplyKat.BodyVector) throws -> Data {
        switch (vector.serialized, vector.serialized_b64) {
        case (let text?, nil):
            return Data(text.utf8)
        case (nil, let encoded?):
            return try XCTUnwrap(Data(base64Encoded: encoded), "bad base64 in \(vector.name)")
        default:
            XCTFail("exactly one of serialized and serialized_b64 in \(vector.name)")
            return Data()
        }
    }

    func testKatFileIsAByteIdenticalCopyOfTheServerFile() throws {
        let bytes = try katBytes()
        XCTAssertEqual(bytes.count, Self.pinnedLength, "length of reply-kat.json changed")
        XCTAssertEqual(sha256Hex(bytes), Self.pinnedSHA256, "reply-kat.json is not the pinned byte-for-byte copy of the server file")
        XCTAssertFalse(bytes.contains(0x0D), "a CR in the vector file: line endings were rewritten (.gitattributes -text)")
    }

    /// The counts are asserted so a vector can never be dropped or filtered out without a failure here.
    func testKatCoversEverythingTheTestsExercise() throws {
        let kat = try loadKat()
        XCTAssertEqual(kat.format, "qaudion-reply-kat")
        XCTAssertEqual(kat.version, 1)
        XCTAssertEqual(kat.constants.count, 13)
        XCTAssertEqual(kat.recognition.count, 25)
        XCTAssertEqual(kat.recognition.filter { $0.expect == "text" }.count, 10)
        XCTAssertEqual(kat.recognition.filter { $0.expect == "reply" }.count, 2)
        XCTAssertEqual(kat.recognition.filter { $0.expect == "fallback" }.count, 13)
        XCTAssertEqual(kat.rules.count, 74)
        XCTAssertEqual(kat.rules.filter { $0.expect == "reply" }.count, 26)
        XCTAssertEqual(kat.rules.filter { $0.expect == "fallback" }.count, 48)
        XCTAssertEqual(kat.excerpt_cases.count, 25)
        XCTAssertEqual(kat.excerpt_cases.filter { $0.input_utf16 != nil }.count, 3)
        XCTAssertEqual(kat.builder_cases.count, 26)
        XCTAssertEqual(kat.builder_cases.filter { $0.refuse != nil }.count, 8)
        XCTAssertEqual(kat.resolution_cases.count, 13)
        XCTAssertEqual(kat.fallback_codes, ["bad_reply", "unsupported_version"])
        // Every code of a rejected body is one of the two of the file.
        for vector in kat.recognition + kat.rules where vector.expect == "fallback" {
            XCTAssertTrue(kat.fallback_codes.contains(vector.code ?? ""), "unknown code in \(vector.name)")
        }
    }

    // MARK: constants

    func testConstantsMatchTheLibrary() throws {
        let constants = try loadKat().constants
        func integer(_ key: String) -> Int64? {
            if case .int(let value)? = constants[key] { return value }
            return nil
        }
        func text(_ key: String) -> String? {
            if case .text(let value)? = constants[key] { return value }
            return nil
        }
        XCTAssertEqual(integer("VERSION"), MessageReplyCodec.version)
        XCTAssertEqual(integer("REPLY_MAX_BYTES"), Int64(MessageReplyCodec.maxBytes))
        XCTAssertEqual(integer("REPLY_MAX_DEPTH"), Int64(MessageReplyCodec.maxDepth))
        XCTAssertEqual(integer("REPLY_MAX_DEPTH"), Int64(FileV2.maxDescriptorDepth))
        XCTAssertEqual(integer("REPLY_MAX_BYTES"), Int64(FileV2.maxDescriptorBytes))
        XCTAssertEqual(integer("Q_MAX_SCALARS"), Int64(MessageReplyCodec.qMaxScalars))
        XCTAssertEqual(integer("TO_LEN"), Int64(MessageReplyCodec.idLength))
        XCTAssertEqual(integer("MAX_JSON_INT"), FileV2.maxJSONInteger)
        XCTAssertEqual(utf8(text("PREFIX")), MessageReplyCodec.prefix)
        XCTAssertEqual(constants["KINDS"]?.texts, MessageReplyKind.allCases.map { $0.rawValue })
        XCTAssertEqual(constants["MEMBER_ORDER"]?.texts, ["qa_reply", "to", "k", "q", "b"])
        let prefixes: [String] = MessageReplyCodec.reservedPrefixes.map { String(decoding: $0, as: UTF8.self) }
        XCTAssertEqual(constants["RECOGNISED_PREFIXES"]?.texts, prefixes)

        // The ranges of EXCERPT, as inclusive pairs of "U+XXXX".
        func ranges(_ key: String) -> [ClosedRange<UInt32>]? {
            guard case .list(let pairs)? = constants[key] else { return nil }
            var out: [ClosedRange<UInt32>] = []
            for pair in pairs {
                guard let ends = pair.texts, ends.count == 2,
                      let low = UInt32(ends[0].dropFirst(2), radix: 16),
                      let high = UInt32(ends[1].dropFirst(2), radix: 16), low <= high else { return nil }
                out.append(low...high)
            }
            return out
        }
        XCTAssertEqual(ranges("EXCERPT_REMOVED"), MessageReplyCodec.removedRanges)
        XCTAssertEqual(ranges("EXCERPT_SPACED"), MessageReplyCodec.spacedRanges)

        // The id pattern: the library's check and the regular expression of the vector file agree.
        let pattern = try XCTUnwrap(text("TO_PATTERN"))
        let expression = try NSRegularExpression(pattern: pattern)
        let samples = ["73740a4d-0d1e-4f08-9f38-5ba1b8fe4472", "00000000-0000-0000-0000-000000000000",
                       "73740A4D-0D1E-4F08-9F38-5BA1B8FE4472", "73740a4d0d1e4f089f385ba1b8fe4472",
                       "73740a4d-0d1e-4f08-9f38-5ba1b8fe447", "73740a4d-0d1e-4f08-9f38-5ba1b8fe44722",
                       "73740a4d-0d1e-4f08-9f38-5ba1b8fe447g", "73740a4d-0d1e4-f08-9f38-5ba1b8fe4472",
                       "", "../../etc/passwd"]
        for sample in samples {
            let range = NSRange(sample.startIndex..., in: sample)
            let byRegex: Bool = expression.firstMatch(in: sample, options: [], range: range) != nil
            XCTAssertEqual(MessageReplyCodec.isServerMessageId(sample), byRegex, "pattern and check disagree on \(sample)")
        }
    }

    // MARK: recognition and rules

    private func run(_ vector: ReplyKat.BodyVector) throws {
        let bytes = try bodyBytes(vector)
        let result = MessageReplyCodec.recognize(utf8: bytes)
        let label = vector.name
        switch vector.expect {
        case "text":
            XCTAssertEqual(result, .notReply, label)
        case "reply":
            guard case .reply(let reply) = result else {
                XCTFail("\(label): expected a reply, got \(result)")
                return
            }
            let normalized = try XCTUnwrap(vector.normalized, "\(label): a reply vector has its normalised form")
            XCTAssertEqual(utf8(reply.to), utf8(normalized.to), label)
            XCTAssertEqual(reply.kind.rawValue, normalized.k, label)
            XCTAssertEqual(utf8(reply.quote), utf8(normalized.q), label)
            XCTAssertEqual(utf8(reply.body), utf8(normalized.b), label)
            XCTAssertEqual(utf8(reply.displayedQuote), utf8(normalized.q_display), label)
            // The text the message shows is `b`, whatever it contains.
            if let text = vector.serialized {
                XCTAssertEqual(utf8(MessageReplyCodec.shownText(ofBody: text)), utf8(normalized.b), label)
            }
        case "fallback":
            guard case .rejected(let rejection) = result else {
                XCTFail("\(label): expected a rejection, got \(result)")
                return
            }
            XCTAssertEqual(rejection.rawValue, vector.code, label)
            // A rejected body is NOT lost: it is shown as the ordinary text it is.
            if let text = vector.serialized {
                XCTAssertEqual(utf8(MessageReplyCodec.shownText(ofBody: text)), utf8(text), label)
            }
        default:
            XCTFail("\(label): unknown expect \(vector.expect)")
        }
    }

    func testEveryRecognitionVector() throws {
        let vectors = try loadKat().recognition
        XCTAssertEqual(vectors.count, 25)
        for vector in vectors { try run(vector) }
    }

    func testEveryRulesVector() throws {
        let vectors = try loadKat().rules
        XCTAssertEqual(vectors.count, 74)
        for vector in vectors { try run(vector) }
    }

    // MARK: EXCERPT

    func testEveryExcerptVector() throws {
        let vectors = try loadKat().excerpt_cases
        XCTAssertEqual(vectors.count, 25)
        for vector in vectors {
            let input: String
            switch (vector.input, vector.input_utf16) {
            case (let text?, nil):
                input = text
            case (nil, let units?):
                // A UTF-16 platform first replaces every unpaired surrogate with U+FFFD: decoding does exactly that.
                input = String(decoding: units, as: UTF16.self)
            default:
                XCTFail("exactly one of input and input_utf16 in \(vector.name)")
                continue
            }
            let output = MessageReplyCodec.excerpt(input)
            XCTAssertEqual(utf8(output), utf8(vector.expected), vector.name)
            XCTAssertEqual(output.unicodeScalars.count, vector.expected_scalars, vector.name)
            // EXCERPT is idempotent: a q a conforming builder wrote is displayed byte for byte.
            XCTAssertEqual(utf8(MessageReplyCodec.excerpt(output)), utf8(output), vector.name)
        }
    }

    // MARK: builder

    func testEveryBuilderVector() throws {
        let vectors = try loadKat().builder_cases
        XCTAssertEqual(vectors.count, 26)
        for vector in vectors {
            let input = vector.input
            var body: String = ""
            if let text = input.b {
                body = text
            } else if let units = input.b_utf16 {
                body = String(decoding: units, as: UTF16.self)
            }
            var source: String? = input.q_source
            if source == nil, let units = input.q_source_utf16 {
                source = String(decoding: units, as: UTF16.self)
            }
            let result = MessageReplyCodec.build(to: input.to, kind: input.k, quoteSource: source,
                                                 quotedIsEphemeral: input.quoted_ephemeral ?? false, body: body)
            switch (vector.expected, vector.refuse) {
            case (let expected?, nil):
                guard case .success(let text) = result else {
                    XCTFail("\(vector.name): the builder refused: \(result)")
                    continue
                }
                XCTAssertEqual(utf8(text), utf8(expected), vector.name)
                XCTAssertLessThan(text.utf8.count, 8192, vector.name)
                // What the builder writes is accepted by the receiver, with `b` unchanged.
                guard case .reply(let reply) = MessageReplyCodec.recognize(utf8: Data(text.utf8)) else {
                    XCTFail("\(vector.name): the receiver does not accept the builder's text")
                    continue
                }
                XCTAssertEqual(utf8(reply.body), utf8(body), vector.name)
                XCTAssertEqual(utf8(reply.to), utf8(input.to), vector.name)
            case (nil, let reason?):
                let refusal = try XCTUnwrap(MessageReplyRefusal(rawValue: reason), "\(vector.name): unknown reason")
                XCTAssertEqual(result, .failure(refusal), vector.name)
            default:
                XCTFail("exactly one of expected and refuse in \(vector.name)")
            }
        }
    }

    // MARK: resolution

    func testEveryResolutionVector() throws {
        let vectors = try loadKat().resolution_cases
        XCTAssertEqual(vectors.count, 13)
        for vector in vectors {
            guard case .reply(let reply) = MessageReplyCodec.recognize(utf8: Data(vector.serialized.utf8)) else {
                XCTFail("\(vector.name): the reply of the vector is not a valid reply")
                continue
            }
            var rows: [MessageReplyRow] = []
            for row in vector.rows {
                let kind = try XCTUnwrap(MessageReplyKind(rawValue: row.kind), "\(vector.name): unknown kind")
                rows.append(MessageReplyRow(id: row.id, sameConversation: row.conversation == "same", kind: kind,
                                            text: row.text, author: row.author, viewOnce: row.view_once ?? false,
                                            gone: row.gone ?? false))
            }
            let block = MessageReplyCodec.resolve(reply, rows: rows)
            XCTAssertEqual(block.source.rawValue, vector.expected.source, vector.name)
            XCTAssertEqual(utf8(block.link), utf8(vector.expected.link), vector.name)
            XCTAssertEqual(utf8(block.author), utf8(vector.expected.author), vector.name)
            XCTAssertEqual(utf8(block.excerpt), utf8(vector.expected.excerpt), vector.name)
        }
    }
}
