import XCTest
import CryptoKit
@testable import QAudionEngine

/// Frame-crypto vectors shared by every client and by the native M150 build
/// (`Resources/group-calls-v2-frame-crypto.json`, version 2, generated by the desktop's byte-exact
/// frame cryptor with `node:crypto` only, with synthetic keys). They cover group calls v2 AND 1:1
/// calls (WIRE_SPEC §11).
///
/// What is pinned on iOS, through the test-target-only reference in `FrameCryptoKatReference.swift`
/// (the real transformer is the native one in the WebRTC binary):
///  * the key derivation `aes_key = HKDF-SHA256(ikm = K[M,E], salt = empty, info = 128 x 0x00,
///    L = 32)` (the same one the native FrameCryptor runs),
///  * the frame wire layout `header(unencrypted_bytes) || ciphertext || tag(16) || iv(12) ||
///    [12, keyIndex]` with AAD = header, and the v2 IV `ssrc || ts || ((ts - counter) mod 2^32)`
///    with a FULL uint32 counter (`counterCases[]`, including the old mod-0xFFFF boundary, a
///    wrapping `ts < counter` and an H.264 body whose IV contains `00 00 01`: the receiver parses
///    the trailer and IV AFTER unescaping),
///  * `keyIndex = epoch mod 16` and the ring semantics: the receiver installs `K[M,E]` at slot
///    `E mod 16` of M's own ring, a frame is looked up by the key index in its trailer, a slot
///    overwritten by a later epoch no longer opens the older epoch (`decrypt_failed`), an empty
///    slot is `missing_key`, and rings are per participant. The installs come from the real
///    `GroupE2eeCoordinator` (the code that feeds the native key provider),
///  * the P12 receiver anti-replay window (`replayScenarios[]`): W = 256 per ssrc, duplicates,
///    reordering at 255 / 256, jumps, simulcast ssrcs, key switches, slot-overwrite GC, the
///    reflection guard, "a failed AEAD or a missing key never commits" and the 64-stream cap.
final class GroupE2eeKatTests: XCTestCase {

    /// sha256 of `group-calls-v2-frame-crypto.json`: the file is byte-identical in every client
    /// repo and in the build repo, and this test refuses any other bytes.
    private static let pinnedSha256 = "4edfef48a51fe95986e0f9f3f6568be651e45e79ff6dbab88bec48caa9ff9b38"

    // MARK: - Vector file

    private struct Sender {
        let name: String
        let participantId: String
        var user: String { "user-" + name.lowercased() }
    }

    private struct KatCase {
        let id: String
        let sender: String
        let participantId: String
        let epoch: UInt32
        let keyIndex: Int
        let key: Data
        let aesKey: Data
        let frame: String
        let codec: String
        let isKeyFrame: Bool
        let ssrc: UInt32
        let rtpTimestamp: UInt32
        let counter: UInt32
        let iv: Data
        let unencryptedBytes: Int
        let plaintext: Data
        let wire: Data
        let wireUnescaped: Data?

        var refCodec: String { codec }
    }

    private struct Step {
        let install: [UInt32]
        let opens: [String]
        let refused: [(frame: String, reason: String)]
    }

    private struct Scenario {
        let name: String
        let participantId: String
        let steps: [Step]
    }

    private struct ReplayFrame {
        let id: String
        let codec: String
        let isKeyFrame: Bool
        let unencryptedBytes: Int
        let plaintext: Data
        let wire: Data
        let ssrc: UInt32
        let counter: UInt32
    }

    private struct ReplayStep {
        let participant: String
        let install: [(keyIndex: Int, key: Data)]
        let deliver: String?
        let expect: String?
    }

    private struct ReplayScenario {
        let name: String
        let localSendSsrcs: Set<UInt32>
        let steps: [ReplayStep]
    }

    private struct Vectors {
        let root: [String: Any]
        let senders: [Sender]
        let cases: [KatCase]
        let counterCases: [KatCase]
        let scenarios: [Scenario]
        let replayFrames: [String: ReplayFrame]
        let replayScenarios: [ReplayScenario]
    }

    private static func hex(_ text: String) -> Data {
        var out = Data()
        var index = text.startIndex
        while index < text.endIndex {
            let next = text.index(index, offsetBy: 2)
            out.append(UInt8(text[index..<next], radix: 16) ?? 0)
            index = next
        }
        return out
    }

    private static func number(_ value: Any?) -> UInt32 {
        return UInt32(truncating: value as? NSNumber ?? 0)
    }

    private func fileData() throws -> Data {
        guard let url = Bundle.module.url(forResource: "group-calls-v2-frame-crypto", withExtension: "json") else {
            XCTFail("group-calls-v2-frame-crypto.json not found in Bundle.module")
            throw NSError(domain: "kat", code: 1)
        }
        return try Data(contentsOf: url)
    }

    private static func parseCase(_ c: [String: Any]) -> KatCase {
        return KatCase(
            id: c["id"] as? String ?? "\(c["sender"] as? String ?? "")/\(c["epoch"] as? Int ?? 0)/\(c["frame"] as? String ?? "")",
            sender: c["sender"] as? String ?? "",
            participantId: c["participantId"] as? String ?? "",
            epoch: number(c["epoch"]),
            keyIndex: (c["keyIndex"] as? NSNumber)?.intValue ?? -1,
            key: hex(c["key"] as? String ?? ""),
            aesKey: hex(c["aesKey"] as? String ?? ""),
            frame: c["frame"] as? String ?? "",
            codec: c["codec"] as? String ?? "",
            isKeyFrame: (c["isKeyFrame"] as? NSNumber)?.boolValue ?? false,
            ssrc: number(c["ssrc"]),
            rtpTimestamp: number(c["rtpTimestamp"]),
            counter: number(c["counter"]),
            iv: hex(c["iv"] as? String ?? ""),
            unencryptedBytes: (c["unencryptedBytes"] as? NSNumber)?.intValue ?? -1,
            plaintext: hex(c["plaintext"] as? String ?? ""),
            wire: hex(c["wire"] as? String ?? ""),
            wireUnescaped: (c["wireUnescaped"] as? String).map { hex($0) })
    }

    private func load() throws -> Vectors {
        let object = try JSONSerialization.jsonObject(with: fileData())
        let root = try XCTUnwrap(object as? [String: Any])
        let senders = try XCTUnwrap(root["senders"] as? [[String: Any]]).map {
            Sender(name: $0["name"] as? String ?? "", participantId: $0["participantId"] as? String ?? "")
        }
        let cases = try XCTUnwrap(root["cases"] as? [[String: Any]]).map { Self.parseCase($0) }
        let counterCases = try XCTUnwrap(root["counterCases"] as? [[String: Any]]).map { Self.parseCase($0) }
        let scenarios = try XCTUnwrap(root["ringScenarios"] as? [[String: Any]]).map { s -> Scenario in
            let steps = (s["steps"] as? [[String: Any]] ?? []).map { step -> Step in
                Step(
                    install: (step["install"] as? [NSNumber] ?? []).map { UInt32(truncating: $0) },
                    opens: step["opens"] as? [String] ?? [],
                    refused: (step["refused"] as? [[String: String]] ?? []).map { (frame: $0["frame"] ?? "", reason: $0["reason"] ?? "") })
            }
            return Scenario(name: s["name"] as? String ?? "", participantId: s["participantId"] as? String ?? "", steps: steps)
        }
        var pool: [String: ReplayFrame] = [:]
        for f in try XCTUnwrap(root["replayFrames"] as? [[String: Any]]) {
            let id = f["id"] as? String ?? ""
            pool[id] = ReplayFrame(
                id: id, codec: f["codec"] as? String ?? "",
                isKeyFrame: (f["isKeyFrame"] as? NSNumber)?.boolValue ?? false,
                unencryptedBytes: (f["unencryptedBytes"] as? NSNumber)?.intValue ?? -1,
                plaintext: Self.hex(f["plaintext"] as? String ?? ""),
                wire: Self.hex(f["wire"] as? String ?? ""),
                ssrc: Self.number(f["ssrc"]), counter: Self.number(f["counter"]))
        }
        let replay = try XCTUnwrap(root["replayScenarios"] as? [[String: Any]]).map { s -> ReplayScenario in
            let steps = (s["steps"] as? [[String: Any]] ?? []).map { step -> ReplayStep in
                let installs = (step["install"] as? [[String: Any]] ?? []).map {
                    (keyIndex: ($0["keyIndex"] as? NSNumber)?.intValue ?? -1, key: Self.hex($0["key"] as? String ?? ""))
                }
                return ReplayStep(
                    participant: step["participant"] as? String ?? "",
                    install: installs, deliver: step["deliver"] as? String, expect: step["expect"] as? String)
            }
            return ReplayScenario(
                name: s["name"] as? String ?? "",
                localSendSsrcs: Set((s["localSendSsrcs"] as? [NSNumber] ?? []).map { UInt32(truncating: $0) }),
                steps: steps)
        }
        return Vectors(root: root, senders: senders, cases: cases, counterCases: counterCases, scenarios: scenarios,
                       replayFrames: pool, replayScenarios: replay)
    }

    // MARK: - The file is the pinned one and states the rule the code implements

    func testTheVectorFileIsTheOneEveryClientPins() throws {
        let digest = SHA256.hash(data: try fileData())
        let hexDigest = digest.map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(hexDigest, Self.pinnedSha256,
                       "group-calls-v2-frame-crypto.json must be byte-identical across the clients and the build repo")
    }

    func testTheVectorFileDeclaresTheRuleTheCodeImplements() throws {
        let v = try load()
        XCTAssertEqual(v.root["version"] as? Int, 2)
        XCTAssertEqual((v.root["keyRingSize"] as? NSNumber)?.uint32Value, GroupE2ee.keyRingSize)
        let hkdf = try XCTUnwrap(v.root["hkdf"] as? [String: Any])
        XCTAssertEqual(hkdf["hash"] as? String, "sha256")
        XCTAssertEqual(hkdf["salt"] as? String, "", "empty salt")
        XCTAssertEqual(Self.hex(hkdf["info"] as? String ?? "x"), Data(count: 128), "info = 128 x 0x00")
        XCTAssertEqual((hkdf["length"] as? NSNumber)?.intValue, GroupE2ee.keyLength)
        let unencrypted = try XCTUnwrap(v.root["unencryptedBytes"] as? [String: Int])
        XCTAssertEqual(unencrypted, ["opus": 1, "vp8-key": 10, "vp8-delta": 3, "h264-idr": 6])
        let rules = try XCTUnwrap(v.root["replayRules"] as? [String: Any])
        XCTAssertEqual((rules["window"] as? NSNumber)?.intValue, ReplayHandlerReference.windowSize)
        XCTAssertEqual((rules["maxStreamsPerParticipant"] as? NSNumber)?.intValue, ReplayHandlerReference.maxStreams)
        XCTAssertEqual(v.cases.count, 102, "2 senders x epochs 1..17 x (opus, vp8 key, vp8 delta)")
        XCTAssertEqual(Set(v.cases.map { $0.epoch }), Set(UInt32(1)...17))
        XCTAssertEqual(v.counterCases.count, 13)
        XCTAssertEqual(v.replayFrames.count, 90)
        XCTAssertEqual(v.replayScenarios.count, 13)
    }

    func testTheKeyIndexOfEveryCaseIsTheEpochModuloSixteenAndTheKeyIs32Bytes() throws {
        let v = try load()
        for c in v.cases {
            XCTAssertEqual(Int32(c.keyIndex), GroupE2ee.keyIndex(forEpoch: c.epoch), c.id)
            XCTAssertEqual(c.key.count, GroupE2ee.keyLength, c.id)
            XCTAssertEqual(c.wire.last, UInt8(c.keyIndex), "the trailer carries the key index: \(c.id)")
            XCTAssertEqual(c.wire[c.wire.count - 2], 12, "the trailer's first byte is the IV length: \(c.id)")
        }
        // The wrap: epoch 16 -> slot 0, epoch 17 -> slot 1.
        XCTAssertEqual(v.cases.first { $0.epoch == 16 }?.keyIndex, 0)
        XCTAssertEqual(v.cases.first { $0.epoch == 17 }?.keyIndex, 1)
    }

    // MARK: - HKDF

    func testEveryDerivedAesKeyMatches() throws {
        let v = try load()
        for c in v.cases + v.counterCases {
            let derived = FrameCryptoKatReference.aesKey(fromMaterial: c.key).withUnsafeBytes { Data($0) }
            XCTAssertEqual(derived, c.aesKey, "aes_key of \(c.id)")
        }
    }

    // MARK: - Wire layout and the v2 IV

    private func seal(_ c: KatCase) throws -> Data {
        return try FrameCryptoKatReference.seal(
            plaintext: c.plaintext, keyMaterial: c.key, keyIndex: UInt8(c.keyIndex), codec: c.refCodec,
            isKeyFrame: c.isKeyFrame, ssrc: c.ssrc, rtpTimestamp: c.rtpTimestamp, counter: c.counter)
    }

    func testEveryFrameIsReproducedByteForByte() throws {
        for c in try load().cases {
            XCTAssertEqual(
                FrameCryptoKatReference.unencryptedBytes(codec: c.refCodec, isKeyFrame: c.isKeyFrame, data: c.plaintext),
                c.unencryptedBytes, "unencrypted bytes of \(c.id)")
            XCTAssertEqual(c.counter, 0, "every cases[] frame is the first frame of its ssrc: \(c.id)")
            XCTAssertEqual(try seal(c), c.wire, "wire of \(c.id)")
            // header || ciphertext || tag || iv || trailer: the IV sits before the 2-byte trailer.
            XCTAssertEqual(Data(c.wire.suffix(14).prefix(12)), c.iv, "iv of \(c.id)")
            // The header stays in the clear (qjanus needs the codec bytes).
            XCTAssertEqual(Data(c.wire.prefix(c.unencryptedBytes)), Data(c.plaintext.prefix(c.unencryptedBytes)), c.id)
        }
    }

    func testTheV2IvFormulaAndEveryCounterCase() throws {
        let v = try load()
        // The counters of the file: 1, 2, the old mod-0xFFFF boundary, 2^31, 0xFFFFFFFE, 0xFFFFFFFF,
        // a timestamp BELOW the counter (the third word wraps), and an H.264 IV holding 00 00 01.
        XCTAssertEqual(Set(v.counterCases.map { $0.counter }).isSuperset(of: [1, 2, 65_534, 65_535, 65_536, 1 << 31, 0xFFFF_FFFE, 0xFFFF_FFFF]), true)
        XCTAssertTrue(v.counterCases.contains { $0.rtpTimestamp < $0.counter }, "a case with ts < counter (w3 wraps)")
        for c in v.counterCases {
            XCTAssertEqual(FrameCryptoKatReference.iv(ssrc: c.ssrc, rtpTimestamp: c.rtpTimestamp, counter: c.counter), c.iv,
                           "iv formula of \(c.id)")
            XCTAssertEqual(try seal(c), c.wire, "wire of \(c.id)")
            let parsed = try FrameCryptoKatReference.parse(
                wire: c.wire, codec: c.refCodec, isKeyFrame: c.isKeyFrame, headerLength: c.unencryptedBytes)
            XCTAssertEqual(parsed.counter, c.counter, "the receiver recovers the counter of \(c.id)")
            XCTAssertEqual(parsed.ivSsrc, c.ssrc, c.id)
            XCTAssertEqual(parsed.keyIndex, UInt8(c.keyIndex), c.id)
            XCTAssertEqual(try FrameCryptoKatReference.open(parsed, keyMaterial: c.key), c.plaintext, c.id)
        }
    }

    func testAnH264BodyWhoseIvContains000001IsParsedAfterUnescaping() throws {
        let c = try XCTUnwrap(try load().counterCases.first { $0.id == "ctr-h264-iv-000001" })
        let unescaped = try XCTUnwrap(c.wireUnescaped, "the case carries the unescaped body too")
        XCTAssertNotEqual(c.wire, unescaped, "the IV's 00 00 01 is escaped on the wire")
        // The escaped wire opens (parse after unescaping)...
        let parsed = try FrameCryptoKatReference.parse(
            wire: c.wire, codec: c.refCodec, isKeyFrame: c.isKeyFrame, headerLength: c.unencryptedBytes)
        XCTAssertEqual(parsed.iv, c.iv)
        XCTAssertEqual(try FrameCryptoKatReference.open(parsed, keyMaterial: c.key), c.plaintext)
        // ...and reading the IV from the ESCAPED tail (the upstream defect P12 fixes) would not.
        let shiftedIv = Data(c.wire.suffix(14).prefix(12))
        XCTAssertNotEqual(shiftedIv, c.iv, "the escaped tail's IV window is shifted by the inserted 0x03")
    }

    func testEveryWireOpensToItsPlaintextAndIsAuthenticated() throws {
        for c in try load().cases {
            func opens(_ wire: Data, key: Data) -> Data? {
                guard let parsed = try? FrameCryptoKatReference.parse(
                    wire: wire, codec: c.refCodec, isKeyFrame: c.isKeyFrame, headerLength: c.unencryptedBytes) else { return nil }
                return try? FrameCryptoKatReference.open(parsed, keyMaterial: key)
            }
            XCTAssertEqual(opens(c.wire, key: c.key), c.plaintext, c.id)

            var headerFlip = c.wire
            headerFlip[0] ^= 0x01
            XCTAssertNil(opens(headerFlip, key: c.key), "the header is the AAD: \(c.id)")

            var bodyFlip = c.wire
            bodyFlip[c.unencryptedBytes] ^= 0x01
            XCTAssertNil(opens(bodyFlip, key: c.key), "the ciphertext is authenticated: \(c.id)")

            var otherKey = c.key
            otherKey[0] ^= 0x01
            XCTAssertNil(opens(c.wire, key: otherKey), "another key never opens it: \(c.id)")
        }
    }

    // MARK: - Ring semantics, driven by the real coordinator

    private enum Outcome: String {
        case opens
        case missingKey = "missing_key"
        case decryptFailed = "decrypt_failed"
    }

    /// What the receiver does with `frame`: look the trailer's key index up in the ring of
    /// `participantId`, then try to open the frame with that slot's key. A fresh replay window
    /// per open (the file's `casesNote`): these sections re-open counter-0 frames.
    private func outcome(of frame: KatCase, ring: [Int32: Data]) -> Outcome {
        let slot = Int32(frame.wire.last ?? 0)
        guard let key = ring[slot] else { return .missingKey }
        guard let parsed = try? FrameCryptoKatReference.parse(
            wire: frame.wire, codec: frame.refCodec, isKeyFrame: frame.isKeyFrame, headerLength: frame.unencryptedBytes),
              (try? FrameCryptoKatReference.open(parsed, keyMaterial: key)) != nil else { return .decryptFailed }
        return .opens
    }

    func testTheRingScenariosAreReproducedByTheCoordinatorsInstallsAndTheFrameLookup() throws {
        let v = try load()
        XCTAssertEqual(v.scenarios.count, 3)
        let byId = Dictionary(uniqueKeysWithValues: v.cases.map { ($0.id, $0) })
        for scenario in v.scenarios {
            let env = FakeE2eeEnvironment()
            let coordinator = GroupE2eeCoordinator(callId: "kat-call", selfUserId: "user-self", environment: env)
            var pseudonyms = ["user-self": String(repeating: "ff", count: 16)]
            for sender in v.senders { pseudonyms[sender.user] = sender.participantId }
            coordinator.onRoster(epoch: 1, members: ["user-self"] + v.senders.map { $0.user }, pseudonyms: pseudonyms)
            let owner = try XCTUnwrap(v.senders.first { $0.participantId == scenario.participantId }, scenario.name)

            var rings: [String: [Int32: Data]] = [:]
            var applied = 0
            for (number, step) in scenario.steps.enumerated() {
                for epoch in step.install {
                    let source = try XCTUnwrap(v.cases.first { $0.participantId == scenario.participantId && $0.epoch == epoch },
                                               "\(scenario.name): no vector for epoch \(epoch)")
                    coordinator.onEnvelope(
                        .mediaKey(callId: "kat-call", epoch: epoch, index: GroupE2ee.keyIndex(forEpoch: epoch), key: source.key,
                                  pseudonym: owner.participantId),
                        from: owner.user)
                }
                // What the coordinator handed to the native key provider since the last step.
                for install in env.installs[applied...] {
                    rings[install.participantId, default: [:]][install.index] = install.key
                }
                applied = env.installs.count

                let ring = rings[scenario.participantId] ?? [:]
                for id in step.opens {
                    let frame = try XCTUnwrap(byId[id], id)
                    XCTAssertEqual(outcome(of: frame, ring: ring), .opens, "\(scenario.name) step \(number): \(id) must open")
                }
                for refusal in step.refused {
                    let frame = try XCTUnwrap(byId[refusal.frame], refusal.frame)
                    XCTAssertEqual(outcome(of: frame, ring: ring).rawValue, refusal.reason,
                                   "\(scenario.name) step \(number): \(refusal.frame) must be refused as \(refusal.reason)")
                }
            }
        }
    }

    func testEveryInstallLandsInTheSlotOfItsEpochForTheSendersOwnPseudonym() throws {
        let v = try load()
        let env = FakeE2eeEnvironment()
        let coordinator = GroupE2eeCoordinator(callId: "kat-call", selfUserId: "user-self", environment: env)
        var pseudonyms = ["user-self": String(repeating: "ff", count: 16)]
        for sender in v.senders { pseudonyms[sender.user] = sender.participantId }
        coordinator.onRoster(epoch: 1, members: ["user-self"] + v.senders.map { $0.user }, pseudonyms: pseudonyms)
        env.installs.removeAll()
        for c in v.cases where c.frame == "opus" {
            let user = try XCTUnwrap(v.senders.first { $0.participantId == c.participantId }).user
            coordinator.onEnvelope(.mediaKey(callId: "kat-call", epoch: c.epoch, index: Int32(c.keyIndex), key: c.key,
                                             pseudonym: c.participantId), from: user)
        }
        XCTAssertEqual(env.installs.count, 34, "17 epochs x 2 senders")
        for c in v.cases where c.frame == "opus" {
            XCTAssertTrue(env.installs.contains(.init(key: c.key, index: Int32(c.keyIndex), participantId: c.participantId)),
                          "K[\(c.sender),\(c.epoch)] goes to slot \(c.keyIndex) of \(c.sender)")
        }
    }

    // MARK: - P12 receiver replay window

    func testTheReplayScenariosYieldEveryVerdictOfTheFile() throws {
        let v = try load()
        var verdictsSeen = Set<String>()
        for scenario in v.replayScenarios {
            var handlers: [String: ReplayHandlerReference] = [:]
            for (number, step) in scenario.steps.enumerated() {
                let handler = handlers[step.participant] ?? ReplayHandlerReference(localSendSsrcs: scenario.localSendSsrcs)
                handlers[step.participant] = handler
                for install in step.install {
                    handler.install(key: install.key, slot: install.keyIndex)
                }
                guard let id = step.deliver else { continue }
                let frame = try XCTUnwrap(v.replayFrames[id], "\(scenario.name): no pool frame \(id)")
                let verdict = handler.receive(
                    wire: frame.wire, codec: frame.codec, isKeyFrame: frame.isKeyFrame,
                    unencryptedBytes: frame.unencryptedBytes)
                XCTAssertEqual(verdict.rawValue, step.expect, "\(scenario.name) step \(number): \(id)")
                verdictsSeen.insert(verdict.rawValue)
            }
        }
        XCTAssertEqual(verdictsSeen, ["ok", "duplicate", "too_old", "reflected", "cap", "decrypt_failed", "missing_key"],
                       "the scenarios exercise every verdict")
    }
}
