import XCTest
import CryptoKit
@testable import QAudionEngine

/// Group calls v2 (spec 5.1 - 5.4) — the cross-platform frame-crypto vectors
/// (`Resources/group-calls-v2-frame-crypto.json`), generated by the desktop's
/// byte-exact frame cryptor with `node:crypto` only, with synthetic keys.
///
/// What is pinned on iOS:
///  * the key derivation `aes_key = HKDF-SHA256(ikm = K[M,E], salt = empty,
///    info = 128 x 0x00, L = 32)` (the same one the native FrameCryptor runs),
///  * the frame wire layout `header(unencrypted_bytes) || ciphertext || tag(16) ||
///    iv(12) || [12, keyIndex]` with AAD = header, sealed and opened through the
///    Swift port of the frame cryptor (`LiveKitVideoFrameCryptor`, the same
///    layout the native one produces),
///  * `keyIndex = epoch mod 16` and the ring semantics: the receiver installs
///    `K[M,E]` at slot `E mod 16` of M's own ring, a frame is looked up by the
///    key index in its trailer, a slot overwritten by a later epoch no longer opens
///    the older epoch (`decrypt_failed`), an empty slot is `missing_key`, and
///    rings are per participant. The installs come from the real
///    `GroupE2eeCoordinator` (the code that feeds the native key provider), not from
///    a model written for the test.
final class GroupE2eeKatTests: XCTestCase {

    // MARK: - Vector file

    private struct Sender {
        let name: String
        let participantId: String
        var user: String { "user-" + name.lowercased() }
    }

    private struct KatCase {
        let sender: String
        let participantId: String
        let epoch: UInt32
        let keyIndex: Int
        let key: Data
        let aesKey: Data
        let frame: String
        let codec: String
        let isKeyFrame: Bool
        let ssrc: UInt32
        let rtpTimestamp: UInt32
        let iv: Data
        let unencryptedBytes: Int
        let plaintext: Data
        let wire: Data

        var id: String { "\(sender)/\(epoch)/\(frame)" }
        var frameCodec: LiveKitVideoFrameCryptor.FrameCodec { codec == "opus" ? .opus : .vp8 }
    }

    private struct Step {
        let install: [UInt32]
        let opens: [String]
        let refused: [(frame: String, reason: String)]
    }

    private struct Scenario {
        let name: String
        let participantId: String
        let steps: [Step]
    }

    private struct Vectors {
        let root: [String: Any]
        let senders: [Sender]
        let cases: [KatCase]
        let scenarios: [Scenario]
    }

    private static func hex(_ text: String) -> Data {
        var out = Data()
        var index = text.startIndex
        while index < text.endIndex {
            let next = text.index(index, offsetBy: 2)
            out.append(UInt8(text[index..<next], radix: 16) ?? 0)
            index = next
        }
        return out
    }

    private func load() throws -> Vectors {
        guard let url = Bundle.module.url(forResource: "group-calls-v2-frame-crypto", withExtension: "json") else {
            XCTFail("group-calls-v2-frame-crypto.json not found in Bundle.module")
            throw NSError(domain: "kat", code: 1)
        }
        let object = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
        let root = try XCTUnwrap(object as? [String: Any])
        let senders = try XCTUnwrap(root["senders"] as? [[String: Any]]).map {
            Sender(name: $0["name"] as? String ?? "", participantId: $0["participantId"] as? String ?? "")
        }
        let cases = try XCTUnwrap(root["cases"] as? [[String: Any]]).map { c -> KatCase in
            KatCase(
                sender: c["sender"] as? String ?? "",
                participantId: c["participantId"] as? String ?? "",
                epoch: UInt32(truncating: c["epoch"] as? NSNumber ?? 0),
                keyIndex: (c["keyIndex"] as? NSNumber)?.intValue ?? -1,
                key: Self.hex(c["key"] as? String ?? ""),
                aesKey: Self.hex(c["aesKey"] as? String ?? ""),
                frame: c["frame"] as? String ?? "",
                codec: c["codec"] as? String ?? "",
                isKeyFrame: (c["isKeyFrame"] as? NSNumber)?.boolValue ?? false,
                ssrc: UInt32(truncating: c["ssrc"] as? NSNumber ?? 0),
                rtpTimestamp: UInt32(truncating: c["rtpTimestamp"] as? NSNumber ?? 0),
                iv: Self.hex(c["iv"] as? String ?? ""),
                unencryptedBytes: (c["unencryptedBytes"] as? NSNumber)?.intValue ?? -1,
                plaintext: Self.hex(c["plaintext"] as? String ?? ""),
                wire: Self.hex(c["wire"] as? String ?? ""))
        }
        let scenarios = try XCTUnwrap(root["ringScenarios"] as? [[String: Any]]).map { s -> Scenario in
            let steps = (s["steps"] as? [[String: Any]] ?? []).map { step -> Step in
                Step(
                    install: (step["install"] as? [NSNumber] ?? []).map { UInt32(truncating: $0) },
                    opens: step["opens"] as? [String] ?? [],
                    refused: (step["refused"] as? [[String: String]] ?? []).map { (frame: $0["frame"] ?? "", reason: $0["reason"] ?? "") })
            }
            return Scenario(name: s["name"] as? String ?? "", participantId: s["participantId"] as? String ?? "", steps: steps)
        }
        return Vectors(root: root, senders: senders, cases: cases, scenarios: scenarios)
    }

    // MARK: - The file states the rule the code implements

    func testTheVectorFileDeclaresTheRuleTheCodeImplements() throws {
        let v = try load()
        XCTAssertEqual(v.root["version"] as? Int, 1)
        XCTAssertEqual((v.root["keyRingSize"] as? NSNumber)?.uint32Value, GroupE2ee.keyRingSize)
        let hkdf = try XCTUnwrap(v.root["hkdf"] as? [String: Any])
        XCTAssertEqual(hkdf["hash"] as? String, "sha256")
        XCTAssertEqual(hkdf["salt"] as? String, "", "empty salt")
        XCTAssertEqual(Self.hex(hkdf["info"] as? String ?? "x"), Data(count: 128), "info = 128 x 0x00")
        XCTAssertEqual((hkdf["length"] as? NSNumber)?.intValue, GroupE2ee.keyLength)
        let unencrypted = try XCTUnwrap(v.root["unencryptedBytes"] as? [String: Int])
        XCTAssertEqual(unencrypted, ["opus": 1, "vp8-key": 10, "vp8-delta": 3])
        XCTAssertEqual(v.cases.count, 102, "2 senders x epochs 1..17 x (opus, vp8 key, vp8 delta)")
        XCTAssertEqual(Set(v.cases.map { $0.epoch }), Set(UInt32(1)...17))
    }

    func testTheKeyIndexOfEveryCaseIsTheEpochModuloSixteenAndTheKeyIs32Bytes() throws {
        let v = try load()
        for c in v.cases {
            XCTAssertEqual(Int32(c.keyIndex), GroupE2ee.keyIndex(forEpoch: c.epoch), c.id)
            XCTAssertEqual(c.key.count, GroupE2ee.keyLength, c.id)
            XCTAssertEqual(c.wire.last, UInt8(c.keyIndex), "the trailer carries the key index: \(c.id)")
            XCTAssertEqual(c.wire[c.wire.count - 2], 12, "the trailer's first byte is the IV length: \(c.id)")
        }
        // The wrap: epoch 16 -> slot 0, epoch 17 -> slot 1.
        XCTAssertEqual(v.cases.first { $0.epoch == 16 }?.keyIndex, 0)
        XCTAssertEqual(v.cases.first { $0.epoch == 17 }?.keyIndex, 1)
    }

    // MARK: - HKDF

    func testEveryDerivedAesKeyMatches() throws {
        for c in try load().cases {
            let derived = LiveKitVideoFrameCryptor.deriveFrameCryptorKey(pqcSessionKey: c.key)
            XCTAssertEqual(derived, c.aesKey, "aes_key of \(c.id)")
        }
    }

    // MARK: - Wire layout

    func testEveryFrameIsReproducedByteForByteExceptTheKeyIndexOfThe1To1Cryptor() throws {
        for c in try load().cases {
            // A fresh cryptor per case: the first frame of its ssrc, send count 0.
            let cryptor = LiveKitVideoFrameCryptor(keyProvider: { c.key })
            XCTAssertEqual(
                LiveKitVideoFrameCryptor.unencryptedBytes(codec: c.frameCodec, isKeyFrame: c.isKeyFrame, data: c.plaintext),
                c.unencryptedBytes, "unencrypted bytes of \(c.id)")
            let sealed = try cryptor.seal(data: c.plaintext, codec: c.frameCodec, isKeyFrame: c.isKeyFrame,
                                          ssrc: c.ssrc, rtpTimestamp: c.rtpTimestamp)
            // The 1:1 cryptor pins key index 0 in the trailer; the group wire carries
            // epoch mod 16 there (the native key provider picks the slot). Everything
            // before that last byte is the same frame.
            XCTAssertEqual(sealed.count, c.wire.count, c.id)
            XCTAssertEqual(Data(sealed.dropLast()), Data(c.wire.dropLast()), "wire of \(c.id)")
            // header || ciphertext || tag || iv || trailer: the IV sits before the 2-byte trailer.
            XCTAssertEqual(Data(c.wire.suffix(14).prefix(12)), c.iv, "iv of \(c.id)")
            // The header stays in the clear (qjanus needs the codec bytes).
            XCTAssertEqual(Data(c.wire.prefix(c.unencryptedBytes)), Data(c.plaintext.prefix(c.unencryptedBytes)), c.id)
        }
    }

    func testEveryWireOpensToItsPlaintextAndIsAuthenticated() throws {
        for c in try load().cases {
            let cryptor = LiveKitVideoFrameCryptor(keyProvider: { c.key })
            XCTAssertEqual(try cryptor.open(data: c.wire, codec: c.frameCodec, isKeyFrame: c.isKeyFrame), c.plaintext, c.id)

            var headerFlip = c.wire
            headerFlip[0] ^= 0x01
            XCTAssertThrowsError(try cryptor.open(data: headerFlip, codec: c.frameCodec, isKeyFrame: c.isKeyFrame),
                                 "the header is the AAD: \(c.id)")

            var bodyFlip = c.wire
            bodyFlip[c.unencryptedBytes] ^= 0x01
            XCTAssertThrowsError(try cryptor.open(data: bodyFlip, codec: c.frameCodec, isKeyFrame: c.isKeyFrame),
                                 "the ciphertext is authenticated: \(c.id)")

            var otherKey = c.key
            otherKey[0] ^= 0x01
            let wrong = LiveKitVideoFrameCryptor(keyProvider: { otherKey })
            XCTAssertThrowsError(try wrong.open(data: c.wire, codec: c.frameCodec, isKeyFrame: c.isKeyFrame),
                                 "another key never opens it: \(c.id)")
        }
    }

    // MARK: - Ring semantics, driven by the real coordinator

    private enum Outcome: String {
        case opens
        case missingKey = "missing_key"
        case decryptFailed = "decrypt_failed"
    }

    /// What the receiver does with `frame`: look the trailer's key index up in the
    /// ring of `participantId`, then try to open the frame with that slot's key.
    private func outcome(of frame: KatCase, ring: [Int32: Data]) -> Outcome {
        let slot = Int32(frame.wire.last ?? 0)
        guard let key = ring[slot] else { return .missingKey }
        let cryptor = LiveKitVideoFrameCryptor(keyProvider: { key })
        return (try? cryptor.open(data: frame.wire, codec: frame.frameCodec, isKeyFrame: frame.isKeyFrame)) == nil
            ? .decryptFailed : .opens
    }

    func testTheRingScenariosAreReproducedByTheCoordinatorsInstallsAndTheFrameLookup() throws {
        let v = try load()
        XCTAssertEqual(v.scenarios.count, 3)
        let byId = Dictionary(uniqueKeysWithValues: v.cases.map { ($0.id, $0) })
        for scenario in v.scenarios {
            let env = FakeE2eeEnvironment()
            let coordinator = GroupE2eeCoordinator(callId: "kat-call", selfUserId: "user-self", environment: env)
            var pseudonyms = ["user-self": String(repeating: "ff", count: 16)]
            for sender in v.senders { pseudonyms[sender.user] = sender.participantId }
            coordinator.onRoster(epoch: 1, members: ["user-self"] + v.senders.map { $0.user }, pseudonyms: pseudonyms)
            let owner = try XCTUnwrap(v.senders.first { $0.participantId == scenario.participantId }, scenario.name)

            var rings: [String: [Int32: Data]] = [:]
            var applied = 0
            for (number, step) in scenario.steps.enumerated() {
                for epoch in step.install {
                    let source = try XCTUnwrap(v.cases.first { $0.participantId == scenario.participantId && $0.epoch == epoch },
                                               "\(scenario.name): no vector for epoch \(epoch)")
                    coordinator.onEnvelope(
                        .mediaKey(callId: "kat-call", epoch: epoch, index: GroupE2ee.keyIndex(forEpoch: epoch), key: source.key),
                        from: owner.user)
                }
                // What the coordinator handed to the native key provider since the last step.
                for install in env.installs[applied...] {
                    rings[install.participantId, default: [:]][install.index] = install.key
                }
                applied = env.installs.count

                let ring = rings[scenario.participantId] ?? [:]
                for id in step.opens {
                    let frame = try XCTUnwrap(byId[id], id)
                    XCTAssertEqual(outcome(of: frame, ring: ring), .opens, "\(scenario.name) step \(number): \(id) must open")
                }
                for refusal in step.refused {
                    let frame = try XCTUnwrap(byId[refusal.frame], refusal.frame)
                    XCTAssertEqual(outcome(of: frame, ring: ring).rawValue, refusal.reason,
                                   "\(scenario.name) step \(number): \(refusal.frame) must be refused as \(refusal.reason)")
                }
            }
        }
    }

    func testEveryInstallLandsInTheSlotOfItsEpochForTheSendersOwnPseudonym() throws {
        let v = try load()
        let env = FakeE2eeEnvironment()
        let coordinator = GroupE2eeCoordinator(callId: "kat-call", selfUserId: "user-self", environment: env)
        var pseudonyms = ["user-self": String(repeating: "ff", count: 16)]
        for sender in v.senders { pseudonyms[sender.user] = sender.participantId }
        coordinator.onRoster(epoch: 1, members: ["user-self"] + v.senders.map { $0.user }, pseudonyms: pseudonyms)
        env.installs.removeAll()
        for c in v.cases where c.frame == "opus" {
            let user = try XCTUnwrap(v.senders.first { $0.participantId == c.participantId }).user
            coordinator.onEnvelope(.mediaKey(callId: "kat-call", epoch: c.epoch, index: Int32(c.keyIndex), key: c.key), from: user)
        }
        XCTAssertEqual(env.installs.count, 34, "17 epochs x 2 senders")
        for c in v.cases where c.frame == "opus" {
            XCTAssertTrue(env.installs.contains(.init(key: c.key, index: Int32(c.keyIndex), participantId: c.participantId)),
                          "K[\(c.sender),\(c.epoch)] goes to slot \(c.keyIndex) of \(c.sender)")
        }
    }
}
